Color Theme Setup
WookieeMatt/Essence20 pull request #204
Opened 2022-09-18 19:58 UTC by WookieeMatt

2022-09-19 02:49 UTC, phildominguez requested changes
Looks great! Just a few comments. 

I'd also be in favor of making the default background a dark grey gradient instead of the current blueish one, so it doesn't clash with whatever color they pick. Probably something neutral for the tab and skill header colors, too. Thoughts on that @guswadsworth12 ?

2022-09-19 02:49 UTC, phildominguez commented on module/settings.js
> +
Can remove this

2022-09-19 02:49 UTC, phildominguez commented on templates/actor/parts/headers/actor-pr-header.hbs
> +</div>
![image](https://user-images.githubusercontent.com/41161497/190941953-c9481196-213a-4f03-bcf6-69ce9026d9be.png)
Could the "Color" label be centered?

2022-09-19 02:49 UTC, phildominguez commented on system.json
>  {
Is this a new system.json format for v10 or something?

2022-09-21 16:35 UTC, guswadsworth12 commented
> Looks great! Just a few comments.
> 
> I'd also be in favor of making the default background a dark grey gradient instead of the current blueish one, so it doesn't clash with whatever color they pick. Probably something neutral for the tab and skill header colors, too. Thoughts on that @guswadsworth12 ?

This is probably a good idea. Let me see what I can do.

2022-09-22 14:46 UTC, guswadsworth12 commented on templates/actor/parts/headers/actor-pr-header.hbs
> +</div>
This would need a new resource-label Class just for this one too show centered

2022-09-22 16:14 UTC, phildominguez commented on templates/actor/parts/headers/actor-pr-header.hbs
> +</div>
Looks good now

2022-09-22 16:17 UTC, phildominguez commented on module/settings.js
> +
I've removed this

2022-09-22 16:19 UTC, phildominguez approved these changes

2022-09-22 16:21 UTC, merged