Added Evasion bonus option to Armor
WookieeMatt/Essence20 pull request #227
Opened 2023-01-29 01:56 UTC by JFranklin3000

2023-01-29 04:40 UTC, phildominguez requested changes
Good stuff, just some tweaks!

2023-01-29 04:40 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +            equippedArmorEvasion += parseInt(i.system.armorEvasion);
These need to match the fields added in `template.json`, otherwise the default values won't set. I think I like `bonusEvasion` and `bonusToughness`, but that would have to get fixed elsewhere. Lmk what you think.

2023-01-29 04:40 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    context.equippedArmorEvasion = equippedArmorEvasion;
Alphabetical here, too.

2023-01-29 04:40 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    let equippedArmorEvasion = 0;
Not sure why this was out of alphabetical order in the first place, let's move them where they should be.

2023-01-29 04:40 UTC, phildominguez commented on template.json
> +      "evasionBonus": 1,
Please retain alphabetical order :)

2023-01-29 17:02 UTC, phildominguez commented on lang/en.json
> +    "bonusToughness": "Toughness Bonus",
For items in the en.json we follow the dnd5e system naming convention, where it starts with the item type. So we can remove lines 71-72 and replace lines 59-60 with "ArmorBonusEvasion": "Bonus Evasion" etc.

2023-01-29 17:07 UTC, phildominguez commented on template.json
> +      "bonusToughness": 0,
Alphabetical :)

2023-01-29 17:18 UTC, JFranklin3000 commented on lang/en.json
> +    "bonusToughness": "Toughness Bonus",
Changes made

2023-01-29 17:18 UTC, JFranklin3000 commented on template.json
> +      "bonusToughness": 0,
Changes made,

2023-02-05 23:17 UTC, phildominguez approved these changes

2023-02-06 00:04 UTC, phildominguez requested changes
Currently seeing an error about locking compendiums post migration. Still looking into it.

2023-02-07 01:56 UTC, phildominguez approved these changes
Migrations now working

2023-02-07 01:57 UTC, merged