Transformers sheet
WookieeMatt/Essence20 pull request #233
Opened 2023-02-05 04:42 UTC by JFranklin3000

2023-02-05 14:49 UTC, phildominguez requested changes
Great start!

2023-02-05 14:49 UTC, phildominguez commented on template.json
> +      "tranformerMode": "botMode",
Are there armor types that can only be used in certain modes?

2023-02-05 14:49 UTC, phildominguez commented on lang/en.json
> +    "AltMode": "Alt Mode",
Thoughts on making them `ModeAltMode` , `ModeBotMode`, `ModeBoth` for grouping?

2023-02-05 14:49 UTC, phildominguez commented on templates/actor/parts/actor-altmode.hbs
> +  <label for="system.altModesize" class="resource-label">{{localize 'E20.AltModeSize'}}</label>
`E20.AltModeSize` not defined

2023-02-05 14:49 UTC, phildominguez commented on templates/actor/parts/actor-altmode.hbs
> +</div>
What are your thoughts as far as the ordering of all the elements for this tab? Maybe defense on top (to match other tabs), followed by Weapons, then a single row with Crew/Size/Movement, and Origin at the bottom?

2023-02-05 14:49 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    const altmode =[];
Needed?

2023-02-05 14:49 UTC, phildominguez commented on templates/actor/parts/actor-hardpoint-selector.hbs
> +</select>
Should this be called actor-mode-selector.hbs, or something along those lines?

2023-02-05 14:49 UTC, phildominguez commented on templates/actor/parts/actor-movement-altmode.hbs
> +</div>
We should make a movement template so that we don't have a lot of duplicated code between this file and actor-movement.hbs. That way we can just pass in `system.movement` or `system.altmodemovement` as a parameter. I can explain more on Discord.

2023-02-05 14:49 UTC, phildominguez commented on templates/actor/parts/actor-weapons.hbs
> +      {{/ifEquals}}
Handlebars supports `{{else ifEquals... }}`

2023-02-05 14:49 UTC, phildominguez commented on templates/actor/parts/actor-defenses-altmode.hbs
> +</div>
Might be able to make use of a template for defenses, too? Explained more in another comment.

2023-02-05 15:18 UTC, JFranklin3000 commented on lang/en.json
> +    "Autobots": "Autobots",
fixed.

2023-02-05 15:20 UTC, JFranklin3000 commented on module/helpers/config.mjs
> +  bothMode: "E20.BothMode"
Any probably makes a lot more sense. Of course now that we are thinking about multi-forms. We might need an option to pick the alt mode.

2023-02-05 15:22 UTC, JFranklin3000 commented on template.json
> +    },
moved to Transformer

2023-02-05 15:34 UTC, JFranklin3000 commented on templates/actor/parts/actor-altmode.hbs
> +</div>
It was definitely a temp out based on what is on the character sheet so I was expecting to reorder.

2023-02-05 15:35 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +    const altmode =[];
For now no, but if we go to alt modes as items then we will.

2023-02-05 15:40 UTC, JFranklin3000 commented on template.json
> +      "tranformerMode": "botMode",
Not yet. I was looking for that and didn't see anything.

2023-02-05 15:46 UTC, JFranklin3000 commented on templates/actor/parts/actor-weapons.hbs
> +      {{/ifEquals}}
fixed

2023-02-05 18:19 UTC, JFranklin3000 commented on lang/en.json
> +    "AltMode": "Alt Mode",
Fixed

2023-02-05 18:20 UTC, JFranklin3000 commented on lang/en.json
> +    "AltMode": "Alt Mode",
I did `ModeAltMode`, `ModeBotMode` and `ModeAny`

2023-02-05 18:21 UTC, JFranklin3000 commented on templates/actor/parts/actor-altmode.hbs
> +  <label for="system.altModesize" class="resource-label">{{localize 'E20.AltModeSize'}}</label>
fixed

2023-02-08 05:15 UTC, JFranklin3000 commented on templates/actor/parts/actor-hardpoint-selector.hbs
> +</select>
Change Made

2023-02-08 14:00 UTC, closed without merging