Update to Perks to add Type and Game System
WookieeMatt/Essence20 pull request #250
Opened 2023-02-11 04:51 UTC by JFranklin3000

2023-02-11 14:33 UTC, phildominguez requested changes
![image](https://user-images.githubusercontent.com/41161497/218263518-27efb84e-9faf-4916-bece-b0a59818d5ce.png)
Game System and Type should show up in some capacity when the item is expanded on the actor sheet. Probably as chips?
![image](https://user-images.githubusercontent.com/41161497/218263576-bfdc82cf-1d6a-4692-819c-650672ea08cd.png)
Similar for the chat card, though now I'm noticing Source is broken there.

2023-02-11 14:34 UTC, phildominguez commented
Also just wanted to confirm that System should be checkboxes and not a selector? Are there Perks shared between the systems?

2023-02-11 15:14 UTC, JFranklin3000 commented
> Also just wanted to confirm that System should be checkboxes and not a selector? Are there Perks shared between the systems?
![image](https://user-images.githubusercontent.com/71140111/218266120-9aefe7a0-9134-4f9d-8fe7-aea2289124d7.png)

![image](https://user-images.githubusercontent.com/71140111/218266148-0b2af97e-e665-4947-9d1e-56afa953a2c4.png)

![image](https://user-images.githubusercontent.com/71140111/218266168-e60e7e23-2d27-4666-ad4b-830b062f2684.png)
 
First General Perk in the 3 existing games

2023-02-11 15:27 UTC, phildominguez commented
> 

Gotcha, thanks for the example!

2023-03-30 23:13 UTC, phildominguez requested changes
Couple small things 👍

2023-03-30 23:13 UTC, phildominguez commented on module/helpers/config.mjs
> +
Remove extra newline

2023-03-30 23:13 UTC, phildominguez commented on template.json
> +      "type": "General"
This should be `"general"` to match the key in config.mjs

2023-03-30 23:13 UTC, phildominguez commented on templates/item/item-perk-sheet.hbs
> +    {{/"systems/essence20/templates/item/parts/item-sheet-field.hbs"}}
Indentation is off for lines within the div

2023-03-30 23:17 UTC, JFranklin3000 commented on templates/item/item-perk-sheet.hbs
> +    {{/"systems/essence20/templates/item/parts/item-sheet-field.hbs"}}
fixed

2023-03-30 23:17 UTC, JFranklin3000 commented on template.json
> +      "type": "General"
changed

2023-03-30 23:17 UTC, JFranklin3000 commented on module/helpers/config.mjs
> +
removed

2023-03-30 23:48 UTC, phildominguez requested changes

2023-03-30 23:48 UTC, phildominguez commented on templates/item/item-perk-sheet.hbs
> +
```suggestion
```

2023-03-30 23:48 UTC, phildominguez commented on templates/item/item-perk-sheet.hbs
> +
```suggestion
```
Nbd to me if there's a newline here or not, but there's no corresponding newline where the div closes.

2023-03-31 00:00 UTC, JFranklin3000 commented on templates/item/item-perk-sheet.hbs
> +
Changes made

2023-03-31 00:00 UTC, JFranklin3000 commented on templates/item/item-perk-sheet.hbs
> +
changes made

2023-03-31 00:21 UTC, phildominguez approved these changes

2023-03-31 00:21 UTC, merged