Draft: Add active effects
WookieeMatt/Essence20 pull request #276
Opened 2023-02-17 18:30 UTC by JFranklin3000

Active Effects are active on character actors and on perks and hang-ups for now.

2023-02-18 00:13 UTC, phildominguez requested changes
Haven't fully tested yet, but I know you like syntax feedback!

2023-02-18 00:13 UTC, phildominguez commented on templates/actor/parts/actor-active-effects.hbs
> +</ol>
Is it possible to style the containers to be like the collapsible item containers we have?

2023-02-18 00:13 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +    context.effects = prepareActiveEffectCategories(this.object.effects);
I get this when I open the sheet and whatnot:
![image](https://user-images.githubusercontent.com/41161497/219819169-ad70d9bb-9869-42e9-895a-8ec95384e4bf.png)
I think just make this `e.disabled` here https://github.com/WookieeMatt/Essence20/blob/main/module/helpers/effects.mjs#L58

2023-02-18 00:36 UTC, JFranklin3000 commented
test cases on both user and item
add effect that increases Essences (system.essences.<name> Add X)
add effect that increases Defenses in same way (system.bonuses.<name> Add X)
add effect that sets skill to value (system.skills.<essence>.<skill>.shift set d8 or whatever)
add effect that sets bonus to skill (system.skills.<essence>.<skill>.modifier Add X)

2023-02-18 15:21 UTC, JFranklin3000 commented on lang/en.json
> +    "EffectEnable": "Enable Effect",
renamed to ActiveEffectAdd for example. Duration just got missed.

2023-02-18 15:22 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +
removed

2023-02-18 15:23 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +import { onManageActiveEffect, prepareActiveEffectCategories } from "../helpers/effects.mjs";
Moved.

2023-02-18 15:23 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    // Prepare active effects
Added.

2023-02-18 15:27 UTC, JFranklin3000 commented on templates/item/parts/item-active-effects.hbs
> +</ol>
Fixed indenting

2023-02-18 15:28 UTC, JFranklin3000 commented on templates/item/parts/item-active-effects.hbs
> +                   data-tooltip="{{#if effect.disabled}}E20.EffectEnable{{else}}E20.EffectDisable{{/if}}">
yep, not taking credit for it I borrowed that from the 5e code.

2023-02-18 15:28 UTC, JFranklin3000 commented on templates/actor/parts/actor-active-effects.hbs
> +</ol>
I would think so I asked @guswadsworth12 to take a look as well.

2023-02-18 15:38 UTC, JFranklin3000 commented on templates/actor/actor-powerRanger-sheet.hbs
> +
how do you mean that is the div for the tab, not sure why the list gets created outside of the tab div though.

2023-02-19 00:32 UTC, phildominguez requested changes

2023-02-19 00:32 UTC, phildominguez commented on templates/actor/actor-giJoe-sheet.hbs
> +    <div class="tab background flexcol" data-group="primary" data-tab="effects"></div>
`background` here should be `effects` to match `data-tab` above. Needs to be fixed for all sheets.

There's also a trailing `</div>` on this line that's causing it to show up on every tab.

2023-02-19 00:32 UTC, phildominguez commented on templates/actor/parts/actor-active-effects.hbs
> +</ol>
We spoke offline but just to note, I only mean the rounded border style and whatnot, not actually make it work with collapsible-item-container just yet

2023-02-19 00:32 UTC, phildominguez commented on templates/item/item-hangUp-sheet.hbs
> +
You're probably aware:
![image](https://user-images.githubusercontent.com/41161497/219905594-b56aaf36-f821-4a9b-a690-6915a25cf251.png)
Should we go with an Effects tab like the actor sheets?

2023-02-19 19:56 UTC, JFranklin3000 commented on templates/actor/parts/actor-active-effects.hbs
> +</ol>
Border added

2023-02-19 19:56 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +import { onManageActiveEffect, prepareActiveEffectCategories } from "../helpers/effects.mjs";
Added

2023-02-19 23:37 UTC, phildominguez commented on templates/actor/parts/actor-active-effects.hbs
> +</ol>
![image](https://user-images.githubusercontent.com/41161497/219982181-336d7417-d454-403a-9afb-83603b665c18.png)
Sorry for the confusion, this is what I meant. Remove the outer border, round the ones around the headers, and be sure they use the actor's color. I think make the font larger so it matches what we use elsewhere as well.

2023-02-19 23:43 UTC, phildominguez requested changes

2023-02-19 23:43 UTC, phildominguez commented on templates/item/item-perk-sheet.hbs
> +
Remove space 🙂

2023-02-20 15:37 UTC, phildominguez requested changes

2023-02-20 15:37 UTC, phildominguez commented on sass/assets/_headers.scss
> +  box-shadow: v.$boxshadow;
I think you didn't run `sass sass/essence20.scss css/essence20.css`, so this was never applied to the CSS.

2023-02-20 15:37 UTC, phildominguez commented on templates/item/item-altmode-sheet.hbs
> +    </div>
![image](https://user-images.githubusercontent.com/41161497/220146963-4186c253-b423-44b1-8e18-1a2b4ac4e154.png)
With the default item sheet width, this does not look great

2023-02-20 15:37 UTC, phildominguez commented on templates/actor/parts/actor-active-effects.hbs
> +<div class="stats-container defense-container" style="border-color: {{system.color}};">
Don't think we need this border

2023-02-20 15:37 UTC, phildominguez commented on templates/actor/parts/actor-active-effects.hbs
> +    <li class="items-header flexrow" data-effect-type="{{section.type}}">
Make the border color the actor's color

2023-02-20 15:37 UTC, phildominguez commented on templates/item/item-altmode-sheet.hbs
> +    <a class="item" style="border-color: {{system.color}};" data-tab="details">{{ localize "E20.TabDetails" }}</a>
`E20.*` strings aren't defined

I also would not split up the main tab into description and details in this PR. It's not really related to this work and is something we should discuss first. If we want to go for it, we can do it for all items at once.

2023-02-23 02:50 UTC, phildominguez requested changes

2023-02-23 02:50 UTC, phildominguez commented on templates/item/item-altmode-sheet.hbs
> +    <a class="item" style="border-color: {{system.color}};" data-tab="effects">{{ localize "E20.TabEffects" }}</a>
`border-color` not needed here

2023-02-23 02:50 UTC, phildominguez commented on templates/item/parts/item-active-effects.hbs
> +      <div class="effect-duration">{{effect.duration.label}}</div>
`effect-source` and `effect-duration` don't seem to be needed. Let's remove them in the hbs and scss

2023-02-23 03:24 UTC, JFranklin3000 commented on templates/item/parts/item-active-effects.hbs
> +      <div class="effect-duration">{{effect.duration.label}}</div>
I didn't add them to the scss they were already there. but I have no issue removing if that won't affect anything else.

2023-02-23 03:24 UTC, JFranklin3000 commented on templates/item/item-altmode-sheet.hbs
> +    <a class="item" style="border-color: {{system.color}};" data-tab="effects">{{ localize "E20.TabEffects" }}</a>
Removed.

2023-02-23 03:24 UTC, JFranklin3000 commented on templates/actor/parts/actor-active-effects.hbs
> +    <li class="items-header flexrow" data-effect-type="{{section.type}}">
Added on the Item Sheet.

2023-02-23 04:22 UTC, phildominguez commented on templates/item/parts/item-active-effects.hbs
> +      <div class="effect-duration">{{effect.duration.label}}</div>
Ohh okay. Yeah I feel like if it doesn't do anything let's remove it from the hbs. I'm fine with leaving it in the scss.

2023-02-23 16:39 UTC, guswadsworth12 commented
Bug Identified:

Can not change the number of turns that an effect lasts for. Rounds works though. 
![image](https://user-images.githubusercontent.com/28365506/220972076-9fa767fc-5aec-4bc8-b159-0da8d9a7d792.png)

2023-02-23 19:35 UTC, phildominguez requested changes

2023-02-23 19:35 UTC, phildominguez commented on sass/items/_item-styling.scss
> +  padding-bottom: 5px;
![image](https://user-images.githubusercontent.com/41161497/221011736-ab8a428f-4468-49a9-95fa-7dc9f86176f7.png)
I think we want to remove this bottom padding

2023-02-24 00:38 UTC, JFranklin3000 commented on sass/items/_item-styling.scss
> +  padding-bottom: 5px;
this has been removed.

2023-02-24 04:57 UTC, phildominguez approved these changes

2023-02-27 15:05 UTC, guswadsworth12 approved these changes
Looks and works good approved.

2023-02-28 23:52 UTC, merged