Added bonusShift to all skills and pass it to the dice roll dialog
WookieeMatt/Essence20 pull request #283
Opened 2023-02-20 16:36 UTC by JFranklin3000

added a bonusShift to all skills for use with effects, Perk bonuses, etc.

2023-02-28 14:08 UTC, guswadsworth12 commented
How do you want this tested?

2023-02-28 14:22 UTC, phildominguez requested changes

2023-02-28 14:22 UTC, phildominguez commented on module/dice.mjs
> +    shiftDown =  dataset.downshift;
22-25 can be removed if you do my suggestion below. Also, typically [let is used instead of var](https://sentry.io/answers/difference-between-let-and-var-in-javascript/#:~:text=The%20difference%20between%20let%20and,in%20which%20they're%20declared.).

2023-02-28 14:22 UTC, phildominguez commented on module/dice.mjs
> +        shiftDown,
```suggestion
        shiftUp: dataset.upshift,
        shiftDown: dataset.downshift,
```

2023-02-28 15:25 UTC, JFranklin3000 commented on module/dice.mjs
> +        shiftDown,
I pushed those changes that is much cleaner.

2023-02-28 15:29 UTC, JFranklin3000 commented on module/dice.mjs
> +        shiftDown,
It is a bit complicated to test so I hadn't written it out yet. But here it is. Go to the Active Effects Branch and create a perk or effect on an actor with the following. (or something similar for another skill) You can also do shiftDown as well. 

![image](https://user-images.githubusercontent.com/71140111/221899440-475e8e76-668e-4c53-90e1-a6fcfaa6984a.png)

Then flip to the automatic-upshifts branch and add the perk if you made that and roll that skill.  you should see the Up or Down Shift box on the roll dialog populated with the values you added.

2023-03-02 01:13 UTC, phildominguez approved these changes

2023-03-02 01:24 UTC, merged