Added Spells Tab
WookieeMatt/Essence20 pull request #295
Opened 2023-03-17 19:32 UTC by JFranklin3000

Changed the Powers Tab to Spells on the Pony Sheet
added the Spellcasting skill and a place to add spells.

2023-03-18 14:00 UTC, phildominguez commented
![image](https://user-images.githubusercontent.com/41161497/226110603-8755c227-45d4-4b05-b6c2-b7ce51ab3f72.png)
Somehow this dot is showing up, even though you didn't touch actor-essence-skills.hbs🤔

2023-03-18 14:09 UTC, phildominguez requested changes
Works nicely!

2023-03-18 14:09 UTC, phildominguez commented on templates/actor/parts/items/spell/container.hbs
> +{{/each}}
`container.hbs` files for other items only have an `actor-collapsible-item-container` in them. I would make an `actor/parts/actor-spells.hbs` and do this:
```
{{!-- Spellcasting Skill --}}
{{#each system.skills.any as |fields skill|}}
{{> "systems/essence20/templates/actor/parts/actor-essence-skills.hbs" essence='any' skill='spellcasting' fields=fields}}
{{/each}}

{{!-- Spells --}}
{{> "systems/essence20/templates/actor/parts/items/spell/container.hbs"}}
```

Then in `actor-pony-sheet.hbs` you'd use `actor-spells.hbs`

2023-03-18 14:22 UTC, JFranklin3000 commented on module/helpers/config.mjs
> +  any: "E20.EssenceAny",
I went with any because you can use an Essence increase from any Essence to increase spellcasting. Looking towards when we start tracking that if we ever do.

2023-03-18 15:39 UTC, JFranklin3000 commented on templates/actor/parts/items/spell/container.hbs
> +{{/each}}
added sheet

2023-03-18 18:11 UTC, phildominguez commented
![image](https://user-images.githubusercontent.com/41161497/226126086-bf43444d-2dc0-4d65-8781-479ea2edd9cb.png)
This is definitely better! I'm not a big fan of the huge text input though... What about splitting this tab in half, with Spellcasting on one side, and Spells on the other? Dunno, I'm open to ideas.

2023-03-20 00:26 UTC, phildominguez commented
![image](https://user-images.githubusercontent.com/41161497/226220058-972f529b-3b25-4d32-a14c-f21794851724.png)
We'll have to tweak how we're iterating over essences for this

2023-03-20 00:33 UTC, phildominguez commented on sass/actors/_pony-sheet.scss
> +}
Since it's in a flex row you don't need `float`, and the two percentages should total 100% (the full width)

2023-03-20 00:37 UTC, JFranklin3000 commented on sass/actors/_pony-sheet.scss
> +}
I deleted the floats, but for some reason if I reduce the width of the one from 100% it looks wrong.

2023-03-20 00:39 UTC, phildominguez commented on sass/actors/_pony-sheet.scss
> +}
This works for me:
```
.essence20 .spellcasting{
  width: 35%;
}

.essence20 .spells{
  width: 65%;
}
```

2023-03-20 00:40 UTC, phildominguez commented on sass/actors/_pony-sheet.scss
> +}
OH I didn't run the CSS command. Hmm...

2023-03-20 13:11 UTC, phildominguez commented on templates/actor/parts/actor-spell.hbs
Since the tab name is `spells` let's call this `actor-spells.hbs`

2023-03-20 15:02 UTC, phildominguez commented on templates/actor/parts/actor-spell.hbs
> +    {{#each system.skills.any as |fields skill|}}
Because if you remove the `#each` then `fields` isn't defined. Replace `fields=fields` with `fields=system.skills.any.spellcasting`

2023-03-20 15:54 UTC, JFranklin3000 commented on templates/actor/parts/actor-spell.hbs
> +    {{#each system.skills.any as |fields skill|}}
fixed.

2023-03-20 16:23 UTC, merged