Adding Magic Bauble to MLP
WookieeMatt/Essence20 pull request #308
Opened 2023-03-22 23:10 UTC by JFranklin3000

Added a Magic Bauble Item Type 
Added a Magic Bauble to the Gear Section of the Pony Sheet.

2023-03-22 23:56 UTC, phildominguez commented
You'll have to add `TypeMagicbauble` to `E20.ITEM` so it shows up in the Create New Item menu

2023-03-23 00:08 UTC, phildominguez requested changes
Works great, just a few things

2023-03-23 00:08 UTC, phildominguez commented on template.json
> +      "spellCastingShift": "d2"
For some reason this is defaulting to Critical Success for me

2023-03-23 00:08 UTC, phildominguez commented on templates/actor/parts/items/magicBauble/details.hbs
> +  <span class="chip" name="chip.spell.magicBaubleSpellcastingShift">{{localize 'E20.MagicBaubleSpellcastingShift'}}: {{item.system.magicBaubleSpellcastingShift}}</span>
![image](https://user-images.githubusercontent.com/41161497/227065910-28d75294-4603-453e-9a47-261d156053a5.png)
This would have to get localized

2023-03-23 00:30 UTC, JFranklin3000 commented on lang/en.json
> +    "MagicBaubleSpellcastingShift": "Magic Bauble Spellcasting",
the Spellcasting Skill noted on the Magic Bauble is what it is called in the rules.

2023-03-23 00:30 UTC, JFranklin3000 commented on module/documents/item.mjs
> +      const downshift = 0;
removed

2023-03-23 00:48 UTC, JFranklin3000 commented on template.json
> +      "spellCastingShift": "d2"
fixed.

2023-03-23 00:56 UTC, JFranklin3000 commented on templates/actor/parts/items/magicBauble/details.hbs
> +  <span class="chip" name="chip.spell.magicBaubleSpellcastingShift">{{localize 'E20.MagicBaubleSpellcastingShift'}}: {{item.system.magicBaubleSpellcastingShift}}</span>
fixed.

2023-03-23 12:59 UTC, phildominguez commented on template.json
> +      "magicBaubleSpellcastingShift": "d2"
Why add magicBauble to the front? Isn't it redundant?

2023-03-23 13:02 UTC, JFranklin3000 commented on lang/en.json
> +    "MagicBaubleSpellcastingShift": "Magic Bauble Spellcasting",
I can see that. I was trying to specify where that came from since the player has two options. I will make that change.

2023-03-23 13:07 UTC, JFranklin3000 commented on template.json
> +      "magicBaubleSpellcastingShift": "d2"
That was what was causing the critical Success issue you found earlier. when it was
`      ],
      "duration": "",
      "range": "",
      "spellCastingShift": "d2"`
The d2 wasn't getting applied because the names didn't match. we could go the other way.

2023-03-23 14:33 UTC, JFranklin3000 commented on template.json
> +      "magicBaubleSpellcastingShift": "d2"
renamed the fields on their and the item sheet.

2023-03-23 15:02 UTC, phildominguez commented on templates/actor/parts/items/magicBauble/details.hbs
Update the `item.system.magicBauble*` values here too

2023-03-23 15:03 UTC, phildominguez commented on module/documents/item.mjs
> +      const shift = this.system.magicBaubleSpellcastingShift;
And here

2023-03-23 15:30 UTC, guswadsworth12 approved these changes
Looks great man! works well too!

2023-03-23 15:41 UTC, JFranklin3000 commented on templates/actor/parts/items/magicBauble/details.hbs
updated those

2023-03-23 15:45 UTC, phildominguez approved these changes
🪄

2023-03-23 15:48 UTC, merged