Add Stun tracking to Character sheets.
WookieeMatt/Essence20 pull request #336
Opened 2023-03-29 00:26 UTC by JFranklin3000

Added a field by health to track stun.

2023-03-30 13:27 UTC, guswadsworth12 requested changes
Add this field to NPC sheet as well.

2023-03-30 13:54 UTC, JFranklin3000 commented
added to the NPC sheet.

2023-03-30 23:27 UTC, phildominguez requested changes
Works nicely! Small stuff.

2023-03-30 23:27 UTC, phildominguez commented on templates/actor/actor-npc-sheet.hbs
> +          {{!-- Health --}}
```suggestion
          {{!-- Stun --}}
```

2023-03-30 23:27 UTC, phildominguez commented on templates/actor/parts/actor-common.hbs
> +    {{!-- Stun --}}
```suggestion
  {{!-- Stun --}}
```

2023-03-30 23:27 UTC, phildominguez commented on templates/actor/parts/actor-stun.hbs
> +      <input class="centered-input" type="number" name="system.stun.max" value="{{system.health.value}}" />
Thoughts on making this input disabled?

2023-03-30 23:42 UTC, JFranklin3000 commented on templates/actor/parts/actor-stun.hbs
> +      <input class="centered-input" type="number" name="system.stun.max" value="{{system.health.value}}" />
I like it and added it.

2023-03-30 23:42 UTC, JFranklin3000 commented on templates/actor/parts/actor-common.hbs
> +    {{!-- Stun --}}
fixed

2023-03-30 23:42 UTC, JFranklin3000 commented on templates/actor/actor-npc-sheet.hbs
> +          {{!-- Health --}}
fixed

2023-03-31 00:00 UTC, JFranklin3000 commented on templates/actor/parts/actor-stun.hbs
> +      <input class="centered-input" type="number" name="system.stun.max" value="{{system.health.value}}" />
Yea that looks better.

2023-03-31 00:12 UTC, phildominguez approved these changes

2023-03-31 18:42 UTC, guswadsworth12 approved these changes
Looks and works good now man

2023-03-31 18:42 UTC, merged