Skills reconfigure
WookieeMatt/Essence20 pull request #346
Opened 2023-04-03 01:12 UTC by JFranklin3000

Moved skills to new structure so that we can support skills with multiple essences.

2023-04-04 23:37 UTC, phildominguez commented on template.json
> +            },
Any objections to making this a list of strings?

2023-04-05 00:13 UTC, JFranklin3000 commented on template.json
> +            },
I was thinking in most cases it is going to be a single essence. I went that way because it is easier for me to do this 

![image](https://user-images.githubusercontent.com/71140111/229949412-962afccb-3d98-4650-be5e-c9090e9faceb.png)

![image](https://user-images.githubusercontent.com/71140111/229949506-15bf8dec-c65d-4be8-be24-8007bb08f4db.png)

2023-04-05 00:19 UTC, phildominguez commented on template.json
> +            },
Could it just be a string? The override would just be the essence name, then. Should we allow for multiple essences?

2023-04-05 00:23 UTC, JFranklin3000 commented on template.json
> +            },
We do need to allow for multiple essences. I wouldn't see an issue with string as long as it can be multiples. 

![image](https://user-images.githubusercontent.com/71140111/229950704-0760162c-972e-4634-98a0-64f3392d6552.png)

2023-04-05 01:06 UTC, JFranklin3000 commented on template.json
> +            },
Pushed the change to plural

2023-04-05 01:16 UTC, phildominguez requested changes

2023-04-05 01:16 UTC, phildominguez commented on module/helpers/config.mjs
> +
Weird indent and extra newline

2023-04-13 00:46 UTC, phildominguez approved these changes
🏆

2023-04-13 00:49 UTC, merged