Origin item changes
WookieeMatt/Essence20 pull request #347
Opened 2023-04-03 01:37 UTC by JFranklin3000

Initial changes to Origin Sheet Layout. 

The Description and Details Tab is an experiment, but is similar to the way 5e, Pf2, etc do item sheets. 

This uses the Trait Selector for Essences and skills.

2023-04-04 01:12 UTC, phildominguez commented
> The Description and Details Tab is an experiment, but is similar to the way 5e, Pf2, etc do item sheets.

Not opposed to this idea at all, but I'd rather do it separately from this and for all items at once.

2023-04-04 01:28 UTC, phildominguez requested changes

2023-04-04 01:28 UTC, phildominguez commented on template.json
> +      "skills": [],
Not sure how we should handle the user losing these two fields. What about appending them to the description?

We could also look parsing the old fields to populate the new ones. So if it finds "speed" somewhere in the string, it will append "speed" to `essences`.

2023-04-04 01:28 UTC, phildominguez commented on template.json
> +      "essence": [],
Should this be plural? If not, it should just be a string.

2023-04-04 01:28 UTC, phildominguez commented on templates/item/item-origin-sheet.hbs
> +      <textarea rows="5" name="system.languages">{{system.languages}}</textarea>
I think languages could just use a normal text input, not a textarea

2023-04-04 01:28 UTC, phildominguez commented on templates/item/item-origin-sheet.hbs
> +            {{!-- Base Aquatic Movement --}}
Fix indent

2023-04-04 01:57 UTC, JFranklin3000 commented on templates/item/item-origin-sheet.hbs
> +          <a class="trait-selector" style="flex-grow: 0;" data-options="essence" data-target="system.origin.essence" title="{{localize 'E20.TraitSelector'}}">
Just on the 2 Trait Selectors or somewhere else?

2023-04-04 02:04 UTC, JFranklin3000 commented on templates/item/item-origin-sheet.hbs
> +          <a class="trait-selector" style="flex-grow: 0;" data-options="essence" data-target="system.origin.essence" title="{{localize 'E20.TraitSelector'}}">
Oh I see what you are saying.

2023-04-04 02:04 UTC, JFranklin3000 commented on template.json
> +      "essence": [],
yep it should be plural or at least can be one or more than one.

2023-04-04 02:06 UTC, JFranklin3000 commented on templates/item/item-origin-sheet.hbs
> +      <textarea rows="5" name="system.languages">{{system.languages}}</textarea>
changed

2023-04-04 02:06 UTC, JFranklin3000 commented on templates/item/item-origin-sheet.hbs
> +            {{!-- Base Aquatic Movement --}}
fixed

2023-04-04 02:13 UTC, JFranklin3000 commented on template.json
> +      "skills": [],
One thing we could do to fix that is have the Origin Compendiums ready to go before we release the change (I would need the change in beta before that so I can build them). The parsing is a possibility of course we are parsing to fields to one.

2023-04-19 00:11 UTC, phildominguez requested changes
Still need to look at actor-sheet and item-sheet

2023-04-19 00:11 UTC, phildominguez commented on templates/item/item-origin-sheet.hbs
> +
```suggestion
```

2023-04-19 00:11 UTC, phildominguez commented on templates/item/item-origin-sheet.hbs
> +
```suggestion
```

2023-04-19 00:11 UTC, phildominguez commented on templates/item/item-origin-sheet.hbs
> +      title="{{localize 'E20.TraitSelector'}}">
I would change the title since it's not for traits

2023-04-19 00:11 UTC, phildominguez commented on templates/item/item-origin-sheet.hbs
> +
```suggestion
```

2023-04-19 00:11 UTC, phildominguez commented on templates/item/item-origin-sheet.hbs
> +      title="{{localize 'E20.TraitSelector'}}">
Same here

2023-04-19 00:11 UTC, phildominguez commented on template.json
>          "description": ""
Alphabetize

2023-04-19 00:21 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +        console.log(originPerk);
Removed

2023-04-19 00:22 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    console.log(itemData)
Removed

2023-04-19 00:22 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +
Removed

2023-04-19 00:29 UTC, JFranklin3000 commented on templates/actor/parts/items/origin/details.hbs
> +<div>{{localize 'E20.OriginSkill'}}: {{item.system.skills}}</div>
Should the item.system.essence be localized?

2023-04-19 00:31 UTC, JFranklin3000 commented on template.json
>          "description": ""
I am going to review this one it doesn't seem quite right.

2023-04-19 01:07 UTC, phildominguez requested changes

2023-04-19 01:07 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    await this.actor.update({
```suggestion
    }

    await this.actor.update({
```

2023-04-19 01:07 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    if (selectedSkill == "initiative"){
```suggestion
    const essence = this.actor.system.originEssencesIncrease;
    const essenceValue = this.actor.system.essences[essence] - 1;
    
    let skillString = "";
    let currentShift = "";
    let newShift = "";

    let selectedSkill = this.actor.system.originSkillsIncrease;
    if (selectedSkill == "initiative"){
```

2023-04-19 01:07 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +  async _originStatUpdate (origin, essence, skills, options) {
`skills` not used

2023-04-19 01:07 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    await this.actor.update({
```suggestion
    }

    const essenceString = `system.essences.${essence}`;

    await this.actor.update({
```
`data` not used

2023-04-19 01:41 UTC, phildominguez requested changes

2023-04-19 01:41 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +
```suggestion
```

2023-04-19 01:41 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  _preparePerks(context) {
Add a comment block for this method

2023-04-19 01:41 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  async _onDrop (event) {
Add a comment block for this method

2023-04-19 01:41 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +      let originPerkIds = [];
Since this is holding Perk items, I would change this to `originPerks`, and refer to it as such everywhere

2023-04-19 01:41 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +      context.originPerkIds = originPerkIds;
```suggestion
      }

      if (!originPerkIds.length) {
        for (let pack of game.packs){
          const compendium = game.packs.get(`essence20.${pack.metadata.name}`);
          let originPerk = compendium.index.get(this.item.system.originPerkIds[0]);

          if (originPerk) {
            originPerkIds.push(originPerk);
          }
        }
      }

      context.originPerkIds = originPerkIds;
```

2023-04-19 01:41 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  }
I think this can be simplified, let's discuss on Discord first though

2023-04-19 01:41 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  async _onOriginPerkDelete(event) {
Add a comment block for this method

2023-04-19 02:14 UTC, phildominguez commented on templates/actor/parts/items/origin/details.hbs
> +<div>{{localize 'E20.OriginSkill'}}: {{item.system.skills}}</div>
So this is tricky. You'll have to iterate through `item.system.essences` and look up the strings from the config. Same for skills. We can discuss on Discord.

2023-04-19 04:19 UTC, JFranklin3000 commented on templates/item/item-origin-sheet.hbs
> +      title="{{localize 'E20.TraitSelector'}}">
Changed

2023-04-19 04:19 UTC, JFranklin3000 commented on templates/item/item-origin-sheet.hbs
> +      title="{{localize 'E20.TraitSelector'}}">
Changed

2023-04-19 04:22 UTC, JFranklin3000 commented on module/helpers/traits.mjs
> +    case "originEssenceSkills":
Changed

2023-04-19 15:12 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +      let originPerkIds = [];
My theory here is that at some point we might have to prepare Perks that aren't originPerks but yea we could rename to just originPerks.

2023-04-19 15:16 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +      let originPerkIds = [];
On second thought this is just getting originPerkIds so that does make more sense. Changed

2023-04-19 15:17 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  _preparePerks(context) {
added

2023-04-19 15:17 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  async _onDrop (event) {
added

2023-04-19 15:21 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +      let sourceItem = await fromUuid(data.uuid);
changed

2023-04-19 15:25 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +  async _originStatUpdate (origin, essence, skills, options) {
updated

2023-04-19 15:25 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +  async _originPerkCreate(origin){
updated

2023-04-19 15:26 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +function indexFromUuid(uuid) {
Updated

2023-04-19 15:27 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +    let itemEffects = {}
Yep I figured out a better way to do this without trying to copy individual pieces.

2023-04-19 15:27 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +    let itemEffects = {}
Removed

2023-04-19 15:28 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +    await this.actor.update({
Fixed

2023-04-19 15:28 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +    if (selectedSkill == "initiative"){
changed

2023-04-19 15:30 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +
removed line

2023-04-19 15:33 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +    if (selectedSkill == "initiative"){
Changed

2023-04-19 22:09 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +            ui.notifications.error(game.i18n.format("Characters can only have one Origin"));
fixed

2023-04-19 22:22 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +        title: "Select Essence Score Increase Option",
fixed

2023-04-19 22:23 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +            label: "Accept",
fixed

2023-04-19 22:23 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +        title: "Select Origin Bonus Skill",
fixed

2023-04-19 22:23 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +            label: "Accept",
fixed

2023-04-19 22:37 UTC, JFranklin3000 commented on template.json
>          "description": ""
fixed with what should actually be on the template now.

2023-04-20 01:38 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  //function to delete a Perk from an Origin Sheet
```suggestion
  async _onDrop (event) {
    const data = TextEditor.getDragEventData(event);
    const droppedItem = indexFromUuid(data.uuid);
    const parts = data.uuid.split(".");
    const targetItem = this.item;

    if (targetItem.type  == "origin") {
      if (droppedItem.type == "perk") {
        const originPerkIds = duplicate(this.item.system.originPerkIds);

        // Can't contain duplicate Origin Perks
        if (parts[0] === "Compendium") {
          if (!originPerkIds.includes(droppedItem._id)) {
           originPerkIds.push(droppedItem._id);
            await this.item.update({
              "system.originPerkIds": originPerkIds
            }).then(this.render(false));
          }
        } else {
          if (!originPerkIds.includes(droppedItem.id)) {
            originPerkIds.push(droppedItem.id);
             await this.item.update({
               "system.originPerkIds": originPerkIds
             }).then(this.render(false));
          }
        }
      }
    }
  }

  //function to delete a Perk from an Origin Sheet
```

2023-04-20 03:23 UTC, JFranklin3000 commented on templates/actor/parts/items/origin/details.hbs
> +<div>{{localize 'E20.OriginSkill'}}: {{item.system.skills}}</div>
Fixed.

2023-04-21 00:45 UTC, phildominguez requested changes

2023-04-21 00:45 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +      const item = super._onDropItem(event, data);
```suggestion
      super._onDropItem(event, data);
```
Since we're not doing anything with `item`

2023-04-21 00:45 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    selectedSkills = choices;
Sorry, I think I meant you don't need `selectedSkills`. It doesn't get used anywhere.

2023-04-21 00:47 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +      let originPerkIds = [];
Sorry, I meant `originPerkIds` should be `originPerks`. The method name change I'm cool with as well.

2023-04-21 00:53 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +      const item = super._onDropItem(event, data);
changed

2023-04-21 01:22 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +    selectedSkills = choices;
fixed

2023-04-21 01:28 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +      let originPerkIds = [];
It isn't the full Origin Perk, I think I went with the Id name. 

![image](https://user-images.githubusercontent.com/71140111/233519340-34dd73cf-226d-4213-bb4b-fa1322dc2017.png)

2023-04-23 03:38 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    let selectedSkills = "";
```suggestion
```
Not used

2023-04-23 04:11 UTC, phildominguez requested changes

2023-04-23 04:11 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +      } else {
```suggestion
      if (selectedSkill) {
```

2023-04-23 04:11 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +        await this.actor.update({
```suggestion
        }

        super._onDropItem(event, data);

        await this.actor.update({
```

2023-04-24 15:15 UTC, phildominguez approved these changes

2023-04-24 15:19 UTC, merged