Move actor templates
WookieeMatt/Essence20 pull request #383
Opened 2023-04-16 18:40 UTC by phildominguez

Closes https://github.com/WookieeMatt/Essence20/issues/381

In this PR:
- Moving a bunch of misc actor parts templates into `parts/misc/`
- Removing `actor-` from the start of the file names since they're already in `/actor`
- Removing `-header` from header files since they're already in `/headers`
- Renaming `headers/actor-header.hbs` to `headers/common.hbs`

Testing: All actor sheets should still look normal

2023-04-17 01:18 UTC, guswadsworth12 submitted a review, later dismissed
Looks great. Works as expected.

2023-04-17 01:20 UTC, guswadsworth12 requested changes
Resolve conflicts please.

2023-04-18 14:45 UTC, JFranklin3000 approved these changes

2023-04-27 22:06 UTC, JFranklin3000 approved these changes

2023-04-27 23:02 UTC, guswadsworth12 approved these changes

2023-04-27 23:03 UTC, merged