Upgrades
WookieeMatt/Essence20 pull request #398
Opened 2023-04-27 02:36 UTC by JFranklin3000

2023-04-27 23:55 UTC, phildominguez requested changes

2023-04-27 23:55 UTC, phildominguez commented on module/helpers/config.mjs
> +};
```suggestion
// Upgrade types
E20.upgradeType = {
  armor: "E20.UpgradeArmor",
  drone: "E20.UpgradeDrone",
  weapon: "E20.UpgradeWeapon",
};
```

2023-04-27 23:55 UTC, phildominguez commented on lang/en.json
> +    "Upgrades": "Upgrades",
```suggestion
    "Upgrade": "Upgrade",
    "UpgradeAvailability": "Availability",
    "UpgradeBenefit": "Benefit",
    "UpgradePlural": "Upgrades",
    "UpgradePrerequisite": "Prerequisite",
    "UpgradeTypeArmor": "Armor",
    "UpgradeTypeDrone": "Drone",
    "UpgradeTypeWeapon": "Weapon",
    "UpgradeType": "Type",
```
Having "Blah Upgrade" for all the types seems redundant to me. I changed `Upgrades` to `UpgradePlural` as well.

2023-04-27 23:55 UTC, phildominguez commented on lang/en.json
> +    "ItemTypeUpgradeWeaponPlural": "Weapon Upgrades",
Idt it's being used

2023-04-28 00:01 UTC, JFranklin3000 commented on lang/en.json
> +    "ItemTypeUpgradeWeaponPlural": "Weapon Upgrades",
removed

2023-04-28 00:20 UTC, phildominguez approved these changes

2023-04-28 00:20 UTC, merged