Upgrade traits and Armor bonus
WookieeMatt/Essence20 pull request #408
Opened 2023-04-29 17:47 UTC by JFranklin3000

Add ability for upgrades to add Traits and Armor Bonuses to Armor and Weapons. 

Create Armor Upgrade with a Trait and Armor bonus of Evasion or toughness (Cleverness and Willpower are there temporarily)
Validate adding that to armor adds both and deleting removes both. 

Need to consolidate some code to functions as well.

2023-04-30 23:08 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  async _addIfUnique (parts, Ids, droppedItem, itemType) {
```suggestion
  /**
  * <The current desc is pasted from somewhere else>
  * @param {Array} uuidParts          The parts of the UUID
  * @param {Array} ids                    ID of the item being dropped
  * @param {Item} droppedItem     The item that was dropped
  * @param {String} itemType         A string defining what the item is
  * @private
  */
  async _addIfUnique (parts, id, droppedItem, itemType) {
```
The description for `ids` seems off. How does an item have a list of IDs?

2023-04-30 23:09 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  async _addIfUnique (parts, Ids, droppedItem, itemType) {
The spacing is really messed up, but the descriptions for each variable should line up with one another

2023-04-30 23:14 UTC, phildominguez requested changes

2023-04-30 23:14 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  async _addDroppedItemTraits (droppedItem, targetItem) {
```suggestion
  /**
  * Handle adding Traits to Items that have Upgrades
  * @param {Item} droppedItem     The Item that was dropped
  * @private
  */
  async _addDroppedItemTraits (droppedItem) {
```
`targetItem` is just `this.item` so it doesn't need to be passed around

2023-04-30 23:31 UTC, phildominguez requested changes

2023-04-30 23:31 UTC, phildominguez commented on module/sheets/item-sheet.mjs
>      if (targetItem.type  == "origin") {
You could do a `switch` on `targetItem.type` and have cases for origin, armor, and weapon

2023-04-30 23:31 UTC, phildominguez commented on module/sheets/item-sheet.mjs
>      const parts = data.uuid.split(".");
I think `parts` is too vague for me, I would make it `uuidParts`

2023-04-30 23:31 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +        this._addIfUnique (parts, originPerkIds, droppedItem, "originPerk");
```suggestion
        this._addIfUnique(parts, originPerkIds, droppedItem, "originPerk");
```

2023-04-30 23:31 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +          }
Having this in here and the weapon section is enough for me to recommend pulling it into a separate method

2023-04-30 23:31 UTC, phildominguez commented on module/sheets/item-sheet.mjs
>          if (droppedItem.system.type == "armor") {
```suggestion
        } else if (droppedItem.system.type == "armor") {
```

2023-04-30 23:31 UTC, phildominguez commented on module/sheets/item-sheet.mjs
>          if (droppedItem.system.type == "weapon") {
```suggestion
        } else if (droppedItem.system.type == "weapon") {
```

2023-05-01 00:49 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  async _addIfUnique (parts, Ids, droppedItem, itemType) {
It is an array of ids from the item to validate that the dropped items Id isn't already in the array.

2023-05-01 00:50 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  async _addDroppedItemTraits (droppedItem, targetItem) {
changed.

2023-05-01 00:53 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
>      if (targetItem.type  == "origin") {
definitely on my radar to move to a switch if we get many more items that can be dropped.

2023-05-01 00:53 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
>      const parts = data.uuid.split(".");
updated

2023-05-01 00:55 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
>          if (droppedItem.system.type == "armor") {
Nope this is a standalone if. The one before it is only if the item is in a compendium.

2023-05-01 00:55 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
>          if (droppedItem.system.type == "weapon") {
Same as the last one this is a standalone if.

2023-05-01 01:17 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +          }
Moved to function.

2023-05-01 12:57 UTC, phildominguez commented
![image](https://user-images.githubusercontent.com/41161497/235454340-8da3c806-6005-4a39-bed5-bf5a3df1d1bc.png)
Github won't let me comment on it directly, but I think this should go in `module\helpers\utils.mjs`. The description seems to be pasted from elsewhere, and I would mention it returns null if not found.

2023-05-01 14:28 UTC, phildominguez requested changes

2023-05-01 14:28 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  async _addIfUnique (uuidParts, Ids, droppedItem, itemType) {
```suggestion
  * Handles validating an item being dropped is unique
  * @param {Item} droppedItem The item that was dropped
  * @param {String} itemType  A string defining what the item is
  * @param {Array} existingIds  The Ids of existing items attached to the target item
  * @private
  */
  async _addIfUnique(droppedItem, itemType, existingIds) {
```
- It looks like uuidParts is only being used in this method. I think we should generate it here instead of passing it as a param.
- I changed `Ids` to `existingIds` to make it more specific. Also, capitalized stuff is usually reserved for class names, so best to keep the first letter lowercase.
- I put `existingIds` as the last param, because having the item being dropped first seems more natural to me

2023-05-01 14:28 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +    if (droppedItem.system.traits.length > 0) {
```suggestion
    if (!droppedItem.system.traits.length) {
      return;
    }
```
Short circuiting is a nice way to avoid large if blocks

2023-05-01 14:28 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +      let traits = this.item.system.traits;
```suggestion
      let itemTraits = this.item.system.traits;
```
To help avoid confusion

2023-05-01 14:28 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  async _addDroppedItemTraits (droppedItem) {
```suggestion
  /**
  * Handle adding Traits to Items from a dropped Upgrade
  * @param {Upgrade} upgrade  The upgradethat was dropped
  * @private
  */
  async _addDroppedUpradeTraits(upgrade) {
```
If we know this is an Upgrade, I think make it as specific as possible

2023-05-01 14:28 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +      for (let trait of droppedItem.system.traits) {
```suggestion
      for (const upgradeTrait of upgrade.system.traits) {
```

2023-05-01 14:28 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +      let upgradeTraits = this.item.system.upgradeTraits;
```suggestion
      const existingUpgradeTraits = this.item.system.upgradeTraits;
```

2023-05-01 14:28 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +        }
```suggestion
        if (!itemTraits.includes(trait) && !existingUpgradeTraits.includes(trait) {
          upgradeTraits.push(trait);
        }
```

2023-05-01 19:32 UTC, phildominguez requested changes

2023-05-01 19:32 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +
```suggestion
```

2023-05-01 19:32 UTC, phildominguez commented on templates/item/sheets/upgrade.hbs
> +      </select>
I think this indenting is off. Also, strings from config don't need to be localized since they're prelocalized now.

2023-05-02 00:18 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  async _searchCompendium (droppedItem) {
fixed

2023-05-02 00:22 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  async _addIfUnique (uuidParts, Ids, droppedItem, itemType) {
Updated

2023-05-02 00:24 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    if (droppedItem.system.traits.length > 0) {
So everything else goes in the else?

2023-05-02 00:25 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +      let traits = this.item.system.traits;
updated to itemTrait

2023-05-02 01:13 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  async _addDroppedItemTraits (droppedItem) {
Changed

2023-05-02 01:15 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +      for (let trait of droppedItem.system.traits) {
We don't have upgrade here that is in the function now only.

2023-05-02 01:16 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +      for (let trait of droppedItem.system.traits) {
Nevermind that whole section shouldn't be there it moved to the function.

2023-05-02 01:18 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +      for (let trait of droppedItem.system.traits) {
Fixed

2023-05-02 01:43 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  * Handle deleting of an Upgrade from a Weapon or Armor Sheet
Fixed, and not in here Drones would be in the actor-sheet.mjs

2023-05-02 01:47 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    if (data.system.traits.length > 0) {
fixed

2023-05-02 01:47 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +          if(keptTraits.includes(itemTrait)) {
fixed

2023-05-02 01:47 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +              }else {
fixed I couldn't for the life of me get this one right.

2023-05-02 01:47 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +          if (otherItemTrait == false) {
fixed

2023-05-02 01:47 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +
fixed

2023-05-02 01:49 UTC, JFranklin3000 commented on templates/item/sheets/upgrade.hbs
> +      </select>
fixed

2023-05-02 02:01 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +        }
implemented and that made it a lot cleaner.

2023-05-02 02:01 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +      let upgradeTraits = this.item.system.upgradeTraits;
If I do that I can't push the new traits to the existing traits and then write them all back.

2023-05-02 02:02 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +      for (let trait of droppedItem.system.traits) {
I rolled this one back as it was overlapping the other upgradeTraits.

2023-05-02 23:15 UTC, phildominguez requested changes

2023-05-02 23:15 UTC, phildominguez commented on module/helpers/utils.mjs
> +  else if ( parts.length < 3 ) {
```suggestion
  if (parts[0] === "Compendium") {
    const [, scope, packName, id] = parts;
    const pack = game.packs.get(`${scope}.${packName}`);
    index = pack?.index.get(id);
  }

  // World Documents
  else if (parts.length < 3) {
```
Just keeping the styling consistent with our codebase

2023-05-02 23:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +    if(!droppedItem.system) {
```suggestion
    const targetItem = this.item;

    let droppedItem = indexFromUuid(data.uuid);
    if(!droppedItem.system) {
```
Put them next to each other since they're directly related

2023-05-02 23:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +
```suggestion
```

2023-05-02 23:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +
```suggestion
```
Method calls can generally be cuddled

2023-05-02 23:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +
```suggestion
```

2023-05-02 23:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +
```suggestion
```

2023-05-02 23:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +
```suggestion
```

2023-05-02 23:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +          if (droppedItem.system.armorBonus.value >0) {
```suggestion
          if (droppedItem.system.armorBonus.value > 0) {
```

2023-05-02 23:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
```suggestion
```

2023-05-02 23:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
>    //
```suggestion
```

2023-05-02 23:18 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +  else if ( parts.length < 3 ) {
updated.

2023-05-02 23:18 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    if(!droppedItem.system) {
updated

2023-05-02 23:20 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +
fixed

2023-05-02 23:20 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +
fixed

2023-05-02 23:20 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +
fixed

2023-05-02 23:21 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +
fixed

2023-05-02 23:21 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +
fixed

2023-05-02 23:21 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +          if (droppedItem.system.armorBonus.value >0) {
fixed

2023-05-02 23:22 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
fixed

2023-05-02 23:22 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
>    //
fixed

2023-05-02 23:38 UTC, phildominguez requested changes

2023-05-02 23:38 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +          this._addIfUnique (data, upgradeIds, droppedItem, "upgrade");
```suggestion
          this._addIfUnique(data, upgradeIds, droppedItem, "upgrade");
```

2023-05-02 23:38 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +          this._addDroppedUpgradeTraits (droppedItem, targetItem);
```suggestion
          this._addDroppedUpgradeTraits(droppedItem);
```
targetItem is no longer a param

2023-05-02 23:38 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +          this._addDroppedUpgradeTraits (droppedItem, targetItem);
```suggestion
          this._addDroppedUpgradeTraits(droppedItem);
```
targetItem is no longer a param

2023-05-02 23:38 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +    if (uuidParts[0] === "Compendium") {
```suggestion
    const uuidParts = data.uuid.split(".");
    const idString = `system.${itemType}Ids`;

    if (uuidParts[0] === "Compendium") {
```
No cuddling multiple variable declarations with `if`s

2023-05-02 23:38 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  async _addIfUnique(data, existingIds, droppedItem, itemType) {
```suggestion
  /**
  * Handles validating an item being dropped is unique
  * @param {Object} data The data from drop event
  * @param {Item} droppedItem The item that was dropped
  * @param {String} itemType  A string defining what the item is
  * @param {Array} existingIds  The Ids of existing items attached to the target item
  * @private
  */
  async _addIfUnique(data, existingIds, droppedItem, itemType) {
```
- Is `itemType` needed as a param? Can't we just do droppedItem.type?
- I would make droppeditem the first param since it's the most "important"
- Order of params in the comment block should match the param list
- I'm thinking we should change the name to `_addItemIfUnique`, otherwise it's a bit vague

2023-05-02 23:38 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +      await this.item.update({
```suggestion
      }

      await this.item.update({
```
No cuddling stuff after `for`s

2023-05-02 23:38 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  async _searchCompendium(droppedItem) {
- Needs a comment block
- This method doesn't really care where the item is from, I would just called the param `item`

2023-05-02 23:38 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +    for (let pack of game.packs){
```suggestion
    let id = droppedItem._id || droppedItem;

    for (let pack of game.packs){
```

2023-05-02 23:38 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +        let droppedUpgrade = await compendium.getDocument(id);
This method isn't "aware" of anything being dropped or an upgrade

2023-05-02 23:38 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +    return droppedItem
```suggestion
    }

    return droppedItem
```

2023-05-02 23:43 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +          this._addIfUnique (data, upgradeIds, droppedItem, "upgrade");
changed

2023-05-02 23:43 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +          this._addDroppedUpgradeTraits (droppedItem, targetItem);
changed

2023-05-02 23:44 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    if (uuidParts[0] === "Compendium") {
fixed

2023-05-02 23:52 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  async _addIfUnique(data, existingIds, droppedItem, itemType) {
ItemType is needed because of the originPerk that one doesn't work as droppedItem.type

Otherwise fixed.

2023-05-02 23:57 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  async _searchCompendium(droppedItem) {
changed

2023-05-03 01:15 UTC, phildominguez requested changes

2023-05-03 01:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +    let data = game.items.get(upgradeId);
I'm finding myself getting mixed up between what relates to `this.item` and what relates to the upgrade. I think prepending more stuff with `upgrade______` will help, like making this `upgradeData`.

2023-05-03 01:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +      for (let itemTrait of data.system.traits) {
Related to the other convo, I would make this `upgradeTrait`

2023-05-03 01:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +              }
Don't we have `_searchCompendium` do do this now?

2023-05-03 01:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +      await this.item.update({
```suggestion
        }

        if (!isOtherItemTrait) {
          keptTraits = keptTraits.filter(x => x !== itemTrait);
        }
      }

      await this.item.update({
```
Generally don't cuddle stuff below `{ ... }` blocks

2023-05-03 01:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +                isOtherItemTrait = true
Once we hit this, we can `break` to stop searching and exit the loop

2023-05-03 01:15 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +              if(!otherItem) {
```suggestion
              const otherItem = game.items.get(id);
              if (!otherItem) {
```

2023-05-03 01:31 UTC, phildominguez requested changes

2023-05-03 01:31 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +    let droppedItem = indexFromUuid(data.uuid);
```suggestion
    const droppedItem = indexFromUuid(data.uuid);
```
Sorry I missed this one

2023-05-03 03:24 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    if (data.system.traits.length > 0) {
Updated

2023-05-03 03:28 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  */
fixed

2023-05-03 03:28 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    for (let pack of game.packs){
fixed

2023-05-03 03:34 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +      await this.item.update({
updated

2023-05-03 03:39 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +              }
fixed

2023-05-03 04:04 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    let data = game.items.get(upgradeId);
renamed data deletedItem so we know it is the item being deleted.

2023-05-03 04:04 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +      for (let itemTrait of data.system.traits) {
renamed deletedItemTrait

2023-05-03 21:39 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +              if(!otherItem) {
fixed

2023-05-03 21:39 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    let droppedItem = indexFromUuid(data.uuid);
fixed

2023-05-03 21:41 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +                isOtherItemTrait = true
so just add a break after we set it true and that breaks out of the inner for loop right?

2023-05-03 21:42 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +                isOtherItemTrait = true
updated and it is working as expected.

2023-05-04 00:05 UTC, phildominguez requested changes

2023-05-04 00:05 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +      for (let deletedItemTrait of deletedItem.system.traits) {
```suggestion
      for (const deletedItemTrait of deletedItem.system.traits) {
```

2023-05-04 00:05 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +    for (let pack of game.packs){
```suggestion
    for (const pack of game.packs){
```

2023-05-04 01:21 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +        let droppedUpgrade = await compendium.getDocument(id);
changed

2023-05-04 01:23 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    console.log(droppedItem.type)
removed

2023-05-04 01:25 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +      for (let trait of upgrade.system.traits) {
changed.

2023-05-04 01:28 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    if(!droppedItem.system) {
Changed

2023-05-04 01:29 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +      for (let deletedItemTrait of deletedItem.system.traits) {
fixed

2023-05-04 01:29 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    for (let pack of game.packs){
fixed

2023-05-04 01:30 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +          }
fixed

2023-05-04 01:31 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    const deletedItem = game.items.get(upgradeId) || await this._searchCompendium(upgradeId);
That works.

2023-05-04 15:43 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +      for (let trait of upgrade.system.traits) {
Doesn't look like the names were changed, if you agree with them

2023-05-04 15:45 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +      for (let trait of upgrade.system.traits) {
`const` as well

2023-05-04 15:50 UTC, phildominguez requested changes

2023-05-04 22:17 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +      for (let droppedTrait of upgrade.system.traits) {
```suggestion
      for (const droppedTrait of upgrade.system.traits) {
```

2023-05-04 22:17 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +        let compendiumItem = await compendium.getDocument(id);
```suggestion
        const compendiumItem = await compendium.getDocument(id);
```

2023-05-04 22:26 UTC, phildominguez approved these changes

2023-05-04 22:27 UTC, merged