Auto Setting Movement
WookieeMatt/Essence20 pull request #416
Opened 2023-05-05 22:27 UTC by JFranklin3000

Closes nothing

##### In this PR
clearly defined all types of movement and bonuses
        "movement": {
          "aerial": {
            "altmode":0,
            "base": 0,
            "bonus": 0,
            "morphed": 0,
            "total": 0
          },
          "ground": {
            "altmode":0,
            "base": 0,
            "bonus": 0,
            "morphed": 0,
            "total": 0
          },
          "swim": {
            "altmode":0,
            "base": 0,
            "bonus": 0,
            "morphed": 0,
            "total": 0
          }

also added isMorphed and isTransformed for future buttons. 
- 

##### Testing

create characters of all types verify adding an origin sets the right base values. 
Add AEs that update movement, either base or bonus (if base is 0 then that movement will show as 0)
Validate NPCs still have to have their movement set manually.

2023-05-06 23:33 UTC, phildominguez requested changes

2023-05-06 23:33 UTC, phildominguez commented on templates/actor/parts/misc/movement.hbs
> +    {{/if}}
I'm not positive but there might be a clean way to do this with https://guides.emberjs.com/release/components/built-in-components/. Instead of doing the `inArray` here, we could create a new field called `movementIsReadOnly` in `getData()`, and just use that here. Can discuss on DC.

2023-05-06 23:33 UTC, phildominguez commented on template.json
> +            "altmode":0,
I think we do `altMode` everywhere

2023-05-06 23:33 UTC, phildominguez commented on module/essence20.mjs
> +});
Oh this is neat

2023-05-06 23:33 UTC, phildominguez commented on module/documents/actor.mjs
> +    }
- Are float movement values a thing? Should we use `parseInt`?
- I would calculate all the values being parsed before this `if` block so that it's easier to read and aren't duplicating calls
- Are all 3 of these big `if` blocks the same? Can it be a helper method?

2023-05-07 00:47 UTC, JFranklin3000 commented on template.json
> +            "altmode":0,
yep it is the base movement for the alt modes so aerial.altmode would be the base aerial speed well in an altmode.

2023-05-07 00:48 UTC, JFranklin3000 commented on module/essence20.mjs
> +});
I know right.

2023-05-07 00:51 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +    }
The base movements from the Origins come in as floats that the whole reason it is there. 
So parseFloat before the ifs?
They should be the same for all 4 types (PR, TF, GI Joe and Pony). I am all for that should we do the same with the defense for all of them as well?

2023-05-07 02:23 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +    }
Would this be called as a separate function in the same file or in a different file?

2023-05-07 17:05 UTC, phildominguez commented on module/documents/actor.mjs
> +    }
> The base movements from the Origins come in as floats
Like from the Origin item sheet? I'm just curious where it's indicating it's a float.

> So parseFloat before the ifs?
I would do all the parseFloats before the first `if` on 142

> Would this be called as a separate function in the same file or in a different file?
Same file is fine

> Should we do the same with the defense for all of them as well?
If it's not part of this change we can save that for later

2023-05-07 17:05 UTC, phildominguez commented on template.json
> +            "altmode":0,
Sorry, I was talking about the capitalization of `M`

2023-05-07 18:48 UTC, JFranklin3000 commented on template.json
> +            "altmode":0,
Pushed fix for this.

2023-05-07 18:58 UTC, JFranklin3000 commented on templates/actor/parts/misc/movement.hbs
> +    {{/if}}
So movementIsReadOnly in the template?

2023-05-07 19:15 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +    }
yep from the Origin Item sheet it is coming as a float. I moved the movement to a separate function.

2023-05-08 21:46 UTC, phildominguez requested changes

2023-05-08 21:46 UTC, phildominguez commented on module/documents/actor.mjs
> +  }
```suggestion
  _prepareMovement(system) {
    system.movementIsReadOnly = true;
    system.movement.aerial.base = parseInt(system.movement.aerial.base);
    system.movement.ground.base = parseInt(system.movement.ground.base);
    system.movement.swim.base = parseInt(system.movement.swim.base);

    system.movement.aerial.total = system.movement.aerial.bonus;
    system.movement.ground.total = system.movement.ground.bonus;
    system.movement.swim.total = system.movement.swim.bonus;

    if (system.isMorphed) {
      if (system.movement.aerial.base) {
        system.movement.aerial.total += system.movement.aerial.base + system.movement.aerial.morphed;
      }
      if (system.movement.ground.base) {
        system.movement.ground.total += system.movement.ground.base + system.movement.ground.morphed;
      }
      if (system.movement.swim.base) {
        system.movement.swim.total += system.movement.swim.base + system.movement.swim.morphed;
      }
    }

    if (system.isTransformed) {
      if (system.movement.aerial.altMode) {
        system.movement.aerial.total += system.movement.aerial.altMode;
      }
      if (system.movement.ground.altMode) {
        system.movement.ground.total += system.movement.ground.altMode;
      }
      if (system.movement.swim.altMode) {
        system.movement.swim.total += system.movement.swim.altMode;
      }
    }

    if (!system.isTransformed && !system.isMorphed) {
      if (system.movement.aerial.base) {
        system.movement.aerial.total += system.movement.aerial.base;
      }
      if (system.movement.ground.base) {
        system.movement.ground.total += system.movement.ground.base;
      }
      if (system.movement.swim.base) {
        system.movement.swim.total += system.movement.swim.base;
      }
    }
  }
```
Simplified it, lmk if it doesn't work

2023-05-08 21:46 UTC, phildominguez commented on module/documents/actor.mjs
> +
```suggestion
```

2023-05-08 21:46 UTC, phildominguez commented on templates/actor/parts/misc/movement.hbs
> +    {{/if}}
I think you can use handlebars's [built-in Input](https://guides.emberjs.com/release/components/built-in-components/#:~:text=%3CInput%0A%20%20id%3D%22input%2Dname%22%0A%20%20%40value%3D%7B%7Bthis.name%7D%7D%0A%20%20disabled%3D%7B%7Bthis.isReadOnly%7D%7D%0A%20%20maxlength%3D%2250%22%0A/%3E) instead of doing an if/else

2023-05-08 21:46 UTC, phildominguez commented on module/documents/actor.mjs
> +  _prepareMovement(system) {
I would put this after all the `_prepare<Actor>Data()` definitions instead of before them (so after `_preparePonyData()`)

2023-05-08 22:28 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +  }
pushed a version of your simplification.

2023-05-08 22:29 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +
fixed

2023-05-08 23:26 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +  _prepareMovement(system) {
Moved

2023-05-08 23:30 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +  _prepareMovement(system) {
Moved

2023-05-08 23:30 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +
removed

2023-05-08 23:31 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +  }
Made a modified version of this.

2023-05-08 23:42 UTC, JFranklin3000 commented on templates/actor/parts/misc/movement.hbs
> +    {{/if}}
everything I have tried either doesn't set the actor movement to readonly or doesn't leave the NPC movement unlocked.  So I stayed with what was working.

2023-05-08 23:56 UTC, JFranklin3000 commented on templates/actor/parts/misc/movement.hbs
> +    {{/if}}
or it gets just as complicated as the if else.

2023-05-09 23:17 UTC, phildominguez requested changes

2023-05-09 23:21 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +    }
yep that makes sense. Pushing those changes.

2023-05-10 00:12 UTC, phildominguez commented on templates/actor/parts/misc/movement.hbs
> +      <input class="centered-input" type="text" name="system.movement.aerial.total" value="{{system.movement.aerial.total}}" {{system.movementIsReadOnly}} />
```suggestion
      <input class="centered-input" type="number" name="system.movement.aerial.total" value="{{system.movement.aerial.total}}" {{system.movementIsReadOnly}} />
```

2023-05-10 00:15 UTC, phildominguez commented on module/migration.mjs
> +      }
Do we `break` after an origin is found?

2023-05-10 00:16 UTC, JFranklin3000 commented on module/migration.mjs
> +      }
We could, but we should only have one. but we could break.

2023-05-11 01:38 UTC, JFranklin3000 commented on module/migration.mjs
> +      }
I added the break.

2023-05-11 16:51 UTC, phildominguez requested changes

2023-05-11 16:51 UTC, phildominguez commented on module/migration.mjs
> +        break
```suggestion
        break;
```

2023-05-11 16:51 UTC, phildominguez commented on module/documents/actor.mjs
> +    this._prepareMovement(system);
```suggestion
    this._prepareMovement();
```

2023-05-11 23:20 UTC, phildominguez submitted a review, later dismissed

2023-05-11 23:24 UTC, phildominguez approved these changes

2023-05-11 23:25 UTC, merged