Morph button
WookieeMatt/Essence20 pull request #423
Opened 2023-05-14 23:45 UTC by JFranklin3000

Closes [https://github.com/WookieeMatt/Essence20/issues/326]

##### In this PR
- Added Morph Button
- Added function to set isMorphed
- Restructured defenses in template
- redid the defenses partial and removed the PR specific one

##### Testing
- Create Power Ranger and validate movement and defense changes for Morphing
- Create other characters and validate Defenses are calculated right.
- This will require a migration yet.

2023-05-16 01:36 UTC, phildominguez commented on module/documents/actor.mjs
> +      const defenseName = system.defenses[defenseType];
`Name` to me implies that it's just a string. I would just call this `defense`.

2023-05-16 01:40 UTC, phildominguez commented on module/documents/actor.mjs
> +      if (system.isMorphed) {
```suggestion
      const morphedName = game.i18n.localize('E20.DefenseMorphed');

      if (system.isMorphed) {
```

2023-05-16 01:43 UTC, phildominguez commented on module/documents/actor.mjs
> +        defenseName.string = `${defenseName.base} ${baseName} + ${system.essences[defenseName.essence]} ${essenceName} + ${defenseName.armor} ${armorName} + ${defenseName.bonus} ${bonusName}`
To make this as easy to read as possible, I would make consts for basically all of these. Such as:
```
const base = defense.base;
const essence = system.essences[defenseName.essence];
```

2023-05-16 01:49 UTC, phildominguez commented on module/documents/actor.mjs
>    _preparePonyData() {
Since all 4 of these look the same, we could probably just do an `if` in `prepareDerivedData()` and call `_prepareDefenses()` and `_prepareMovement()` if it's one of the correct types. And delete these four identical methods.

2023-05-16 02:15 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +      const defenseName = system.defenses[defenseType];
Changed

2023-05-16 02:23 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +        defenseName.string = `${defenseName.base} ${baseName} + ${system.essences[defenseName.essence]} ${essenceName} + ${defenseName.armor} ${armorName} + ${defenseName.bonus} ${bonusName}`
changed

2023-05-16 03:16 UTC, JFranklin3000 commented on module/documents/actor.mjs
>    _preparePonyData() {
Changed

2023-05-16 17:57 UTC, phildominguez requested changes

2023-05-16 17:57 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +  }
```suggestion
  async _morph() {
    await this.actor.update({
      "system.isMorphed": !this.actor.system.isMorphed,
    }).then(this.render(false));
  }
```
Comment block as well

2023-05-16 20:43 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +  }
changed

2023-05-20 17:16 UTC, phildominguez requested changes

2023-05-20 23:49 UTC, JFranklin3000 commented on templates/actor/parts/misc/defenses.hbs
> +            </span>
fixed

2023-05-20 23:49 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +        defense.string = `${base} ${baseName} + ${essence} ${essenceName} + ${armor} ${armorName} + ${bonus} ${bonusName}`
fixed

2023-05-20 23:49 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +  _prepareDefenses() {
fixed

2023-05-21 01:42 UTC, phildominguez approved these changes

2023-05-21 01:43 UTC, merged