Crossover Options
WookieeMatt/Essence20 pull request #429
Opened 2023-05-26 14:55 UTC by JFranklin3000

Closes [(https://github.com/WookieeMatt/Essence20/issues/354)]

##### In this PR
- Added Crossover Options button to character actor sheets
- Added Dialog to select can Transform and can Morph

##### Testing
- Create actors of different types and add and remove Morph and Transform options.

2023-05-30 17:16 UTC, guswadsworth12 approved these changes
Tested and works as intended

2023-05-30 19:25 UTC, phildominguez requested changes

2023-05-30 19:25 UTC, phildominguez commented on module/documents/actor.mjs
> +    }
```suggestion

this.system.canMorph = this.type == 'powerRanger';
this.system.canTransform = this.type == 'transformer';
```

2023-05-30 19:25 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +
Indent and remove extra newlines

2023-05-30 19:25 UTC, phildominguez commented on templates/actor/sheets/giJoe.hbs
> +      {{/if}}
Template :)

2023-05-30 19:25 UTC, phildominguez commented on templates/dialog/crossover-options.hbs
> +
```suggestion

```

2023-05-30 19:27 UTC, phildominguez requested changes

2023-05-30 19:27 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +_crossoverSettings(options) {
Comment block

2023-05-30 19:27 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +async _onConfigureEntity(event) {
Comment block

2023-05-30 19:27 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    return buttons;
```suggestion
    }

    return buttons;
```

2023-05-30 19:27 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +        }
```suggestion
        system: this.actor.system,
      }),
      buttons: {
        save: {
          label: game.i18n.localize('E20.AcceptButton'),
          callback: html => this._crossoverSettings(this._rememberOptions(html)),
        },
```

2023-05-30 23:29 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +    }
I didn't know you could do that.

2023-05-30 23:41 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +_crossoverSettings(options) {
fixed

2023-05-30 23:41 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +
fixed

2023-05-30 23:42 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +async _onConfigureEntity(event) {
fixed

2023-05-30 23:46 UTC, JFranklin3000 commented on templates/actor/sheets/giJoe.hbs
> +      {{/if}}
by Template I assume you mean separate .hbs?

2023-05-31 01:16 UTC, phildominguez commented on templates/actor/sheets/giJoe.hbs
> +      {{/if}}
Yep

2023-05-31 01:18 UTC, phildominguez requested changes

2023-05-31 01:18 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +          }
```suggestion
          system: this.actor.system,
        }),
        buttons: {
          save: {
            label: game.i18n.localize('E20.AcceptButton'),
            callback: html => this._crossoverSettings(this._rememberOptions(html)),
          },
```

2023-05-31 01:18 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +          [updateString]: false
```suggestion
      const updateString = `system.${option}`;
      if (options[option]) {
        this.actor.update({
          [updateString]: true,
        }).then(this.render(false));
      } else {
        this.actor.update({
          [updateString]: false,
```

2023-05-31 01:18 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +   * @param {HTML} html   The html of the dialog upon submission
The param is options, not html

2023-05-31 01:19 UTC, phildominguez requested changes

2023-05-31 01:19 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    // Make all the Essence20 consts accessibleonIdDe
accessibleonIdDe?

2023-05-31 01:20 UTC, phildominguez requested changes

2023-05-31 01:20 UTC, phildominguez commented on module/documents/actor.mjs
> +this.system.canTransform = this.type == 'transformer';
Indent

2023-06-01 22:15 UTC, JFranklin3000 commented on templates/actor/sheets/giJoe.hbs
> +      {{/if}}
fixed

2023-06-01 22:36 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +    }
I reverted this because for some reason what you proposed stopped the crossover dialog from working.

2023-06-01 22:36 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +this.system.canTransform = this.type == 'transformer';
had to remove and fixed the indent.

2023-06-01 22:38 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +    // Make all the Essence20 consts accessibleonIdDe
Yea no idea. I assume I started typing something well on that line and didn't notice.

2023-06-02 02:24 UTC, phildominguez requested changes

2023-06-02 02:24 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    console.log(options)
```suggestion
```

2023-06-02 03:23 UTC, phildominguez approved these changes

2023-06-02 03:35 UTC, merged