Gear and Combat Tab Styling
WookieeMatt/Essence20 pull request #46
Opened 2022-04-21 21:56 UTC by WookieeMatt

2022-04-21 22:45 UTC, phildominguez requested changes
- Suggested a fix for the edit/delete bug
- I'm seeing double scrollbars on the sheet, any idea how to get rid of that?

2022-04-21 22:45 UTC, phildominguez commented on templates/actor/parts/actor-weapons.hbs
> +    <li class="items flexrow" data-item-id="{{weapon._id}}" style="margin-left: 20px;">
```suggestion
  <ol class="items-list">
    {{#each @root.weapons as |weapon|}}
    <li class="item flexrow" data-item-id="{{weapon._id}}" style="margin-left: 20px;">
```

2022-04-21 22:45 UTC, phildominguez commented on templates/actor/parts/actor-gear.hbs
> +    <li class="items flexrow" data-item-id="{{gear._id}}" style="margin-left: 20px;">
```suggestion
  <ol class="items-list">
    {{#each @root.gears as |gear|}}
    <li class="item flexrow" data-item-id="{{gear._id}}" style="margin-left: 20px;">
```
Editing/deleting broke because an s was added to `item`. I think the `ol` should be outside the `each` as well.

2022-04-21 23:37 UTC, phildominguez commented
Btw the canted angle is an interesting idea, is it inspired by comic styling?

2022-04-21 23:40 UTC, WookieeMatt commented
Yes it is comic inspired. And I have an idea for the scroll bar

2022-04-22 15:46 UTC, phildominguez approved these changes

2022-04-22 15:47 UTC, merged