Automatically calculate PC health
WookieeMatt/Essence20 pull request #470
Opened 2023-06-21 21:29 UTC by JFranklin3000

##### In this PR
-  created prepareHealth in actor.mjs
- created steps to calculate health based on origin, condtioning and bonuses. 

##### Testing
- Validate health is being calculated correctly 
- Validate NPC are not effected.

2023-06-22 00:59 UTC, phildominguez requested changes
Seeing this when I delete my origin:
![image](https://github.com/WookieeMatt/Essence20/assets/41161497/f115b3e6-7e4b-453f-8579-da2e7a6d70d8)

2023-06-22 00:59 UTC, phildominguez commented on lang/en.json
> +    "HealthBonus": "Bonus",
Do we want to just make a single `"Bonus"` field? `"DefenseBonus"` is also just "Bonus".

2023-06-22 00:59 UTC, phildominguez commented on lang/en.json
> +    "HealthOrigin": "Origin",
I think we could just use `E20.SkillConditioning` and `E20.Origin` for these

2023-06-22 00:59 UTC, phildominguez commented on module/documents/actor.mjs
> +    let origin = 0;
```suggestion
    let startingHealth = 0;
```

2023-06-22 00:59 UTC, phildominguez commented on module/documents/actor.mjs
> +    }
```suggestion
    const bonusName = game.i18n.localize('E20.HealthBonus');

    const origins = getItemsOfType('origin', this.items);
    if (origins.length) {
      origin = origins[0].system.startingHealth;
    }
```

2023-06-24 02:13 UTC, JFranklin3000 commented on lang/en.json
> +    "HealthBonus": "Bonus",
Changed

2023-06-24 02:13 UTC, JFranklin3000 commented on lang/en.json
> +    "HealthOrigin": "Origin",
Changed

2023-06-24 02:14 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +    let origin = 0;
Changed

2023-06-25 20:05 UTC, phildominguez approved these changes

2023-06-25 22:17 UTC, merged