upgrade clean up
WookieeMatt/Essence20 pull request #471
Opened 2023-06-25 00:33 UTC by JFranklin3000

##### In this PR
-fixes upgrade drop on drones and characters that can transform
-simplified the error message  

##### Testing
-Make sure that drops on Drones and actors that can transform work And other characters do not.

2023-06-25 14:19 UTC, phildominguez requested changes

2023-06-25 14:19 UTC, phildominguez commented on lang/en.json
> +    "UpgradeDropError": "This upgrade can not be dropped here",
```suggestion
    "UpgradeDropError": "Upgrade of type {upgrade_type} cannot be dropped on {actor_type}",
```

2023-06-25 14:19 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +        ui.notifications.error(game.i18n.format(game.i18n.localize('E20.UpgradeDropError')));
```suggestion
      const actor_type = this.actor.type;
      const upgrade_type = sourceItem.system.type;

      if (actor_type == 'companion' && this.actor.system.type == 'drone' && upgrade_type == 'drone') {
        super._onDropItem(event, data);
      } else if (this.actor.system.canTransform && upgrade_type == 'armor') {
        super._onDropItem(event, data);
      } else {
        ui.notifications.error(game.i18n.format('E20.UpgradeDropError', {upgrade_type, actor_type}));
```
Untested, but something like this should work for a better error message

2023-06-25 14:46 UTC, phildominguez requested changes

2023-06-25 14:46 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    const upgrade_type = sourceItem.system.type;
I would put these in the upgrade case since they're only used there

2023-06-25 20:07 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +    const upgrade_type = sourceItem.system.type;
rolled back changes

2023-06-26 10:48 UTC, phildominguez approved these changes

2023-06-26 13:06 UTC, merged