Added Alteration to Characters
WookieeMatt/Essence20 pull request #473
Opened 2023-07-01 15:29 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- Created Alteration Item
- Added Alterations to the Gear Tab

##### Testing
- Create Item and Drag and Drop to Actor sheet.

2023-07-01 16:46 UTC, phildominguez requested changes

2023-07-01 16:46 UTC, phildominguez commented on templates/actor/parts/items/alteration/details.hbs
Would chips for the essences/costs be a good idea?

2023-07-01 16:46 UTC, phildominguez commented on lang/en.json
> +    "AlterationCost": "Cost",
We already have `E20.Bonus`, and we have a few entries that are just "Cost" as well. Would be good to just have `E20.Cost` I think.

2023-07-01 16:46 UTC, phildominguez commented on template.json
> +      "cost": "",
Aren't these numbers?

2023-07-01 17:14 UTC, JFranklin3000 commented on lang/en.json
> +    "AlterationCost": "Cost",
That makes sense to go to one name.

2023-07-01 17:14 UTC, JFranklin3000 commented on template.json
> +      "cost": "",
Nope benefit can be other things. Basically the 3 main things that are a benefit/ cost are essences, movement, and Other things. Here is a good example. 

![image](https://github.com/WookieeMatt/Essence20/assets/71140111/3e2d7cf9-6834-42d6-be06-0cbf9410cbc0)

2023-07-01 17:15 UTC, JFranklin3000 commented on templates/actor/parts/items/alteration/details.hbs
yea I need to figure out the best layout for the various types yet.

2023-07-02 01:03 UTC, phildominguez approved these changes

2023-07-02 01:05 UTC, merged