Weapon effects
WookieeMatt/Essence20 pull request #475
Opened 2023-07-03 12:59 UTC by JFranklin3000

##### In this PR
- Created Weapon Effects template
- Created Weapon Effects Item sheet

##### Testing
- Create an Effect Item 
- Validated fields working,

2023-07-03 23:09 UTC, phildominguez requested changes

2023-07-03 23:09 UTC, phildominguez commented on lang/en.json
> +    "ShiftDown": "Shift Down",
How about add ShiftUp and remove RollDialogShiftDown/RollDialogShiftUp?

2023-07-03 23:09 UTC, phildominguez commented on lang/en.json
> +      "effect": "Weapon Effect",
Any objections to making it `weaponEffect`? Right now it's out of order in the item creation menu.

2023-07-04 17:53 UTC, JFranklin3000 commented on lang/en.json
> +      "effect": "Weapon Effect",
nope changed.

2023-07-04 17:54 UTC, JFranklin3000 commented on lang/en.json
> +    "ShiftDown": "Shift Down",
done.

2023-07-04 18:04 UTC, phildominguez approved these changes

2023-07-04 18:11 UTC, merged