Alteration drop
WookieeMatt/Essence20 pull request #478
Opened 2023-07-05 21:25 UTC by JFranklin3000

##### In this PR
- Added drops for alteration that modify essences. 
- deletes for those dropped alterations as well. 

##### Testing
- create an actor 
- create an alteration
- drop the alteration on to the actor
- delete the alteration from the actor.

2023-07-07 00:02 UTC, phildominguez requested changes

2023-07-07 00:02 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  async _alterationStatUpdate(alteration, bonusSkill, dropFunc, costEssence, options) {
This and `_onAlterationDelete` have a lot of similar code. Can we break out more methods to help with that?

2023-07-07 02:44 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +    }
yea I was trying to figure out a way to do that, but that might work.

2023-07-07 02:51 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +      if (costEssence == 'strength') {
fixed

2023-07-07 03:10 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +
fixed

2023-07-07 03:10 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +    }
changed

2023-07-07 03:10 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +
fixed

2023-07-07 03:10 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +
fixed

2023-07-07 03:11 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +  async _showAlterationCostSkillDialog (alteration, bonusSkill, dropFunc, options) {
fixed

2023-07-07 11:57 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +    this._actorSheet = actorSheet;
I was keeping it there in case I needed for the rest of the drop.

2023-07-07 14:11 UTC, phildominguez requested changes

2023-07-07 14:11 UTC, phildominguez commented on module/helpers/utils.mjs
> + * @param
I know you're doing these later for alteration-handler, but I'd knock this out before we forget.

2023-07-07 14:11 UTC, phildominguez commented on module/helpers/utils.mjs
> +export async function getSkillChange(skill, change, actor) {
What about `getShiftedSkill`? And make `change` to `shift`? I think I like the specificity of "shifting" a skill vs "changing" it.

2023-07-07 14:11 UTC, phildominguez commented on module/helpers/utils.mjs
> +  if (skill == "initiative") {
```suggestion
  let newShift = "";

  if (skill == "initiative") {
```

2023-07-07 14:11 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +
```suggestion
```

2023-07-07 14:11 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +    costSkillString = cost[1];
```suggestion
    const bonusNewShift, bonusSkillString = await getSkillChange(bonusSkill, 1, this._actor);
    const costNewShift, costSkillString = await getSkillChange(costSkill, -1, this._actor);
```
Untested but should work 1

2023-07-07 14:11 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +    costSkillString = cost[1];
```suggestion
    const bonusNewShift, bonusSkillString = await getSkillChange(bonusSkill, -1, this._actor);
    const costNewShift, costSkillString = await getSkillChange(costSkill, 1, this._actor);
```
Untested but should work 2

2023-07-07 14:11 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +
```suggestion
```

2023-07-07 14:11 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
> +    skillString = skillChange[1];
```suggestion
    const newShift, skillString = await getSkillChange(selectedSkill, 1, this._actor);
```
Untested but should work 4

2023-07-07 14:11 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
> +    skillString = skillChange[1];
```suggestion
    const newShift, skillString = await getSkillChange(selectedSkill, 1, this._actor);
```
Untested but should work 3

2023-07-07 14:11 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +
```suggestion
```

2023-07-07 14:11 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
> +
```suggestion
```

2023-07-07 14:11 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +    if (alteration.system.selectedEssence) {
```suggestion
    let costEssence = "";

    if (alteration.system.selectedEssence) {
```

2023-07-07 14:11 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +    if (options) {
```suggestion
    let costEssence = "";

    if (options) {
```

2023-07-08 22:13 UTC, JFranklin3000 commented on lang/en.json
> +    "AlterationIncrease": "Select a skill to increase.",
Changed

2023-07-08 22:14 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +  async _alterationBonusSet (alteration, options, dropFunc) {
Changed

2023-07-08 22:15 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +  async _alterationStatUpdate(alteration, bonusSkill, dropFunc, costEssence, options) {
Pulled out one function

2023-07-09 18:28 UTC, phildominguez requested changes

2023-07-09 18:28 UTC, phildominguez commented on module/helpers/utils.mjs
> + * @param {Actor} actor  The actor
Don't forget the @return

2023-07-09 18:28 UTC, phildominguez commented on module/helpers/utils.mjs
> + * @param {Text} skill The skill shifting
```suggestion
 * @param {String} skill The skill shifting
```
Here and elsewhere

2023-07-09 18:28 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * @param {Object} alteration The alteration
These should be Alteration in a bunch of methods instead of Object. Better to be as specific as possible.

2023-07-09 18:28 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +   * @param {Object} options    The options resulting from _showAlterationBonusSkillDialog()
A handful of methods have an @param with indentation that's off

2023-07-09 18:28 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * Handle the dropping of an alteratione on to a character
```suggestion
  * Handle the dropping of an alteration onto a character
```

2023-07-09 18:28 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +      await this._showAlterationCostSkillDialog (alteration, bonusSkill, dropFunc);
```suggestion
      await this._showAlterationCostEssenceDialog(alteration, bonusSkill, dropFunc);
    } else {
      await this._showAlterationCostSkillDialog(alteration, bonusSkill, dropFunc);
```

2023-07-09 18:28 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * Handles creating a dialog to choose an essencd to decrease
```suggestion
  * Handles creating a dialog to choose an essence to decrease
```

2023-07-11 01:04 UTC, phildominguez requested changes

2023-07-11 01:04 UTC, phildominguez commented on module/helpers/utils.mjs
> + * @return {Text} skillString The name of the skill being shifted
```suggestion
 * @return {String} newShift The value of the new Shift
 * @return {String} skillString The name of the skill being shifted
```

2023-07-11 01:04 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * @param {Object} alteration The alteration
```suggestion
  * @param {Alteration} alteration The alteration
```

2023-07-11 01:04 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +   * @param {Text} bonusSkill    The skill selected from _processAlterationSkillIncrease()
```suggestion
  * @param {String} bonusSkill    The skill selected from _processAlterationSkillIncrease()
```

2023-07-11 01:04 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * @param {Text} bonusSkill    The skill selected from _processAlterationSkillIncrease()
```suggestion
  * @param {String} bonusSkill    The skill selected from _processAlterationSkillIncrease()
```

2023-07-11 01:04 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * @param {Text} costEssence    The essence selected from _showAlterationCostEssenceDialog()
```suggestion
  * @param {String} bonusSkill    The skill selected from _processAlterationSkillIncrease()
  * @param {Function} dropFunc   The function to call to complete the Alteration drop
  * @param {String} costEssence    The essence selected from _showAlterationCostEssenceDialog()
```

2023-07-13 23:31 UTC, phildominguez requested changes

2023-07-13 23:31 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +      ui.notifications.warn(game.idemo8n.localize('E20.AlterationSelectNoSkill'));
```suggestion
      ui.notifications.warn(game.i18n.localize('E20.AlterationSelectNoSkill'));
```

2023-07-13 23:31 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +      ui.notifications.warn(game.idemo8n.localize('E20.AlterationSelectNoSkill'));
```suggestion
      ui.notifications.warn(game.i18n.localize('E20.AlterationSelectNoSkill'));
```

2023-07-13 23:31 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +              if (CONFIG.E20.skillShiftList.indexOf(this._actor.system.skills[skill].shift) < 10) {
Dunno if you'd be up for this, but we could add a helper method where you pass in an actor's shift, and a shift to compare it to. Something like `shiftIsHigher(shift1, shift2)`, then here you would call `if (shiftIsHigher(this._actor.system.skills[skill].shift, 'd20'))`. Would help with code duplication and readability imo.

2023-07-13 23:52 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +              if (CONFIG.E20.skillShiftList.indexOf(this._actor.system.skills[skill].shift) < 10) {
I feel like we are going to need to do something like this a lot so having a helper would make sense. For example, Prereqs later on where something requires Brawn d4 for example.

2023-07-14 17:41 UTC, phildominguez requested changes

2023-07-14 17:41 UTC, phildominguez commented on module/helpers/utils.mjs
> + */
Don't forget @return

2023-07-14 17:41 UTC, phildominguez commented on module/helpers/utils.mjs
> +    }
```suggestion
    return CONFIG.E20.skillShiftList.indexOf(shift1) < CONFIG.E20.skillShiftList.indexOf(shift2));
```
Similar for others

2023-07-14 17:41 UTC, phildominguez commented on module/helpers/utils.mjs
> +  }
I think it's worth throwing an error if the operand doesn't match something we'd expect, something like

```
throw new Error(`Operator ${operator} not expected`);
```

2023-07-14 17:41 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +              if (compareShift(this._actor.system.skills[skill].shift, "d20","greater")) {
```suggestion
              if (compareShift(this._actor.system.skills[skill].shift, "d20", "greater")) {
```

2023-07-14 17:41 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +          if (compareShift(this._actor.system.skills[skill].shift, "d20","greater")) {
```suggestion
          if (compareShift(this._actor.system.skills[skill].shift, "d20", "greater")) {
```

2023-07-14 17:41 UTC, phildominguez commented on module/helpers/utils.mjs
> +export function compareShift(shift1,shift2,operator) {
```suggestion
export function compareShift(shift1, shift2, operator) {
```

2023-07-14 22:33 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +  }
Is that valid code or would we need to write that differently?

2023-07-14 22:33 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +    }
Again with the oh you can do it this way. 🤣

2023-07-14 22:33 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +              if (compareShift(this._actor.system.skills[skill].shift, "d20","greater")) {
fixed

2023-07-14 22:34 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +          if (compareShift(this._actor.system.skills[skill].shift, "d20","greater")) {
fixed

2023-07-14 22:34 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +export function compareShift(shift1,shift2,operator) {
fixed

2023-07-15 17:51 UTC, phildominguez requested changes

2023-07-15 17:51 UTC, phildominguez commented on module/helpers/utils.mjs
> + * @return {Boolean} result the result of the comparison
```suggestion
 * @return {Boolean} The result of the comparison
```

2023-07-15 17:51 UTC, phildominguez commented on module/helpers/utils.mjs
> +    return false;
```suggestion
    throw new Error(`Operator ${operator} not expected`);
```

2023-07-15 17:56 UTC, phildominguez approved these changes

2023-07-15 17:57 UTC, merged