Draft Alteration movement
WookieeMatt/Essence20 pull request #482
Opened 2023-08-05 14:50 UTC by JFranklin3000

Adding Alteration Movement options to Alterations. 

##### In this PR
- 

##### Testing
-

2023-08-26 02:53 UTC, phildominguez requested changes

2023-08-26 02:53 UTC, phildominguez commented on module/documents/actor.mjs
> +          system.movement[movementType].total = Math.floor(system.movement.ground.total/5*.5)*5;
```suggestion
          system.movement[movementType].total = Math.floor(system.movement.ground.total / 5 * .5) * 5;
```

2023-08-26 02:53 UTC, phildominguez commented on module/essence20.mjs
> +
```suggestion
```

2023-08-26 02:53 UTC, phildominguez commented on module/essence20.mjs
> +
```suggestion
```

2023-08-26 02:53 UTC, phildominguez commented on module/helpers/utils.mjs
> +export function rememberValues(html) {
Desc block on this

2023-08-26 02:53 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  *
Don't forget a short desc of the method

2023-08-26 02:53 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  *
Don't forget a short desc of the method

2023-08-26 02:53 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +            maxValue = (this._actor.system.movement[movementType].base/5-1);
```suggestion
            maxValue = (this._actor.system.movement[movementType].base / 5 - 2);
          }else {
            maxValue = (this._actor.system.movement[movementType].base / 5 - 1);
```

2023-08-26 02:53 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +    for (const [movementReductionType, movementReductionValue] of Object.entries(options)) {
```suggestion
    let additionalBonusMovement = 0;

    for (const [movementReductionType, movementReductionValue] of Object.entries(options)) {
```

2023-08-26 02:53 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +      }
Helper method? Duplicated code.

2023-08-26 02:53 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +      }else{
```suggestion
      } else{
```

2023-08-26 14:14 UTC, phildominguez requested changes

2023-08-26 14:14 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +    if (alteration.system.movementCost){
```suggestion
    if (alteration.system.movementCost) {
```

2023-08-26 14:14 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +    }else {
```suggestion
    } else {
```

2023-08-26 14:14 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +
```suggestion
```

2023-09-03 17:08 UTC, JFranklin3000 commented on module/documents/actor.mjs
> +          system.movement[movementType].total = Math.floor(system.movement.ground.total/5*.5)*5;
Updated and added comment.

2023-09-03 17:10 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +export function rememberValues(html) {
Added

2023-09-03 17:11 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +  *
fixed.

2023-09-03 17:12 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +  *
fxied

2023-09-03 20:30 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +      }
fixed in a much different way

2023-09-03 22:32 UTC, phildominguez requested changes

2023-09-03 22:32 UTC, phildominguez commented on module/helpers/utils.mjs
> + * @returns {Object>}  The dialog inputs and their entered values
```suggestion
/**
 * Returns values of inputs upon dialog submission. Used for passing data between sequential dialogs.
 * (This one does values instead of checked)
 * @param {HTML} html   The html of the dialog upon submission
 * @returns {Object}  The dialog inputs and their entered values
```

2023-09-03 22:32 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
>      for (const perk of originDelete.system.originPerkIds) {
```suggestion
    const originDelete = this._actor.items.get(origin._id);

    for (const perk of originDelete.system.originPerkIds) {
```

2023-09-03 22:32 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * @param {Options} options  The options selected from the dialog
Swap order to match param order

2023-09-03 22:32 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * Handles the movements choices and updating the actors movments
```suggestion
  * Handles the movements choices and updating the actors movements
```

2023-09-03 22:32 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +      } else{
```suggestion
      } else {
```

2023-09-03 22:32 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +      let movementNumberConversion = Number(movementReductionValue);
```suggestion
      const movementReduction = Number(options[movementReductionType].value);
      const movementReductionMax = options[movementReductionType].max;
```

2023-09-03 23:22 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +      let movementNumberConversion = Number(movementReductionValue);
changed

2023-09-03 23:22 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +  * @param {Options} options  The options selected from the dialog
changed

2023-09-04 00:06 UTC, phildominguez requested changes

2023-09-04 00:06 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +      if (movementNumberConversion > movementReductionMax) {
You missed some `movementNumberConversion`

2023-09-04 14:09 UTC, phildominguez approved these changes
Nice work!

2023-09-04 14:14 UTC, merged