Cleaning up changes and adding Cobra Codex Alterations
WookieeMatt/Essence20 pull request #491
Opened 2023-09-15 18:30 UTC by JFranklin3000

##### In this PR
- Cobra Codex Alteration Items Added
- Check to disallow adding the same alteration twice
- originalId for almost all items dropped on an actor

##### Testing
- Validate new Items
- drop prevention for too many movement reductions, duplicates, etc. 
- items are in ccitems

2023-09-16 23:35 UTC, phildominguez requested changes

2023-09-16 23:35 UTC, phildominguez commented on template.json
> +      "item": {
I think this name is too vague for me. What about `uniqueItem`? Or maybe just `originalItem`.

2023-09-16 23:35 UTC, phildominguez commented on module/helpers/utils.mjs
> +export function parseId (uuid) {
```suggestion
export function parseId(uuid) {
```
Don't forget method desc block

2023-09-16 23:35 UTC, phildominguez commented on templates/item/sheets/alteration.hbs
> +        {{!-- Alteration Non Essence Bonus --}}
```suggestion
      {{#ifEquals system.alterationType 'other'}}
        {{!-- Alteration Non Essence Bonus --}}
```

2023-09-16 23:35 UTC, phildominguez commented on templates/item/sheets/alteration.hbs
```suggestion
      {{#ifEquals system.alterationType 'essence'}}
```

2023-09-17 00:33 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +    for (let actorItem of this._actor.items) {
both fixed

2023-09-17 00:57 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +      await this._showAlterationCostMovementDialog(alteration, dropFunc, alterationUuid);
all fixed

2023-09-17 00:57 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
>    * @param {Function} dropFunc   The function to call to complete the Alteration drop
fixed

2023-09-17 00:57 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
>    * @param {Function} dropFunc   The function to call to complete the Alteration drop
fixed

2023-09-17 00:57 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +    if (!this._actor.system.movement.ground.base && !this._actor.system.movement.aerial.base && !this._actor.system.movement.climb.base && !this._actor.system.movement.swim.base) {
fixed

2023-09-17 00:57 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +            callback: html => this._processAlterationSkillIncrease(alteration, rememberOptions(html), dropFunc, alterationUuid),
fixed

2023-09-17 00:58 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +export function parseId (uuid) {
fixed

2023-09-17 00:58 UTC, JFranklin3000 commented on templates/item/sheets/alteration.hbs
> +        {{!-- Alteration Non Essence Bonus --}}
fixed

2023-09-17 00:58 UTC, JFranklin3000 commented on templates/item/sheets/alteration.hbs
fixed

2023-09-17 00:58 UTC, JFranklin3000 commented on template.json
> +      "item": {
I was thinking of this as the template that goes on all items.

2023-09-17 00:59 UTC, JFranklin3000 commented on template.json
> +      "alterationType": "other",
I was thinking of it as a way to differentiate from item type which is already there.

2023-09-17 01:21 UTC, phildominguez commented on module/helpers/utils.mjs
> +export function parseId(uuid) {
Return type is String or null for desc

2023-09-17 01:21 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * @param {AlterationUUID} alterationUuid The original ID of the alteration
These are just String

2023-09-17 01:21 UTC, phildominguez commented on template.json
> +      "alterationType": "other",
Generally in the template we've just used `type` though, like Gear, Perk, Upgrade

2023-09-17 01:24 UTC, phildominguez commented on template.json
> +      "item": {
That works, just move it before `itemDescription` everywhere to keep it alphabetical.

2023-09-17 17:57 UTC, phildominguez requested changes

2023-09-17 17:57 UTC, phildominguez commented on module/helpers/utils.mjs
> +* @return {string} index or null returned.
```suggestion
* @return {string|null} index or null returned.
```

2023-09-17 17:57 UTC, phildominguez commented on module/helpers/utils.mjs
>  /**
```suggestion
    index = id;
  }

  return index || null;
}

/**
```

2023-09-17 17:57 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * @param {AlterationUUID} alterationUuid The original ID of the alteration
```suggestion
  * @param {String} alterationUuid The original ID of the alteration
```

2023-09-17 17:57 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * @param {string} alterationUuid The original ID of the alteration
```suggestion
  * @param {String} alterationUuid The original ID of the alteration
```
We sort of mix caps between different files, but we should try to be consistent in the same file

2023-09-17 17:57 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * @param {AlterationUUID} alterationUuid The original ID of the alteration
```suggestion
  * @param {String} alterationUuid The original ID of the alteration
```

2023-09-17 17:57 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * @param {AlterationUUID} alterationUuid The original ID of the alteration
```suggestion
  * @param {String} alterationUuid The original ID of the alteration
```

2023-09-17 17:57 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * @param {AlterationUUID} alterationUuid The original ID of the alteration
```suggestion
  * @param {String} alterationUuid The original ID of the alteration
```

2023-09-17 17:57 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * @param {AlterationUUID} alterationUuid The original ID of the alteration
```suggestion
  * @param {String} alterationUuid The original ID of the alteration
```

2023-09-17 17:57 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  * @param {AlterationUUID} alterationUuid The original ID of the alteration
```suggestion
  * @param {String} alterationUuid The original ID of the alteration
```

2023-09-17 17:57 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +      return droppedItemList;
Just thought of this, what about making a separate function like `_onDropDefault` that does all this stuff, then we don't need to declare the 3 vars above and it'll be a bit nicer.

2023-09-17 17:57 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
>    /**
```suggestion
  }

  /**
```

2023-09-17 21:17 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +      return droppedItemList;
changed

2023-09-17 23:41 UTC, phildominguez requested changes

2023-09-17 23:41 UTC, phildominguez commented on module/sheet-handlers/alteration-handler.mjs
> +  async _showAlterationCostSkillDialog(alteration, bonusSkill, alterationUuid, dropFunc, options) {
I would keep dropFunc at the end like elsewhere

2023-09-18 00:06 UTC, JFranklin3000 commented on module/sheet-handlers/alteration-handler.mjs
> +  async _showAlterationCostSkillDialog(alteration, bonusSkill, alterationUuid, dropFunc, options) {
If I do that then we will bring back the issue you found earlier when options is empty.

2023-09-18 02:47 UTC, phildominguez requested changes

2023-09-18 02:47 UTC, phildominguez commented on lang/en.json
> +    "AlterationAlreadyTaken": "You have already add this alteration",
```suggestion
    "AlterationAlreadyTaken": "You have already added this alteration",
```

2023-09-18 12:53 UTC, phildominguez approved these changes

2023-09-18 12:54 UTC, merged