Powers redesign
WookieeMatt/Essence20 pull request #526
Opened 2023-10-12 02:07 UTC by JFranklin3000

##### In this PR
- redesigned Power Item
- add start of handler for power

##### Testing
- create new power and make sure everything is working.

2023-10-12 17:39 UTC, phildominguez requested changes

2023-10-12 17:39 UTC, phildominguez commented on lang/en.json
> +    "PowerActive": "Can Be Activated",
I still think having "Passive" is a lot more clear than "Can be activated". Thoughts @guswadsworth12?

2023-10-12 17:39 UTC, phildominguez commented on lang/en.json
> +    "PowerIncrease": "Can Addition Power Be Spent?",
Does this mean you can spend more points in one go to increase the power's effect?

2023-10-12 17:39 UTC, phildominguez commented on lang/en.json
> +    "SelectionLimit": "Number of Times Selected",
```suggestion
    "PowerSelectionLimit": "Selection Limit",
```
To me "Number of Times Selected" sounds like how many times this item has be selected already, not the max.

2023-10-12 17:39 UTC, phildominguez commented on lang/en.json
> +    "PowersUsesPerScene": "Uses Per Scene",
```suggestion
    "PowerUsesPerScene": "Uses Per Scene",
```

2023-10-12 17:39 UTC, phildominguez commented on lang/en.json
> +    "PowerSorcerous": "Sorcerous",
I would do these as PowerSourceBlah to keep them grouped up. So PowerSourceGrid, PowerSourcePersonalPower, PowerSourceSorcerous.

2023-10-12 17:39 UTC, phildominguez commented on lang/en.json
> +    "ActionStandard": "Standard",
```suggestion
    "ActionType": "Action Type",
    "ActionTypeFree": "Free",
    "ActionTypeMove": "Move",
    "ActionTypeStandard": "Standard",
```

2023-10-12 19:00 UTC, JFranklin3000 commented on lang/en.json
> +    "PowerActive": "Can Be Activated",
I don't know that that makes sense this is for power with an activation. Or are you saying check the box to make the extra fields go away?

2023-10-12 19:00 UTC, JFranklin3000 commented on lang/en.json
> +    "PowerIncrease": "Can Addition Power Be Spent?",
yea some powers are 1+ or 1-3 or something like that, most are a set number like 1 or 2.

2023-10-12 19:01 UTC, JFranklin3000 commented on lang/en.json
> +    "SelectionLimit": "Number of Times Selected",
Yea that one was weirdly worded.

2023-10-12 19:11 UTC, JFranklin3000 commented on lang/en.json
> +    "PowerSorcerous": "Sorcerous",
Changed although I left out Personal Power as that is the name of the points.

2023-10-13 23:50 UTC, phildominguez commented on lang/en.json
> +    "PowerIncrease": "Can Addition Power Be Spent?",
Gotcha. I know DND uses "upcast" for spells, but it sounds like E20 doesn't have their own term?

2023-10-14 00:08 UTC, JFranklin3000 commented on lang/en.json
> +    "PowerIncrease": "Can Addition Power Be Spent?",
As I go along I might change this to the maximum number of points but I am going to leave it as that for now.

2023-10-14 00:41 UTC, phildominguez requested changes

2023-10-14 00:41 UTC, phildominguez commented on template.json
> +	  "actionType": "",
The default for this should be one of the valid values

2023-10-14 00:41 UTC, phildominguez commented on lang/en.json
> +    "PowerIncrease": "Can Addition Power Be Spent?",
Gotcha. It should be "Additional" instead of "Addition", yeah?

Also I think we can remove the question mark since we don't do that for other checkboxes, so "Additional Power Can Be Spent".

2023-10-14 00:41 UTC, phildominguez commented on template.json
> +	  "usesPerScene": null
Indentation is off

2023-10-14 00:41 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +  async powerUpdate(power, dropFunc) {
```suggestion
  */
  async powerUpdate(power, dropFunc) {
```

2023-10-14 00:43 UTC, JFranklin3000 commented on template.json
> +	  "actionType": "",
Not sure we can do that because of the way we create it. It is going to have a new Id for every actor.

2023-10-14 00:45 UTC, JFranklin3000 commented on template.json
> +	  "usesPerScene": null
fixed

2023-10-14 01:20 UTC, phildominguez approved these changes

2023-10-14 01:22 UTC, merged