Powers drop
WookieeMatt/Essence20 pull request #527
Opened 2023-10-14 01:26 UTC by JFranklin3000

##### In this PR
- Added drop functionality
- Removed the drop down and hid the roll for power without activations

##### Testing
- create powers and drop on to actors
- make sure activation works and max number of powers as well.

2023-10-14 02:04 UTC, phildominguez requested changes

2023-10-14 02:10 UTC, JFranklin3000 commented on templates/actor/parts/items/power/container.hbs
> +      <a class="rollable" data-roll-type={{item.type}} title="{{localize 'E20.PowerRollTitle'}}"></a>
I had it there so you could still send the description to the chat for powers that don't have an activation.

2023-10-14 02:14 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
> +      if (actorItem.type == 'power') {
fixed

2023-10-14 02:18 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
> +          if (actorItem.name == 'Personal Power') {
fixed

2023-10-14 02:22 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
> +        if (actorItem.system.originalId == powerUuid) {
fixed

2023-10-14 02:22 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
> +            ui.notifications.warn(game.i18n.localize('E20.PowerAlreadyTaken'));
fixed

2023-10-14 02:28 UTC, phildominguez commented on templates/actor/parts/items/power/container.hbs
> +      <a class="rollable" data-roll-type={{item.type}} title="{{localize 'E20.PowerRollTitle'}}"></a>
I think that's a button defined in a different spot that shows up for all items.

2023-10-15 15:53 UTC, phildominguez requested changes

2023-10-15 15:53 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +    let timesTaken  = 0;
```suggestion
    let timesTaken = 0;
```

2023-10-15 15:53 UTC, phildominguez commented on templates/actor/parts/items/power/container.hbs
> +      <a class="rollable" data-roll-type={{item.type}} title="{{localize 'E20.PowerRollTitle'}}"><i class="fas fa-battery-bolt"></i></a>
Missing localization when I click this:
![image](https://github.com/WookieeMatt/Essence20/assets/41161497/4e04d403-b508-4d2a-b91b-36aab49fc46b)

2023-10-15 16:21 UTC, JFranklin3000 commented on templates/actor/parts/items/power/container.hbs
> +      <a class="rollable" data-roll-type={{item.type}} title="{{localize 'E20.PowerRollTitle'}}"></a>
ah, ok I see that now. Yep that can get pulled.

2023-10-15 16:21 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
> +    let timesTaken  = 0;
fixed

2023-10-15 16:26 UTC, JFranklin3000 commented on templates/actor/parts/items/power/container.hbs
> +      <a class="rollable" data-roll-type={{item.type}} title="{{localize 'E20.PowerRollTitle'}}"><i class="fas fa-battery-bolt"></i></a>
I was going to redo the chat card at the end but this is in the main branch. I will mark that for a future change.

2023-10-15 16:57 UTC, phildominguez approved these changes

2023-10-15 17:11 UTC, merged