Sorcerous powers
WookieeMatt/Essence20 pull request #528
Opened 2023-10-15 16:36 UTC by JFranklin3000

##### In this PR
- Add the Finsters and Furious Fighters Compendiums
- Created the Sorcery General Perk
- Created Sorcerous Power as a ClassFeature that gets added when the Perk is added. 

##### Testing
- build ffmcitems pack
- drop item on to Power Ranger
- create power and validate Sorcerous Power is an option in the drop down.

2023-10-15 17:18 UTC, phildominguez requested changes

2023-10-15 17:18 UTC, phildominguez commented on module/sheet-handlers/perk-handler.mjs
> +    }
Atm this perk can be dropped multiple times, so it will generate multiple SP powers:
![image](https://github.com/WookieeMatt/Essence20/assets/41161497/9766525d-167f-4529-9d51-e9599b9f5b0e)

2023-10-15 17:18 UTC, phildominguez commented on module/sheet-handlers/perk-handler.mjs
> +    const perkUuid = parseId(perk.uuid);
```suggestion
  async perkUpdate(perk, dropFunc) {
    const perkUuid = parseId(perk.uuid);
```

2023-10-15 17:18 UTC, phildominguez commented on module/sheet-handlers/perk-handler.mjs
> +  async perkUpdate(perk, dropFunc) {
Comment block on this

2023-10-15 17:18 UTC, phildominguez commented on module/sheet-handlers/perk-handler.mjs
> +  /**
```suggestion
export class PerkHandler {
  /**
```

2023-10-15 17:18 UTC, phildominguez commented on module/sheet-handlers/perk-handler.mjs
> +    if (perkUuid == "xUBOE1s5pgVyUrwj") {
A string like this I would make a const for, maybe just inside the PerkHandler class? Something like SORCERY_PERK_ID.

2023-10-15 17:35 UTC, JFranklin3000 commented on module/sheet-handlers/perk-handler.mjs
> +    if (perkUuid == "xUBOE1s5pgVyUrwj") {
Should we maybe do like an ids.mjs? Something like config.mjs but where we just track the Ids of items so that if we ever need to recreate an item we only change it in one place?

2023-10-15 18:01 UTC, JFranklin3000 commented on module/sheet-handlers/perk-handler.mjs
> +    }
Let me deep dive this, in general you should only take a perk once. but let me see what kind of exceptions to that there are. But I will probably add something similar to what I did for powers probably as a separate change though.

2023-10-15 18:21 UTC, JFranklin3000 commented on module/sheet-handlers/perk-handler.mjs
> +  async perkUpdate(perk, dropFunc) {
Fixed

2023-10-15 18:58 UTC, phildominguez commented on module/sheet-handlers/perk-handler.mjs
> +    if (perkUuid == "xUBOE1s5pgVyUrwj") {
Yeah not opposed at all especially if we're doing more like this

2023-10-15 19:00 UTC, phildominguez requested changes

2023-10-15 23:38 UTC, JFranklin3000 commented on module/sheet-handlers/perk-handler.mjs
> +    if (perkUuid == "xUBOE1s5pgVyUrwj") {
changed

2023-10-16 00:31 UTC, phildominguez requested changes

2023-10-16 00:31 UTC, phildominguez commented on module/sheet-handlers/perk-handler.mjs
> +    const SORCERY_PERK_ID = "xUBOE1s5pgVyUrwj";
This will recreate the variable every time `perkUpdate` is run. Let's put it after the class export declaration on line 5 so it's just made once.

2023-10-16 01:01 UTC, phildominguez approved these changes

2023-10-16 01:01 UTC, merged