Power Cost
WookieeMatt/Essence20 pull request #529
Opened 2023-10-15 17:21 UTC by JFranklin3000

##### In this PR
- Added spending of Personal Power to Activated Powers
- If no activation no button
- if set cost no pop up
- if expanded cost and a max pop up 
- if expanded and no max,  max is total power points

##### Testing
- build powers that can be activated with different power point costs and different maximums.

2023-10-16 13:45 UTC, phildominguez requested changes
Please do a pass for whitespace/indentation and comment blocks as well

2023-10-16 13:45 UTC, phildominguez commented on templates/dialog/power-cost.hbs
> +      <li>
Idt this needs to be a list? Just need the label.

2023-10-16 13:45 UTC, phildominguez commented on lang/en.json
> +    "PowerIncrease": "Power Can Be increased",
```suggestion
    "PowerIncrease": "Power Can Be Increased",
```

2023-10-16 13:45 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +    }
```suggestion
    if ((options[power.name].value > options[power.name].max)
      || (classFeature && options[power.name].value > classFeature.system.uses.value)) {
      ui.notifications.error(game.i18n.localize('E20.PowerOverSpent'));
      return;
    } else if (classFeature) {
      classFeature.update({ ["system.uses.value"]: Math.max(
        0, classFeature.system.uses.value - options[power.name].value) });
    }
```

2023-10-16 13:45 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +    }
```suggestion
    } else if (classFeature) {
      classFeature.update({ ["system.uses.value"]: Math.max(
        0, classFeature.system.uses.value - power.system.powerCost) });
    }
```
Though it seems like this conditional lets me spend unlimited power if it's a fixed-cost power

2023-10-16 13:45 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +        maxPower = classFeature.system.uses.value;
Weird scenario, but, what if a user deletes their personal power class feature, and then drops a power? It can reach here and error on power use. Probably another argument for making person power NOT a class feature.

2023-10-16 13:45 UTC, phildominguez commented on templates/dialog/power-cost.hbs
> +          {{localize power.name}} (min 0, max {{maxPower}})
Should the min be the powerCost?

2023-10-16 13:45 UTC, phildominguez commented on template.json
> +    "isVariable": false,
I think I'd prefer something like `hasVariableCost`

2023-10-16 23:44 UTC, JFranklin3000 commented on templates/dialog/power-cost.hbs
> +          {{localize power.name}} (min 0, max {{maxPower}})
it should that is a good call

2023-10-16 23:48 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
> +    }
You don't get the pop up if it is fixed cost so you can only spend points if you get into the other function.

2023-10-16 23:49 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
> +    }
pretty sure this should stay an else with a check that you have class feature separately. Basically we are doing if the power isVariable then go through this code if it isn't do the else code.

2023-10-17 00:01 UTC, JFranklin3000 commented on templates/dialog/power-cost.hbs
> +          {{localize power.name}} (min 0, max {{maxPower}})
fixed

2023-10-17 00:01 UTC, JFranklin3000 commented on template.json
> +    "isVariable": false,
fixed

2023-10-17 00:02 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
> +    }
Also this is to support threatPowers which won't have a classFeature

2023-10-17 00:03 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
> +    }
Also this allows for threatPowers

2023-10-17 00:13 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
> +        maxPower = classFeature.system.uses.value;
This is definitely a possible problem the if (ClassFeature) I am using should avoid most of these, but this is a good catch.

2023-10-17 01:41 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
> +    }
Ok I think I added a fix

2023-10-17 03:18 UTC, phildominguez requested changes

2023-10-17 03:18 UTC, phildominguez commented on template.json
> +	  "usesPerScene": null
This has tabs again and actionType should be "free" I think

2023-10-17 03:18 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
>    async powerUpdate(power, dropFunc) {
```suggestion
  */
  async powerUpdate(power, dropFunc) {
```

2023-10-17 03:18 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +          buttons: {
```suggestion
          }),
          buttons: {
```

2023-10-17 03:18 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +    } else if (classFeature && classFeature.system.uses.value >= power.system.powerCost){
```suggestion
      ).render(true);
    } else if (classFeature && classFeature.system.uses.value >= power.system.powerCost){
```

2023-10-17 03:18 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +    if ((options[power.name].value > options[power.name].max) || (classFeature && options[power.name].value > classFeature.system.uses.value)) {
```suggestion
  * Handle the spending of power for a power activated
  * @param {Power} power The power
  * @param {ClassFeature} classFeature  The classFeature that is tied to the power
  */
  powerCountUpdate (options, power, classFeature) {
    if ((options[power.name].value > options[power.name].max) || (classFeature && options[power.name].value > classFeature.system.uses.value)) {
```

2023-10-17 03:18 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
>        } else if (rollType == 'classFeature') {
```suggestion
        await this._pwHandler.powerCost(item);
      } else if (rollType == 'classFeature') {
```

2023-10-17 03:18 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +  * @param {Power} power The power
```suggestion
      classFeature.update({ ["system.uses.value"]: Math.max(0, classFeature.system.uses.value - power.system.powerCost) });
    } else {
      ui.notifications.error(game.i18n.localize('E20.PowerOverSpent'));
      return;
    }
  }

  /**
  * Handle the spending of power for a power activated
  * @param {Power} power The power
```

2023-10-17 22:39 UTC, phildominguez requested changes
Please do a pass for whitespace/indentation and comment blocks as well

2023-10-17 22:39 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +    } else if(classFeature) {
```suggestion
      ui.notifications.error(game.i18n.localize('E20.PowerOverSpent'));
    } else if (classFeature) {
```

2023-10-17 22:39 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +    }
```suggestion
      ui.notifications.error(game.i18n.localize('E20.PowerOverSpent'));
    }
```

2023-10-17 22:39 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +          }),
```suggestion
            maxPower: maxPower,
          }),
```

2023-10-17 22:39 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +  * @param {ClassFeature} classFeature  The classFeature that is tied to the power
Missing options param

2023-10-17 22:39 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +      ui.notifications.error(game.i18n.localize('E20.PowerOverSpent'));
![image](https://github.com/WookieeMatt/Essence20/assets/41161497/d0220aa3-a054-4b7f-927c-6af77a2f449d)

2023-10-17 23:09 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
> +      ui.notifications.error(game.i18n.localize('E20.PowerOverSpent'));
fixed

2023-10-17 23:11 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
> +  * @param {ClassFeature} classFeature  The classFeature that is tied to the power
fixed

2023-10-18 00:17 UTC, phildominguez approved these changes

2023-10-18 00:44 UTC, merged