Move Personal Power and Energon to System values
WookieeMatt/Essence20 pull request #537
Opened 2023-11-05 16:56 UTC by JFranklin3000

##### In this PR
- Moved personal Power and Energon to system variables
- Added Sorcerous Power as a system variable. 
- Migration for Personal Power and Energon added

##### Testing
- Create Transformer and validate energon migration on the actor
- Create Power Ranger and validate Personal Power Migration
- Validate casting cost is still working for powers

##### Next Change
-Remove Energon and Personal Power creation from actor.mjs
-Add Energon to AltMode Tab

2023-11-05 17:58 UTC, phildominguez requested changes

2023-11-05 17:58 UTC, phildominguez commented on template.json
> +        "power": {
If these are going to be grouped, I would go with plural `powers`

2023-11-05 17:58 UTC, phildominguez commented on templates/actor/parts/items/power/container.hbs
> +        :{{#if system.usesPer}}
How come?

2023-11-05 17:58 UTC, phildominguez commented on module/documents/actor.mjs
>      if (["giJoe", "pony", "powerRanger", "transformer"].includes(this.type)) {
```suggestion
    this._prepareSorcerousPower();

    if (["giJoe", "pony", "powerRanger", "transformer"].includes(this.type)) {
```

2023-11-05 17:58 UTC, phildominguez commented on module/migration.mjs
> +      console.log (itemToDelete);
```suggestion
```

2023-11-05 17:58 UTC, phildominguez commented on module/migration.mjs
> +        itemToDelete.delete();
Noticing a mix of deletes with and without `await`s. Just checking they're only being used when needed.

2023-11-05 17:58 UTC, phildominguez commented on module/sheet-handlers/perk-handler.mjs
>      }
```suggestion
      });
    }
```

2023-11-05 17:58 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +      if (actorItem.type == 'power' && actorItem.system.originalId == powerUuid) {
```suggestion
      if (actorItem.type == 'power' && actorItem.system.originalId == powerUuid) {
```

2023-11-05 17:58 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +    // }
Is this being fixed later?

2023-11-05 17:58 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
> +    } else if (powerType != "threat" && this._actor.system.power[powerType].value >= power.system.powerCost){
```suggestion
    } else if (powerType != "threat" && this._actor.system.power[powerType].value >= power.system.powerCost) {
```

2023-11-05 17:58 UTC, phildominguez commented on module/sheet-handlers/power-handler.mjs
>    * @param {ClassFeature} classFeature  The classFeature that is tied to the power
Update @param

2023-11-05 18:19 UTC, JFranklin3000 commented on templates/actor/parts/items/power/container.hbs
> +        :{{#if system.usesPer}}
So it only shows up on the NPC sheet. The character sheets in the book don't have that descriptor.

2023-11-05 18:21 UTC, JFranklin3000 commented on module/migration.mjs
> +        itemToDelete.delete();
That one was missing I added it.

2023-11-05 18:24 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
> +    // }
It is actually working but I need to add a way to turn off effects when they expire or the combat ends, before I consider it done.

2023-11-05 18:25 UTC, JFranklin3000 commented on module/sheet-handlers/power-handler.mjs
>    * @param {ClassFeature} classFeature  The classFeature that is tied to the power
updated.

2023-11-05 18:30 UTC, JFranklin3000 commented on template.json
> +        "power": {
changed.

2023-11-05 19:30 UTC, phildominguez commented on templates/actor/parts/items/power/container.hbs
> +        :{{#if system.usesPer}}
Makes sense, what about putting the `:` by itself on the line above? It just looks kinda funky right on an if-statement

2023-11-05 19:35 UTC, phildominguez requested changes

2023-11-05 19:35 UTC, phildominguez commented on templates/actor/parts/items/power/container.hbs
> +</div>
This file should just be for the item container. This stats-container should be in its own template, then added in pc-body.hbs. You can see a blank container on the NPC sheet, and making that change will fix this. Similar for altMode.

2023-11-06 00:17 UTC, phildominguez approved these changes

2023-11-06 00:21 UTC, merged