Changes for Power Chat and Energon
WookieeMatt/Essence20 pull request #540
Opened 2023-11-09 04:12 UTC by JFranklin3000

##### In this PR
- Added Different Types of Energon
- Added Chips to Powers and Chat cards
- Added Energon reset to Sleep button

##### Testing
- Validate Sleep restore
- Validate Chips on Powers

2023-11-09 18:47 UTC, phildominguez requested changes

2023-11-09 18:47 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    }
I would make a `const energon = this.actor.system.energon.normal` at the start to make this more readable

2023-11-09 18:47 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    if ((this.actor.system.energon.normal.value + maxEnergonRestore) > this.actor.system.energon.normal.max) {
```suggestion
    let energonRestore = 0;

    if ((this.actor.system.energon.normal.value + maxEnergonRestore) > this.actor.system.energon.normal.max) {
```

2023-11-09 18:47 UTC, phildominguez commented on templates/actor/parts/items/power/details.hbs
> +  {{#if item.system.canActivate}}
Should this be `#if item.system.powerCost`? A default-created power currently shows this:
![image](https://github.com/WookieeMatt/Essence20/assets/41161497/11c32bb2-d5bb-47d9-836e-10ad6a44b82b)

2023-11-09 23:24 UTC, JFranklin3000 commented on templates/actor/parts/items/power/details.hbs
> +  {{#if item.system.canActivate}}
I idea was you wouldn't have a power that can activate, that doesn't have a power cost, but this is safer.

2023-11-09 23:25 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +    }
pushing change.

2023-11-10 01:43 UTC, phildominguez approved these changes

2023-11-10 01:50 UTC, merged