Added Focus and Role Items to the Game
WookieeMatt/Essence20 pull request #558
Opened 2023-11-17 23:58 UTC by JFranklin3000

##### In this PR
- Added Focus.hbs
- Added role.hbs
- Added initial handlers for roles and advancement

##### Testing
- Validate sheet looks like we want it to.

2023-11-18 17:18 UTC, phildominguez requested changes

2023-11-18 17:18 UTC, phildominguez commented on module/helpers/config.mjs
> +  computerized: "E20.ArmorComputerized",
```suggestion
  computerized: "E20.ArmorsComputerized",
```

2023-11-18 17:18 UTC, phildominguez commented on module/helpers/config.mjs
> +  level1optional: "E20.Level1Additional",
`E20.Level1Additional` not defined

2023-11-18 17:18 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    html.find('.level').change(this._advHandler.onLevelChange(this.actor));
I'd move this up with the other handler stuff, like under transform or something. Don't forget the comment!

2023-11-18 17:18 UTC, phildominguez commented on module/sheet-handlers/advancement-handler.mjs
> +  /**
```suggestion
export class AdvancementHandler {
  /**
```

2023-11-18 17:18 UTC, phildominguez commented on module/sheet-handlers/advancement-handler.mjs
> +}
```suggestion
  }
}
```

2023-11-18 17:18 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +  /**
```suggestion
export class RoleHandler {
  /**
```

2023-11-18 17:18 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +}
```suggestion
  }
}
```

2023-11-18 17:18 UTC, phildominguez commented on module/helpers/config.mjs
> +//Game Version
```suggestion
// Game Version
```

2023-11-18 17:32 UTC, JFranklin3000 commented on module/helpers/config.mjs
> +E20.essenceLevels = {
I was thinking of it as the level you got the essence boost initially, but yea actorLevels or playerLevels would be better

2023-11-18 17:34 UTC, JFranklin3000 commented on templates/item/sheets/role.hbs
> +        {{#ifNotEquals system.version 'transformers'}}
Not saying you are wrong, but the ifNotEquals for myLittlePony is removing most of the options. where the transformers one is removing just that one field. but I can take a look.

2023-11-19 13:57 UTC, phildominguez commented on templates/item/sheets/role.hbs
> +        {{#ifNotEquals system.version 'transformers'}}
Ah okay, np

2023-11-19 16:52 UTC, JFranklin3000 commented on templates/item/sheets/focus.hbs
> +    {{!-- Focus Role --}}
fixed

2023-11-19 16:55 UTC, JFranklin3000 commented on module/helpers/config.mjs
> +  level1optional: "E20.Level1Additional",
fixed

2023-11-19 16:57 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +    html.find('.level').change(this._advHandler.onLevelChange(this.actor));
fixed

2023-11-19 23:29 UTC, phildominguez requested changes

2023-11-19 23:29 UTC, phildominguez commented on template.json
> +      "perks": {
Should this be perkIds?

2023-11-19 23:29 UTC, phildominguez commented on template.json
> +        "trained":""
Should these be lists?

2023-11-19 23:29 UTC, phildominguez commented on template.json
> +        "trained":""
Should these be lists?

2023-11-20 13:48 UTC, JFranklin3000 commented on template.json
> +      "perks": {
I would say no in this case right now it is an array of levels.

2023-11-20 13:48 UTC, JFranklin3000 commented on template.json
> +        "trained":""
yes

2023-11-20 13:48 UTC, JFranklin3000 commented on template.json
> +        "trained":""
yes

2023-11-20 17:37 UTC, phildominguez requested changes

2023-11-20 17:37 UTC, phildominguez commented on template.json
> +      "essences": {
Maybe `essenceLevels`?

2023-11-20 17:37 UTC, phildominguez commented on template.json
> +        "strength":  ""
Lists I think

2023-11-20 17:37 UTC, phildominguez commented on template.json
> +          "levels": "",
This name sounds like it should be a list?

2023-11-20 17:37 UTC, phildominguez commented on template.json
> +        "trained":[]
```suggestion
        "trained": []
```

2023-11-21 02:02 UTC, JFranklin3000 commented on template.json
> +        "trained":[]
fixed

2023-11-21 02:02 UTC, JFranklin3000 commented on template.json
> +          "levels": "",
fixed

2023-11-21 02:02 UTC, JFranklin3000 commented on template.json
> +        "strength":  ""
fixed

2023-11-21 02:02 UTC, JFranklin3000 commented on template.json
> +      "essences": {
changed

2023-11-21 14:04 UTC, phildominguez approved these changes

2023-11-21 14:28 UTC, merged