Draft: Update to add Role Perks to Roles
WookieeMatt/Essence20 pull request #562
Opened 2023-11-25 18:58 UTC by JFranklin3000

##### In this PR
- Contains new way of adding items to items. 

##### Testing
-

2023-12-27 23:34 UTC, phildominguez requested changes

2023-12-27 23:34 UTC, phildominguez commented on templates/item/sheets/focus.hbs
> +      {{> "systems/essence20/templates/item/parts/role-perk-drop.hbs" className="rolePerk" label='E20.RolePerk' items=system.items}}
![image](https://github.com/WookieeMatt/Essence20/assets/41161497/faa69a78-25af-4ef9-a15e-9969128824fc)

Also fix indent

2023-12-27 23:34 UTC, phildominguez commented on template.json
> +      "items": {},
Should have `items` from `parentItem` template already

2023-12-27 23:34 UTC, phildominguez commented on template.json
> +      "items": {},
Should have `items` from `parentItem` template already

2023-12-27 23:34 UTC, phildominguez commented on templates/item/parts/role-perk-drop.hbs
> +            <input type="number" class="level" value="{{item.level}}" name="system.items.{{@key}}.level" />
I think we should add `placeholder="Level"`, otherwise it's tough to tell what the input is for

2023-12-27 23:34 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +    // html.find('.level').change(this._onItemSort.bind(this));
Remove?

2023-12-27 23:34 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +    // this._onItemSort();
Remove?

2023-12-27 23:34 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  _onItemSort() {
Not being used...

2023-12-28 01:18 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  _onItemSort() {
Removed

2023-12-28 01:18 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    // this._onItemSort();
Removed

2023-12-28 01:18 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    // html.find('.level').change(this._onItemSort.bind(this));
Removed

2023-12-28 01:20 UTC, JFranklin3000 commented on template.json
> +      "items": {},
removed

2023-12-28 01:20 UTC, JFranklin3000 commented on template.json
> +      "items": {},
removed

2023-12-28 01:22 UTC, JFranklin3000 commented on templates/item/sheets/focus.hbs
> +      {{> "systems/essence20/templates/item/parts/role-perk-drop.hbs" className="rolePerk" label='E20.RolePerk' items=system.items}}
fixed.

2023-12-28 01:30 UTC, JFranklin3000 commented on templates/item/parts/role-perk-drop.hbs
> +            <input type="number" class="level" value="{{item.level}}" name="system.items.{{@key}}.level" />
Added.

2023-12-28 01:49 UTC, phildominguez approved these changes

2023-12-28 01:50 UTC, merged