Draft: Migrate to new data structure
WookieeMatt/Essence20 pull request #564
Opened 2023-12-01 02:44 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- Influence Drop Changes
- Origin Drop Changes
- Armor Drop Changes
- Weapon Drop Changes

##### Testing
-

2023-12-01 21:59 UTC, phildominguez requested changes

2023-12-03 00:36 UTC, JFranklin3000 commented on template.json
> +      "items": {},
changed

2023-12-03 00:40 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +export async function createItemCopies(items, owner, type, parentItem) {
Updated

2023-12-03 00:40 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +  if (items) {
removed

2023-12-03 00:42 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
>          if (droppedItem.system.type == "armor") {
Can you do multiple variables in a case?

2023-12-03 00:44 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
>          if (droppedItem.system.type == "armor") {
fixed

2023-12-03 00:48 UTC, JFranklin3000 commented on module/sheet-handlers/background-handler.mjs
> +      }
This is definitely one of the ones I am looking at turning into a helper.

2023-12-04 00:29 UTC, phildominguez requested changes

2023-12-04 00:29 UTC, phildominguez commented on module/helpers/utils.mjs
> +    } else if (droppedItem.type == "weaponEffect") {
```suggestion
      addItemIfUnique(droppedItem, targetItem, entry);
    } else if (droppedItem.type == "weaponEffect") {
```

2023-12-04 00:29 UTC, phildominguez commented on module/helpers/utils.mjs
> +export function attachedItemDelete(item, actor) {
```suggestion
export function attachedItemDelete(item, actor) {
```
Also move to attachmentHandler?

2023-12-04 00:29 UTC, phildominguez commented on module/sheet-handlers/attachment-handler.mjs
> +//   }
Delete?

2023-12-04 00:29 UTC, phildominguez commented on module/sheet-handlers/attachment-handler.mjs
> +  async attachItem(droppedItem) {
Update comment block

2023-12-04 00:29 UTC, phildominguez commented on module/sheet-handlers/attachment-handler.mjs
> +  async _attachItem(targetItem, droppedItem) {
Update comment block

2023-12-04 00:29 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
> +  // searchCompendium,
Delete `//`s?

2023-12-04 00:29 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
```suggestion
```

2023-12-04 00:29 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
> +  async _chooseHangUp(influence) {
Update comment block

2023-12-04 00:29 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
> +  async _hangUpSelect(influence, options) {
Update comment block

2023-12-04 00:29 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
> +    // let hangUpToCreate = null;
```suggestion
```

2023-12-04 04:24 UTC, phildominguez requested changes

2023-12-04 04:24 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +        // i.upgrades = this._populateChildItems(i.system.upgradeIds);
```suggestion
```

2023-12-04 04:24 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +      }
```suggestion
      const itemId = element.closest('.item').dataset.itemId || element.closest('.item').dataset.parentId;
```

2023-12-04 04:24 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +        return item.roll(dataset);
If item is null or something I think this would throw an error

2023-12-04 04:24 UTC, phildominguez commented on module/documents/item.mjs
> +  async roll(dataset, keyId) {
`childKey`?

2023-12-04 04:24 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +        if (keyId) {
Doesn't this mean every item that is rollable has to be a child item?

2023-12-04 04:24 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
>      }
```suggestion
      li.slideUp(200, () => this.render(false));
    }
```

2023-12-04 04:24 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    //   return await this._onDropWeapon(event, data);
```suggestion
```

2023-12-04 04:24 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +    // const itemType = context.item.type;
```suggestion
```

2023-12-04 04:24 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  // }
Delete?

2023-12-04 04:24 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  async _onObjectDelete(cssClass, event) {
Should this be made into a helper and used for `_onItemDelete()`?

2023-12-04 04:24 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +  // }
Delete?

2023-12-04 16:10 UTC, JFranklin3000 commented on module/documents/item.mjs
> +    super.prepareDerivedData;
I think so too.

2023-12-04 16:15 UTC, JFranklin3000 commented on module/helpers/utils.mjs
Saving for the migration, but yes this is up for delete/move to the migration.mjs

2023-12-04 16:15 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +// }
same

2023-12-04 19:40 UTC, phildominguez requested changes

2023-12-04 19:40 UTC, phildominguez commented on module/documents/item.mjs
> +        }
```suggestion
      for (const trait of traits) {
        if (!traitsFlag.includes(trait)) {
          traitsFlag.push(trait);
        }
      }
```

2023-12-04 19:40 UTC, phildominguez commented on module/documents/item.mjs
> +    let upgradeTraits = [];
To me this sounds like a list of traits for one upgrade, but it's all the traits for all upgrades. What about `traitsForUpgrades`?

2023-12-04 19:40 UTC, phildominguez commented on module/documents/item.mjs
> +        this.system.totalTraits = traitsFlag;
`totalTraits` makes me think it's a numeric value, what about `allUpgradeTraits` or similar?

2023-12-04 19:40 UTC, phildominguez commented on template.json
> +      "totalTraits": [],
These are derived, yeah? Idt they should be in here, because they're being set in `prepareDerivedData()`.

2023-12-04 19:55 UTC, JFranklin3000 commented on module/documents/item.mjs
> +        }
I tried that and it throws errors in the console that traits aren't itterable if traits is undefined.

2023-12-04 20:02 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  async _onObjectDelete(cssClass, event) {
Ok I think I see what you are saying make it a helper and replace the if(parentitem){ info that would make sense.

2023-12-04 20:05 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +        if (keyId) {
yep the else is on the wrong if.

2023-12-04 21:48 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +        // i.upgrades = this._populateChildItems(i.system.upgradeIds);
removed

2023-12-04 21:48 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    // const itemType = context.item.type;
removed

2023-12-05 14:00 UTC, JFranklin3000 commented on module/documents/item.mjs
> +    let traitsFlag = this.system.traits;
fixed

2023-12-05 14:00 UTC, JFranklin3000 commented on module/documents/item.mjs
> +    if (this.type == 'armor') {
fixed

2023-12-05 14:00 UTC, JFranklin3000 commented on module/documents/item.mjs
> +        if (item.type == 'upgrade' && item.subtype == 'armor'){
fixed

2023-12-05 14:04 UTC, JFranklin3000 commented on module/documents/item.mjs
> +  async roll(dataset, keyId) {
I went with childKey, I can still see if there is a way to get it into dataset.

2023-12-05 14:05 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +  let id= "";
fixed

2023-12-05 14:06 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +export function setEntry(droppedItem,targetItem){
Nope it is also used in item-sheet.

2023-12-05 14:08 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +export function attachedItemDelete(item, actor) {
I left it here because it is also used in background handler and the actor-sheet.

2023-12-05 14:12 UTC, JFranklin3000 commented on module/sheet-handlers/attachment-handler.mjs
> +  async attachItem(droppedItem) {
fixed

2023-12-05 14:13 UTC, JFranklin3000 commented on module/sheet-handlers/attachment-handler.mjs
> +  async _attachItem(targetItem, droppedItem) {
fixed

2023-12-05 14:13 UTC, JFranklin3000 commented on module/sheet-handlers/background-handler.mjs
> +  // searchCompendium,
removed

2023-12-05 14:15 UTC, JFranklin3000 commented on module/sheet-handlers/background-handler.mjs
removed

2023-12-05 14:17 UTC, JFranklin3000 commented on module/sheet-handlers/background-handler.mjs
> +  async _hangUpSelect(influence, options) {
updated

2023-12-05 14:18 UTC, JFranklin3000 commented on module/sheet-handlers/background-handler.mjs
> +    // let hangUpToCreate = null;
removed

2023-12-05 14:23 UTC, JFranklin3000 commented on module/documents/item.mjs
> +    let upgradeTraits = [];
I went with itemAndUpgradeTraits because it starts with the traits from the item.

2023-12-05 16:41 UTC, JFranklin3000 commented on module/documents/item.mjs
> +        this.system.totalTraits = traitsFlag;
replaced with itemAndUpgradeTraits

2023-12-06 04:58 UTC, phildominguez requested changes

2023-12-07 01:58 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +export function attachedItemDelete(item, actor) {
Updated

2023-12-07 01:58 UTC, JFranklin3000 commented on module/sheet-handlers/background-handler.mjs
removed

2023-12-07 01:58 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +      break;
I removed both, I think that works.

2023-12-07 01:59 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +  for (const [,deletedItem] of Object.entries(itemDelete.system.items)) {
updated

2023-12-07 02:00 UTC, JFranklin3000 commented on module/documents/item.mjs
> +    if (this.type == 'armor') {
changed

2023-12-07 02:02 UTC, JFranklin3000 commented on module/documents/item.mjs
> +  _prepareTraits() {
Commented

2023-12-07 02:05 UTC, JFranklin3000 commented on module/documents/item.mjs
> +  _prepareArmorBonuses() {
Added

2023-12-07 02:07 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> -
added

2023-12-07 02:07 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +* @private
removed

2023-12-07 02:13 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
>        const item = this.actor.items.get(itemId);
changed

2023-12-07 02:16 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +export function setEntry(droppedItem, targetItem){
attachItem is already used in the attachment handler so that could be messy. What about setItemData?

2023-12-08 01:31 UTC, phildominguez commented on module/helpers/utils.mjs
> +      break;
Yeah you want to break no matter what and that's done on line 423

2023-12-08 01:38 UTC, phildominguez commented on module/helpers/utils.mjs
> +export function setEntry(droppedItem, targetItem){
Too vague imo, it doesn't convey it's attaching an item to an item, or dropping an item into an item

2023-12-08 02:36 UTC, JFranklin3000 commented on module/documents/item.mjs
> +  * prepares the item and any upgrade traits currently on the item
fixed

2023-12-08 02:37 UTC, JFranklin3000 commented on module/documents/item.mjs
> +  * prepares the combined armor bonuses from the armor and any upgrades
fixed

2023-12-08 02:37 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +  for (const [,attachment] of Object.entries(itemDelete.system.items)) {
fixed

2023-12-14 22:08 UTC, JFranklin3000 commented on module/helpers/utils.mjs
removed

2023-12-14 22:08 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +// }
removed

2023-12-14 22:09 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +// }
removed

2023-12-14 22:09 UTC, JFranklin3000 commented on module/sheet-handlers/attachment-handler.mjs
> +//   }
removed

2023-12-14 22:10 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  // }
removed

2023-12-14 22:10 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +  // }
removed

2023-12-14 22:22 UTC, JFranklin3000 commented on module/documents/item.mjs
> +  async roll(dataset, keyId) {
It is not in dataset it is in the event and we pull it from there, but it isn't in the dataset we are sending. 


![image](https://github.com/WookieeMatt/Essence20/assets/71140111/3b3644d9-6642-42f9-a62f-08c5cf7a57bb)

2023-12-15 00:05 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +  const itemDelete = actor.items.get(item._id);
It is not. :D

2023-12-16 00:02 UTC, phildominguez requested changes

2023-12-16 00:02 UTC, phildominguez commented on module/migration.mjs
> +        const pathPrefix = "system.items";
We can define this once earlier in the method instead of duplicating it

2023-12-16 00:13 UTC, JFranklin3000 commented on module/documents/item.mjs
> +  async roll(dataset, childKey) {
fixed

2023-12-16 00:13 UTC, JFranklin3000 commented on module/documents/item.mjs
> +  * Extends the preparedDerivedData model to add system specific data/.
fixed

2023-12-16 00:14 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> + * @param {Item} items The item(s) to copy
fixed

2023-12-16 00:14 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +      if(parentItem) {
fixed

2023-12-16 00:15 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +* @param {object} entry The Object being created.
correct, this function calls the creating function. And updated.

2023-12-16 00:18 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +export function setEntryAndAddItem(droppedItem, targetItem){
fixed

2023-12-16 00:19 UTC, JFranklin3000 commented on module/migration.mjs
> +  // game.settings.set("essence20", "systemMigrationVersion", game.system.version);
fixed

2023-12-16 00:19 UTC, JFranklin3000 commented on module/migration.mjs
>  /**
fixed

2023-12-16 00:20 UTC, JFranklin3000 commented on module/migration.mjs
> +export function randomId(length) {
I tried that initially and it broke. I was trying to do an import, but maybe there is another way to do it...

2023-12-16 00:22 UTC, JFranklin3000 commented on module/migration.mjs
> +        let originalArmorBonus = 0;
I think when I wrote it initially I thought I was going to need it outside of the if. So yea you are probably right here. 
Fixed

2023-12-16 00:23 UTC, JFranklin3000 commented on module/migration.mjs
>    } else if (item.type == "perk") {
fixed

2023-12-16 00:24 UTC, JFranklin3000 commented on module/migration.mjs
> +  }else if (item.type == 'weapon') {
fixed

2023-12-16 00:29 UTC, JFranklin3000 commented on module/migration.mjs
> +    if (item.system.upgradeIds) {
removed.

2023-12-16 00:36 UTC, JFranklin3000 commented on module/migration.mjs
> +        const pathPrefix = "system.items";
Good idea moved to the top of the function.

2023-12-16 00:42 UTC, JFranklin3000 commented on module/migration.mjs
> +    if (item.system.upgradeIds) {
![image](https://github.com/WookieeMatt/Essence20/assets/71140111/9d267296-beb6-4924-ac6d-43a543d455ac)
With that removed we get this a bunch.

2023-12-16 01:11 UTC, phildominguez commented on module/migration.mjs
> +export function randomId(length) {
Like it couldn't find the method?

2023-12-16 01:14 UTC, phildominguez commented on module/migration.mjs
> +    if (item.system.upgradeIds) {
How is it possible for an armor not to have `upgradeIds`? It was in the old template, defaulted to `[]`...

2023-12-16 01:17 UTC, JFranklin3000 commented on module/migration.mjs
> +    if (item.system.upgradeIds) {
Probably anything that is built new doesn't have it, and if the migration runs in the future after we remove it from the template it will show errors in the console.

2023-12-16 01:18 UTC, JFranklin3000 commented on module/migration.mjs
> +export function randomId(length) {
so I did an import at the beginning of the file and it made all of the js not work. I wonder if it can just find it from utils anyway.

2023-12-16 01:30 UTC, JFranklin3000 commented on module/migration.mjs
> +export function randomId(length) {
Found the issue.

2023-12-16 01:43 UTC, JFranklin3000 commented on module/migration.mjs
> +        } while (item.system.items[id]);
Helper Created

2023-12-16 01:56 UTC, JFranklin3000 commented on module/migration.mjs
> +        }
Helper created

2023-12-16 18:31 UTC, phildominguez requested changes

2023-12-16 18:31 UTC, phildominguez commented on module/sheet-handlers/attachment-handler.mjs
> +    console.log(droppedItem);
```suggestion

```

2023-12-16 18:31 UTC, phildominguez commented on module/sheet-handlers/attachment-handler.mjs
> +  */
Missing dropFunc {Function} in comment block

2023-12-16 18:31 UTC, phildominguez commented on module/migration.mjs
> +  attachedItem = await fromUuid(`Item.${perkId}`);
```suggestion
  let attachedItem = await fromUuid(`Item.${perkId}`);
```
Empty strings are a good default for string vars, but not for non-strings. `fromUuid()` returns `null` if not found, so that should work fine.

2023-12-16 18:31 UTC, phildominguez commented on module/helpers/utils.mjs
> +* @param {Array} items The items already on the item.
```suggestion
* @param {Object} items The items keyed by IDs
```
This method doesn't really need the context that it's being used for attachments

2023-12-16 18:31 UTC, phildominguez commented on module/documents/item.mjs
> +   * @param {Key} childKey The key of the item attached to another item
```suggestion
   * @param {String} childKey The key of the item attached to another item
```
`Key` is not a type :)

2023-12-16 18:31 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    let item = "";
As mentioned elsewhere, `null` should be the default for an item. Here though, setting this here isn't useful since there is no `if (item)` check, it just continues with the delete. Maybe add a check and notify/return if item is `null`?

2023-12-16 18:31 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    if (itemId) {
```suggestion
    const parentItem = this.actor.items.get(parentId);

    if (itemId) {
```

2023-12-16 18:31 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +      for (const attachedItem of this.actor.items) {
I think a comment above this `for` would be good since it's not immediately obvious what's happening

2023-12-16 18:31 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    } else {
```suggestion
      li.slideUp(200, () => this.render(false));
    } else {
```

2023-12-16 18:31 UTC, phildominguez commented on module/migration.mjs
> +        attachedItem = await getItem(perkId);
I think this needs a `const`? And for others below

2023-12-16 18:31 UTC, phildominguez commented on module/migration.mjs
> +          updateData[`${pathPrefix}.${id}`] = entry;
```suggestion
          };
          const id = createId(item.system.items);
          updateData[`${pathPrefix}.${id}`] = entry;
```

2023-12-16 18:31 UTC, phildominguez commented on module/migration.mjs
> +          updateData[`${pathPrefix}.${id}`] = entry;
```suggestion
          };
          const id = createId(item.system.items);
          updateData[`${pathPrefix}.${id}`] = entry;
```

2023-12-16 18:31 UTC, phildominguez commented on module/migration.mjs
> +          updateData[`${pathPrefix}.${id}`] = entry;
```suggestion
        if (attachedItem) {
          const entry = {
            uuid: attachedItem.uuid,
            img: attachedItem.img,
            name: attachedItem.name,
            type: attachedItem.type,
          };
          const id = createId(item.system.items);
          updateData[`${pathPrefix}.${id}`] = entry;
```

2023-12-16 18:31 UTC, phildominguez commented on module/migration.mjs
> +          updateData[`${pathPrefix}.${id}`] = entry;
```suggestion
        if (attachedItem) {
          const entry = {
            uuid: attachedItem.uuid,
            img: attachedItem.img,
            name: attachedItem.name,
            type: attachedItem.type,
          };
          const id = createId(item.system.items);
          updateData[`${pathPrefix}.${id}`] = entry;
```

2023-12-16 18:31 UTC, phildominguez commented on module/migration.mjs
> +          updateData[`${pathPrefix}.${id}`] = entry;
```suggestion
        if (attachedItem) {
          attachedItem.setFlag('core', 'parentId', item.uuid);

          const entry = {
            uuid: attachedItem.uuid,
            img: attachedItem.img,
            name: attachedItem.name,
            type: attachedItem.type,
            availability: attachedItem.availability,
            benefit: attachedItem.benefit,
            description: attachedItem.description,
            prerequisite: attachedItem.prerequisite,
            source: attachedItem.source,
            subtype: attachedItem.type,
            traits: attachedItem.traits,
          };
          const id = createId(item.system.items);
          updateData[`${pathPrefix}.${id}`] = entry;
```

2023-12-16 18:31 UTC, phildominguez commented on module/migration.mjs
> +          updateData[`${pathPrefix}.${id}`] = entry;
```suggestion
          };
          const id = createId(item.system.items);
          updateData[`${pathPrefix}.${id}`] = entry;
```

2023-12-26 20:16 UTC, JFranklin3000 commented on module/sheet-handlers/attachment-handler.mjs
> +  */
fixed

2023-12-26 20:16 UTC, JFranklin3000 commented on module/sheet-handlers/attachment-handler.mjs
> +    console.log(droppedItem);
removed

2023-12-26 20:17 UTC, JFranklin3000 commented on module/migration.mjs
> +  attachedItem = await fromUuid(`Item.${perkId}`);
changed

2023-12-26 20:18 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +* @param {Array} items The items already on the item.
changed

2023-12-26 20:18 UTC, JFranklin3000 commented on module/documents/item.mjs
> +   * @param {Key} childKey The key of the item attached to another item
changed

2023-12-26 20:23 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +    let item = "";
This is a bit of a weird case item can be null for quite awhile depending on if there is a parent item or not. I could do an if (item) above the if (parentItem) should we initiate with let item = null?

2023-12-26 20:24 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +      for (const attachedItem of this.actor.items) {
Added

2023-12-26 20:26 UTC, JFranklin3000 commented on module/migration.mjs
> +        attachedItem = await getItem(perkId);
fixed

2023-12-26 20:26 UTC, JFranklin3000 commented on module/migration.mjs
> +          updateData[`${pathPrefix}.${id}`] = entry;
fixed

2023-12-26 20:26 UTC, JFranklin3000 commented on module/migration.mjs
> +          updateData[`${pathPrefix}.${id}`] = entry;
fixed

2023-12-26 20:27 UTC, JFranklin3000 commented on module/migration.mjs
> +          updateData[`${pathPrefix}.${id}`] = entry;
fixed

2023-12-26 20:27 UTC, JFranklin3000 commented on module/migration.mjs
> +          updateData[`${pathPrefix}.${id}`] = entry;
fixed

2023-12-26 20:27 UTC, JFranklin3000 commented on module/migration.mjs
> +          updateData[`${pathPrefix}.${id}`] = entry;
fixed

2023-12-26 20:27 UTC, JFranklin3000 commented on module/migration.mjs
> +          updateData[`${pathPrefix}.${id}`] = entry;
fixed

2023-12-27 20:42 UTC, phildominguez approved these changes

2023-12-27 20:47 UTC, merged