Draft: Test we have an error that I am trying to find on the ifEquals function in handlebars.
WookieeMatt/Essence20 pull request #567
Opened 2023-12-30 00:02 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- 

##### Testing
-

2024-01-13 16:50 UTC, phildominguez requested changes

2024-01-13 16:50 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +        ui.notifications.error(game.i18n.format(game.i18n.localize('E20.RoleMulitpleError')));
```suggestion
        ui.notifications.error(game.i18n.format(game.i18n.localize('E20.RoleMultipleError')));
```

2024-01-13 17:45 UTC, JFranklin3000 commented on module/sheet-handlers/role-handler.mjs
> +        ui.notifications.error(game.i18n.format(game.i18n.localize('E20.RoleMulitpleError')));
fixed

2024-01-13 18:27 UTC, phildominguez requested changes

2024-01-13 18:27 UTC, phildominguez commented on templates/actor/parts/items/role.hbs
> +    <input type="text" value="{{localize 'E20.RoleDrop'}}" readonly/>
```suggestion
    <input class="no-unlock" type="text" value="{{localize 'E20.RoleDrop'}}" readonly />
```

2024-01-13 23:52 UTC, phildominguez requested changes

2024-01-13 23:52 UTC, phildominguez commented on module/helpers/utils.mjs
> +        }
I think the level-checking responsibility should be done elsewhere, before this method is called. It just seems outside the scope of what this method should handle. Thoughts?

2024-01-13 23:52 UTC, phildominguez commented on module/helpers/utils.mjs
> +      }else {
```suggestion
        }
      } else {
```

2024-01-13 23:52 UTC, phildominguez commented on module/helpers/utils.mjs
> +          }
Similar here, can we do this level-related logic before this method is called?

2024-01-13 23:52 UTC, phildominguez commented on module/sheet-handlers/advancement-handler.mjs
> +   * @param {Object} actor The actor whose level has changed
```suggestion
   * @param {Actor} actor The actor whose level has changed
```

2024-01-13 23:52 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +  // }
```suggestion
```

2024-01-13 23:52 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +   * @param {Object} role The role item that is being dropped on the actor
```suggestion
   * @param {Role} role The role item that is being dropped on the actor
```

2024-01-13 23:52 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +
```suggestion
```

2024-01-13 23:52 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +      if (actorItem.type == 'role') {
We can use `getItemsOfType()` from utils to check this

2024-01-13 23:52 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +    this._actor.setFlag('essence20', 'lastLevelUp', this._actor.system.level);
I think "up" is throwing me off since the previous level isn't guaranteed to have been a level up. What about just `previousLevel`?

2024-01-13 23:52 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +        }
I'd make a helper for this since it's similar to below, and in `onRoleDelete()` and `onLeveLChange()`

2024-01-13 23:52 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +      const newPersonalPowerMax = parseInt(this._actor.system.powers.personal.max) + parseInt(newRole.system.powers.personal.starting) + parseInt(newRole.system.powers.personal.increase * totalIncrea
```suggestion
      const newPersonalPowerMax = parseInt(this._actor.system.powers.personal.max)
        + parseInt(newRole.system.powers.personal.starting)
        + parseInt(newRole.system.powers.personal.increase * totalIncrease);
```

2024-01-13 23:52 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +
```suggestion
```

2024-01-13 23:52 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +  async onRoleDelete(role){
```suggestion
   * @param {Role} role The role item that is being deleted on the actor
   */
  async onRoleDelete(role){
```

2024-01-13 23:52 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +      }
```suggestion
      const essenceValue = Math.max(0, this._actor.system.essences[essence] - totalDecrease);
      const essenceString = `system.essences.${essence}`;
```
Similar for below

2024-01-13 23:52 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +  async _onChangeInput(event) {
Comment block

2024-01-13 23:52 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +    const roles = []; //Used by PCs
```suggestion
    const roles = []; // Used by PCs
```
🙂

2024-01-13 23:52 UTC, phildominguez commented on module/sheet-handlers/advancement-handler.mjs
> +        if (newLevel > lastLevelUp) {
```suggestion
    if (lastLevelUp && newLevel > lastLevelUp) {
```

2024-01-14 17:47 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +        }
As discussed left in, but set lastLevelUp to Null

2024-01-14 17:47 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +          }
As discussed left in, but set lastLevelUp to Null

2024-01-14 18:27 UTC, JFranklin3000 commented on module/sheet-handlers/role-handler.mjs
> +      if (actorItem.type == 'role') {
Changed

2024-01-14 18:59 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +  async _onChangeInput(event) {
fixed

2024-01-14 19:03 UTC, JFranklin3000 commented on module/sheet-handlers/role-handler.mjs
> +    this._actor.setFlag('essence20', 'lastLevelUp', this._actor.system.level);
Sounds good.

2024-01-16 23:19 UTC, JFranklin3000 commented on module/sheet-handlers/role-handler.mjs
> +        }
helper created.

2024-01-17 01:43 UTC, phildominguez requested changes

2024-01-17 01:43 UTC, phildominguez commented on module/helpers/utils.mjs
> +export async function createItemCopies(items, owner, type, parentItem, previousLevel=null) {
```
/**
 * Creates copies of Items for given IDs
 * @param {Object[]} items The item entries to copy
 * @param {Actor} owner The items' owner
 * @param {String} type The type of items to drop
 * @param {Item} parentItem The items' parent item
 * @param {Number} lastProcessedLevel The flag for the last time the actor changed level
 */
export async function createItemCopies(items, owner, type, parentItem, lastProcessedLevel=null) {
  for (const [key, item] of Object.entries(items)) {
    if (item.type == type) {
      const createNewItem =
        parentItem.type != "role"
        || item.level <= owner.system.level && (!lastProcessedLevel || (item.level > lastProcessedLevel));

      if (createNewItem) {
        const itemToCreate = await fromUuid(item.uuid);
        const newItem = await Item.create(itemToCreate, { parent: owner });
        newItem.setFlag('core', 'sourceId', item.uuid);
        newItem.setFlag('essence20', 'collectionId', key);
        newItem.setFlag('essence20', 'parentId', parentItem._id);
      }
    }
  }
}
```
Untested!

2024-01-17 02:19 UTC, phildominguez requested changes

2024-01-17 02:19 UTC, phildominguez commented on module/helpers/utils.mjs
> +
```suggestion
export async function roleValueChange(actor, essenceLevels, lastProcessedLevel=null) {
  let totalChange = 0;

  for (const essenceLevel in essenceLevels) {
    const level = essenceLevel.replace(/[^0-9]/g, '');
    const increaseChange =
      level <= actor.system.level
      && (!lastProcessedLevel || level > lastProcessedLevel)
    totalChange += increaseChange ? 1 : 0;
  }

  return totalChange;
}
```
Untested! Needs a comment block as well.

2024-01-18 01:52 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +
changed

2024-01-18 01:52 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +export async function createItemCopies(items, owner, type, parentItem, previousLevel=null) {
chnaged

2024-01-18 01:59 UTC, phildominguez requested changes

2024-01-18 01:59 UTC, phildominguez commented on module/helpers/utils.mjs
> +            }
```suggestion
          if (!previousLevel
            || (attachment.level > actor.system.level && attachment.level <= previousLevel)) {
            actorItem.delete();
          }
```

2024-01-18 01:59 UTC, phildominguez commented on module/helpers/utils.mjs
> + * @returns {Integer} totalChange The number of level changes.
We've been using `{Number}` instead of `{Integer}`. Idk where it came from, but let's make it consistent.

2024-01-18 01:59 UTC, phildominguez commented on module/helpers/utils.mjs
> +
```suggestion
```

2024-01-18 23:56 UTC, JFranklin3000 commented on module/sheet-handlers/advancement-handler.mjs
> +  /**
fixed

2024-01-18 23:56 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +
fixed

2024-01-19 00:02 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +   * Handle changes to an input element, submitting the form if options.submitOnChange is true. Do not preventDefault in this handler as other interactions on the form may also be occurring.
fixed

2024-01-19 00:02 UTC, JFranklin3000 commented on module/sheet-handlers/role-handler.mjs
> +    const hasRole = await getItemsOfType("role", this._actor.items);
changed

2024-01-19 00:02 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +            }
changed

2024-01-19 00:03 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> + * @returns {Integer} totalChange The number of level changes.
changed

2024-01-19 00:03 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +
fixed

2024-01-19 00:54 UTC, phildominguez requested changes

2024-01-19 00:54 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +   * @param {Roles} roles The role item that is being dropped on the actor
```suggestion
   * @param {Role} role The role item that is being dropped on the actor
```

2024-01-19 00:54 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +    }
```suggestion
    for (const essence in newRole.system.essenceLevels) {
      const totalIncrease = await roleValueChange(this._actor.system.level, newRole.system.essenceLevels[essence]);
      const essenceValue = this._actor.system.essences[essence] + totalIncrease;
      const essenceString = `system.essences.${essence}`;

      await this._actor.update({
        [essenceString]: essenceValue,
      });
    }
```

2024-01-19 00:54 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +      const newPersonalPowerMax = parseInt(this._actor.system.powers.personal.max)
```suggestion
    if (newRole.system.powers.personal.starting) {
      const totalIncrease = await roleValueChange(this._actor.system.level, role.system.powers.personal.levels);
      const newPersonalPowerMax = parseInt(this._actor.system.powers.personal.max)
```

2024-01-19 00:54 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +      const essenceValue = Math.max(0, this._actor.system.essences[essence] + totalDecrease);
```suggestion
  async onRoleDelete(role) {
    const previousLevel = this._actor.getFlag('essence20', 'previousLevel');

    for (const essence in role.system.essenceLevels) {
      const totalDecrease = await roleValueChange(0, role.system.essenceLevels[essence], previousLevel);
      const essenceValue = Math.max(0, this._actor.system.essences[essence] + totalDecrease);
```

2024-01-19 00:54 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +      await this._actor.update({
```suggestion
      const totalDecrease = await roleValueChange(0, role.system.powers.personal.levels, previousLevel);
      const newPersonalPowerMax = Math.max(0, parseInt(this._actor.system.powers.personal.max) - role.system.powers.personal.starting + (role.system.powers.personal.increase * totalDecrease));

      await this._actor.update({
```

2024-01-19 01:15 UTC, phildominguez approved these changes

2024-01-19 01:16 UTC, merged