MLP Adjustments
WookieeMatt/Essence20 pull request #570
Opened 2024-01-20 17:24 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- MLP Health Adjustments
- MLP Essence Select

##### Testing
- Validate drop is working for MLP Roles
- Build a role with type MLP

2024-01-22 23:22 UTC, phildominguez requested changes

2024-01-22 23:22 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +   */
```suggestion
  /**
   * Handles setting the values of what was selected in the Essence Selection Dialog
   * @param {Object} options The selections made in the dialog window.
   * @param {Role} role The role that was dropped on the actor
   * @param {Function} dropFunc The function for the drop of the role
   */
```

2024-01-22 23:22 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +    await createItemCopies(newRole.system.items, this._actor, "perk", newRole);
This looks a lot like `onLevelChange()`, can we consolidate?

2024-01-23 00:24 UTC, JFranklin3000 commented on module/sheet-handlers/advancement-handler.mjs
> +        const totalIncrease = await roleValueChange(this._actor.system.level, item.system.adjustments.health, previousLevel);
fixed, good call.

2024-01-23 00:25 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> + * Returns values of inputs upon dialog submission. Used for passing data between sequential dialogs.
removed

2024-01-23 00:25 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> + * @private
removed

2024-01-23 00:28 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> + * @returns {Object>}  The dialog inputs and their submitted values
fixed

2024-01-23 00:31 UTC, JFranklin3000 commented on module/sheet-handlers/role-handler.mjs
> +      }
But now it is fine. so removed.

2024-01-23 00:33 UTC, JFranklin3000 commented on templates/dialog/essence-select.hbs
> +            {{selectOptions choices nameAttr="key" labelAttr="label"}}
Changed

2024-01-23 02:11 UTC, JFranklin3000 commented on templates/actor/parts/misc/pc-skills.hbs
> +      {{/if}}
Sounds good.

2024-01-23 02:12 UTC, JFranklin3000 commented on module/sheet-handlers/role-handler.mjs
> +   */
fixed

2024-01-23 02:35 UTC, JFranklin3000 commented on module/sheet-handlers/role-handler.mjs
> +    await createItemCopies(newRole.system.items, this._actor, "perk", newRole);
I think we ran into this initially that it was just different enough that we couldn't quite put them together, but if we can figure it out I am all for it.

2024-01-23 02:43 UTC, JFranklin3000 commented on template.json
> +        "ponyEssence": {
Went with essenceRanks I think that is better.

2024-01-24 23:56 UTC, phildominguez requested changes

2024-01-24 23:56 UTC, phildominguez commented on lang/en.json
> +    "EssenceProgressionSilver": "Silver",
`EssenceRank*`

2024-01-24 23:56 UTC, phildominguez commented on lang/en.json
> +    "EssenceSelect": "Select Essence Progression",
`EssenceProgressionSelect`

2024-01-24 23:56 UTC, phildominguez commented on module/helpers/config.mjs
> +E20.AdvancementNames = [
`EssenceRankNames`

2024-01-24 23:56 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +  async _essenceSelect(role, dropFunc) {
`_selectEssenceProgression`

2024-01-24 23:56 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +  _verifySelection (options) {
```suggestion
  _verifyEssenceProgression(options) {
```

2024-01-24 23:56 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +  async _essenceSetValues (options, role, dropFunc) {
```suggestion
  async _setEssenceProgression(options, role, dropFunc) {
```

2024-01-25 00:43 UTC, phildominguez approved these changes

2024-01-25 01:08 UTC, merged