Skill Die and Grid Power Progression Added
WookieeMatt/Essence20 pull request #584
Opened 2024-02-16 23:37 UTC by JFranklin3000

##### In this PR
- Added Skill Die option to Roles and Grid Power Progression

##### Testing
- Small change to pull from Role Point restart.

2024-03-16 00:03 UTC, phildominguez requested changes

2024-03-16 00:03 UTC, phildominguez commented on packs/prcrbitems/_source/White_Ranger_6ANY0ZSPWC9G1WHD.json
> +      "specialization": [
This is currently `specialized` in the template

2024-03-16 00:10 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +    const shiftList=CONFIG.E20.skillShiftList;
fixed

2024-03-16 00:12 UTC, JFranklin3000 commented on templates/actor/parts/items/weapon/container.hbs
> +                <option value="{{@key}}">{{this.displayName}}</option>
It is in this case, there was a lot of research into this one. :) 
https://handlebarsjs.com/guide/builtin-helpers.html#each

2024-03-16 01:06 UTC, JFranklin3000 commented on template.json
> +        "specialized": []
Changed that makes sense.

2024-03-16 01:10 UTC, JFranklin3000 commented on template.json
> +        "has": false,
fixed

2024-03-16 01:11 UTC, JFranklin3000 commented on templates/item/sheets/role.hbs
> +    {{#> "systems/essence20/templates/item/parts/sheet-field.hbs" label='E20.hasSkillDie'}}
Changed to match other change

2024-03-16 01:12 UTC, JFranklin3000 commented on packs/prcrbitems/_source/White_Ranger_6ANY0ZSPWC9G1WHD.json
> +      "specialization": [
Changed to specializedLevels

2024-03-16 01:12 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> +    if (role.system.skillDie.specialization) {
Why would we remove the if? it is preventing an error I think as well.

2024-03-16 03:27 UTC, JFranklin3000 commented on templates/actor/parts/items/weapon/container.hbs
> +                <option value="{{@key}}">{{this.displayName}}</option>
see the object section.

2024-03-16 03:27 UTC, JFranklin3000 commented on module/sheet-handlers/role-handler.mjs
> +
fixed

2024-03-16 17:07 UTC, phildominguez commented on module/helpers/roll-dialog.mjs
> +
```suggestion
```

2024-03-16 17:07 UTC, phildominguez commented on module/dice.mjs
> +
```suggestion
```

2024-03-16 17:07 UTC, phildominguez commented on module/dice.mjs
> +      isSpecialized: specializationBoolean,
```suggestion
      isSpecialized: dataset.isSpecialized,
```

2024-03-16 17:08 UTC, phildominguez commented on module/helpers/utils.mjs
> +
```suggestion
```

2024-03-16 17:09 UTC, phildominguez requested changes

2024-03-16 17:09 UTC, phildominguez commented on templates/item/sheets/role.hbs
> +      {{#> "systems/essence20/templates/item/parts/sheet-field.hbs" label='E20.SkillDieSpecializedLevels'}}
`E20.SkillDieSpecializedLevels` not defined

2024-03-16 18:29 UTC, JFranklin3000 commented on templates/item/sheets/role.hbs
> +      {{#> "systems/essence20/templates/item/parts/sheet-field.hbs" label='E20.SkillDieSpecializedLevels'}}
Or in this case it was actually a typo of SillDieSpecializedLevels

2024-03-16 19:03 UTC, phildominguez requested changes

2024-03-16 19:03 UTC, phildominguez commented on module/helpers/roll-dialog.mjs
> +        isSpecialized: dataset.isSpecialized,
```suggestion
```

2024-03-16 19:03 UTC, phildominguez commented on module/dice.mjs
> +      isSpecialized: dataset.isSpecialized,
```suggestion
```

2024-03-17 15:47 UTC, phildominguez requested changes

2024-03-17 15:47 UTC, phildominguez commented on lang/en.json
> +    "RoleSkillDieError": "The roles Skill Die has no name.",
```suggestion
    "RoleSkillDieError": "Dropped Role's Skill Die must have a name.",
```

2024-03-17 15:47 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +    if (role.system.skillDie.isUsed && role.system.skillDie.name == "") {
```suggestion
    if (role.system.skillDie.isUsed && !role.system.skillDie.name) {
```

2024-03-17 15:47 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +      ui.notifications.error(game.i18n.format(game.i18n.localize('E20.RoleSkillDieError')));
```suggestion
      ui.notifications.error(game.i18n.localize('E20.RoleSkillDieError'));
```

2024-03-17 22:29 UTC, phildominguez approved these changes

2024-03-18 00:17 UTC, merged