Created Role Points as an Item and can drop them on to Roles
WookieeMatt/Essence20 pull request #586
Opened 2024-04-02 12:41 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- The Role Points Item

##### Testing
- Create a Role Point Item and add it to a Role.

2024-04-02 23:50 UTC, phildominguez requested changes

2024-04-02 23:50 UTC, phildominguez commented on lang/en.json
> +    "BonusAttackUpShift": "UpShift to Attack",
I'm leaning towards making "Up Shift" two words

2024-04-02 23:50 UTC, phildominguez commented on lang/en.json
> +    "RolePointsLevel20Advance": "Value at 20th Level (99 is unlimited)",
`RolePointsLevel20Value`?

2024-04-02 23:50 UTC, phildominguez commented on lang/en.json
> +    "RolePointsCanBeActivated": "Can Be Activated",
I'm remembering that for checkboxes we have been putting question marks at the end of these, so this could be "Can Be Activated?". Similar for others below.

2024-04-02 23:50 UTC, phildominguez commented on module/helpers/utils.mjs
> +export async function  createItemCopies(items, owner, type, parentItem, lastProcessedLevel=null) {
```suggestion
export async function createItemCopies(items, owner, type, parentItem, lastProcessedLevel=null) {
```

2024-04-02 23:50 UTC, phildominguez commented on module/helpers/utils.mjs
> +        if (item.type == 'rolePoints') {
```suggestion
      if (droppedItem.type == 'rolePoints' && item.type == 'rolePoints') {
```

2024-04-02 23:50 UTC, phildominguez commented on template.json
> +        "level20Advance": 0,
```suggestion
        "level20Value": 0,
```

2024-04-02 23:50 UTC, phildominguez commented on template.json
> +      "level20Advance": 0,
```suggestion
      "level20Value": 0,
```

2024-04-03 22:45 UTC, JFranklin3000 commented on lang/en.json
> +    "BonusAttackUpShift": "UpShift to Attack",
This is one of those terminology changes that is kind of annoying. PR uses the two word Shift Up whereas TF and GI Joe use Upshift.

2024-04-03 22:53 UTC, JFranklin3000 commented on lang/en.json
> +    "RolePointsCanBeActivated": "Can Be Activated",
Added Question Mark

2024-04-03 22:53 UTC, JFranklin3000 commented on lang/en.json
> +    "RolePointsLevel20Advance": "Value at 20th Level (99 is unlimited)",
Changed

2024-04-04 15:35 UTC, phildominguez requested changes

2024-04-04 15:35 UTC, phildominguez commented on lang/en.json
> +    "RolePointsSecondaryPointIncrease": "Has a Secondary Advancement",
```suggestion
    "RolePointsSecondaryPointIncrease": "Has a Secondary Advancement?",
```

2024-04-04 19:02 UTC, phildominguez approved these changes

2024-04-04 19:06 UTC, merged