Role points drop
WookieeMatt/Essence20 pull request #589
Opened 2024-04-16 02:45 UTC by JFranklin3000

##### In this PR
- Added Role Points to Role Drop

##### Testing
- Validate dropping Roles on to the actor adds the rolePoints as an item as well.

2024-04-16 23:37 UTC, phildominguez requested changes

2024-04-16 23:37 UTC, phildominguez commented on module/documents/item.mjs
> +    if (this.type == 'rolePoints') {
```suggestion
    } else if (this.type == 'rolePoints') {
```

2024-04-16 23:37 UTC, phildominguez commented on module/documents/item.mjs
> +      }
I feel we should toss this into a helper method, maybe `getLevelIncreases`?

2024-04-16 23:37 UTC, phildominguez commented on template.json
> +      },
```suggestion
      "points": {
        "primary": {
          "max": 0,
          "value" : 0
        },
        "secondary": {
          "max": 0,
          "value" : 0
        }
      },
```
Thoughts on this structure? Also I'm not big on role points having role points, so I just changed it to `points`.

2024-04-17 03:29 UTC, JFranklin3000 commented on template.json
> +      },
I like the structure have to do a deep dive to make sure this is changed everywhere.

2024-04-17 03:29 UTC, JFranklin3000 commented on module/documents/item.mjs
> +      }
Probably a good idea as well.

2024-04-17 22:32 UTC, phildominguez requested changes

2024-04-17 22:32 UTC, phildominguez commented on module/helpers/utils.mjs
> + * @returns {LevelIncrease} The number of increases for the level of the actor
Remember that the stuff that goes in the `{ }` is the type of the parameter, not the name. Mostly it will be `Number` or `String`, or if it's an array of one of those then `Blah[]`. The other common case is an object/class, like `Actor` or `Weapon`.

2024-04-17 22:59 UTC, JFranklin3000 commented on module/helpers/utils.mjs
> + * @returns {LevelIncrease} The number of increases for the level of the actor
fixed.

2024-04-17 23:05 UTC, phildominguez approved these changes

2024-04-18 03:40 UTC, merged