Transformer roles
WookieeMatt/Essence20 pull request #604
Opened 2024-04-30 21:38 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- Added missing Items from Transformers and FGtAA

##### Testing
- 
fvtt package pack -n "dditems"
fvtt package pack -n "eocitems"
fvtt package pack -n "tfcrbitems"
fvtt package pack -n "fgtaaitems"

2024-04-30 23:15 UTC, phildominguez requested changes

2024-04-30 23:15 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +
```suggestion
```

2024-04-30 23:15 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +  async _setEssenceProgression (options, role, dropFunc, level1Essences) {
```suggestion
  async _setEssenceProgression(options, role, dropFunc, level1Essences) {
```

2024-04-30 23:15 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +    }else{
```suggestion
    } else {
```

2024-04-30 23:15 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +      throw new Error('Must Select 2 Essences');
Localize

2024-04-30 23:17 UTC, phildominguez requested changes

2024-04-30 23:17 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +  async _selectFirstEssences(role,dropFunc) {
```suggestion
  async _selectFirstEssences(role, dropFunc) {
```

2024-04-30 23:53 UTC, phildominguez requested changes

2024-04-30 23:53 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +  * @param {Object} role The role that is being dropped on the actor
```suggestion
  * @param {Role} role The role that is being dropped on the actor
```

2024-04-30 23:53 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +   *
```suggestion
```

2024-04-30 23:53 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +   * @returns
```suggestion
```

2024-04-30 23:53 UTC, phildominguez commented on lang/en.json
> +    "EssencesRequiredError": "Must Select 2 Essences",
```suggestion
    "EssencesRequiredError": "Must select 2 Essences",
```

2024-05-01 00:12 UTC, phildominguez approved these changes

2024-05-01 00:27 UTC, JFranklin3000 commented on module/sheet-handlers/role-handler.mjs
> +      throw new Error('Must Select 2 Essences');
fixed

2024-05-01 00:29 UTC, merged