Personal Power Regeneration added to _onRest
WookieeMatt/Essence20 pull request #606
Opened 2024-05-01 12:31 UTC by JFranklin3000

##### In this PR
- Added Personal Power Regeneration to _onRest
- 

##### Testing
- pack Power Rangers Core Rulebook
- Drop Role on to Actor
- Check Personal Power Regeneration on Role
- click rest button. 
- validate proper amount of Personal Power Restored.

fvtt package unpack -n "prcrbitems"

2024-05-01 16:42 UTC, phildominguez requested changes

2024-05-01 16:42 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +      }
We can use Math.min instead here

2024-05-01 16:42 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +      ui.notifications.info("Personal Power restored.");
Gah, we missed a bunch of localizations in this method. Want to take care of those?

2024-05-01 16:42 UTC, phildominguez commented on module/helpers/utils.mjs
>        "system.powers.personal.max": newPersonalPowerMax,
Nothing you did here, but leveling is setting max to 0. Let's get the fix in this PR.

2024-05-01 23:31 UTC, JFranklin3000 commented on module/helpers/utils.mjs
>        "system.powers.personal.max": newPersonalPowerMax,
fixed

2024-05-02 00:11 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +      ui.notifications.info("Personal Power restored.");
Got them all

2024-05-02 00:11 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +      }
changed

2024-05-02 00:25 UTC, phildominguez approved these changes

2024-05-02 00:25 UTC, merged