Transitioning away from Handler classes #3
WookieeMatt/Essence20 pull request #632
Opened 2024-05-06 18:29 UTC by phildominguez

Addresses https://github.com/WookieeMatt/Essence20/issues/617

##### In this PR
- Un-classes Role handler
- Cleaned up some comment blocks as well

##### Testing
- Adding and deleting roles and focuses should work as expected, including essence selection

2024-05-06 23:13 UTC, JFranklin3000 approved these changes

2024-05-07 00:33 UTC, JFranklin3000 requested changes

2024-05-07 00:33 UTC, JFranklin3000 commented on module/sheet-handlers/role-handler.mjs
> +    await _selectEssenceProgression(role,dropFunc);
function now expects actor as the first value

2024-05-07 02:15 UTC, phildominguez commented on module/sheet-handlers/role-handler.mjs
> +    await _selectEssenceProgression(role,dropFunc);
Fixed

2024-05-07 02:26 UTC, JFranklin3000 approved these changes

2024-05-07 02:28 UTC, merged