Added essence level edges and snags
WookieeMatt/Essence20 pull request #705
Opened 2024-06-22 21:22 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- Added an option to add edges and snags to all skills in an Essence

##### Testing
- create effect with system.essenceShifts.<essence>.edge or snag validate

2024-06-23 23:55 UTC, phildominguez requested changes

2024-06-23 23:55 UTC, phildominguez commented on module/dice.mjs
> +      snag: calculatedSnag,
```suggestion
      edge: actorSkillData.edge || essenceShifts[rolledEssence].edge,
      snag: actorSkillData.snag || essenceShifts[rolledEssence].snag,
```

2024-06-23 23:55 UTC, phildominguez commented on module/dice.mjs
> +
```suggestion
```

2024-06-24 03:26 UTC, JFranklin3000 commented on module/dice.mjs
> +      snag: calculatedSnag,
changed

2024-06-24 03:26 UTC, JFranklin3000 commented on module/dice.mjs
> +
changed

2024-06-24 13:06 UTC, phildominguez approved these changes

2024-06-24 13:17 UTC, merged