Essence damage
WookieeMatt/Essence20 pull request #708
Opened 2024-06-25 03:05 UTC by JFranklin3000

Closes [[issue URL](https://github.com/WookieeMatt/Essence20/issues/553)]

##### In this PR
- Migrate essences to have value and max values
- Added a field on the essence to represent 

##### Testing
- Validate user migration finishes successfully.

2024-06-25 23:40 UTC, phildominguez requested changes

2024-06-25 23:40 UTC, phildominguez commented on module/data/actor/templates/character.mjs
> +
```suggestion
```

2024-06-25 23:40 UTC, phildominguez commented on module/migration.mjs
> +
```suggestion
```

2024-06-25 23:40 UTC, phildominguez commented on module/sheet-handlers/listener-misc-handler.mjs
> +  for (const essence of Object.keys(actor.system.essences)) {
```suggestion
  // Recovering Essence damage
  for (const essence of Object.keys(actor.system.essences)) {
```

2024-06-25 23:40 UTC, phildominguez commented on module/sheet-handlers/listener-misc-handler.mjs
> +      });
I would put a UI notification saying that the essence was recovered, like the other messages

2024-06-26 00:13 UTC, JFranklin3000 commented on module/data/actor/companion.mjs
> +
reverted

2024-06-26 00:23 UTC, JFranklin3000 commented on module/sheet-handlers/listener-misc-handler.mjs
> +      });
UI notification added.

2024-06-27 16:25 UTC, phildominguez requested changes

2024-06-27 16:25 UTC, phildominguez commented on lang/en.json
> +    "RestEssenceRestored": "{essence} essence restored to {essenceRestore}",
```suggestion
    "RestEssenceRestored": "{essence} Essence restored to {essenceRestore}",
```

2024-06-28 01:39 UTC, phildominguez approved these changes

2024-06-28 02:55 UTC, merged