Changes for Actor Drop
WookieeMatt/Essence20 pull request #722
Opened 2024-08-12 02:08 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- Modified drop for Megaform Combiners to drop Zords and Transformers
- Added drop to Vehicles and Zords that supports selecting passenger location
- Added drop for actors with the Zord Perk to drop Zords on to Characters

##### Testing
- Validate all of the drops in the PR work as expected. 
- Validate all other drops error.

2024-08-12 22:33 UTC, phildominguez requested changes

2024-08-12 22:33 UTC, phildominguez commented on templates/actor/parts/misc/system-actors.hbs
> +    {{#each @root.actors as |attachedActor|}}
Could we do something where if there are no actors present we show a message, like "Drop passengers here" or "Drop Zord Combiners here"?

2024-08-12 22:33 UTC, phildominguez commented on lang/en.json
> +    "ActorDropError": "The dropping of this actor type on to this target actor is not supported.",
```suggestion
    "ActorDropError": "The dropping of this Actor type onto this target Actor is not supported.",
```

2024-08-12 22:33 UTC, phildominguez commented on module/helpers/config.mjs
> +//Vehicle Traits
```suggestion
// Vehicle Roles
E20.vehicleRoles = {
  driver: "E20.VehicleRoleDriver",
  gunner: "E20.VehicleRoleGunner",
  passenger: "E20.VehicleRolePassenger",
};
preLocalize("vehicleRole");

// Vehicle Traits
```

2024-08-12 22:33 UTC, phildominguez commented on module/helpers/dialog.mjs
> +
```suggestion
```

2024-08-12 22:33 UTC, phildominguez commented on module/helpers/templates.mjs
> +
```suggestion
```

2024-08-12 22:33 UTC, phildominguez commented on module/sheet-handlers/drop-handler.mjs
> +  let droppedActor = await fromUuid(data.uuid);
```suggestion
  const droppedActor = await fromUuid(data.uuid);
```

2024-08-12 22:33 UTC, phildominguez commented on module/sheet-handlers/drop-handler.mjs
> +    break;
If the logic in these are all the same, you should be able to do something like:
```
case 'pony':
case 'powerRanger':
cast 'transformer':
  // logic here
```

2024-08-12 22:33 UTC, phildominguez commented on module/sheet-handlers/drop-handler.mjs
> +    ui.notifications.error(game.i18n.localize('E20.ActorDropError'));
I would make a variable before the switch (something like `dropIsValid`) that is initialized as false. Then, inside the `if` for each case set it to true. After the entire switch you can then do an if !dropIsValid-> notify, that way it reduces duplication.

2024-08-12 22:33 UTC, phildominguez commented on module/sheet-handlers/drop-handler.mjs
> +      setEntryAndAddActor (droppedActor, targetActor);
```suggestion
      setEntryAndAddActor(droppedActor, targetActor);
```
Similar on the declarations below too

2024-08-12 22:33 UTC, phildominguez commented on templates/dialog/vehicleRole-select.hbs
I would stick with kebab case, so vehicle-role-seelct.hbs

2024-08-12 22:33 UTC, phildominguez commented on module/sheet-handlers/drop-handler.mjs
> +  }
```suggestion
    return addActorIfUnique(droppedActor, targetActor, entry);
  }
```

2024-08-12 22:33 UTC, phildominguez commented on module/sheet-handlers/drop-handler.mjs
> +
```suggestion
```

2024-08-12 22:33 UTC, phildominguez commented on module/sheet-handlers/drop-handler.mjs
> +  async function _selectVehicleLocation(droppedActor, targetActor) {
Reminder for comment blocks 😃

2024-08-12 22:33 UTC, phildominguez commented on module/sheet-handlers/power-ranger-handler.mjs
```suggestion
```

2024-08-12 22:33 UTC, phildominguez commented on module/sheet-handlers/power-ranger-handler.mjs
> +    let actors = [];
```suggestion
    const actors = [];
```

2024-08-12 22:33 UTC, phildominguez commented on module/sheet-handlers/power-ranger-handler.mjs
>   * @param {Actor} actor The Megaform Zord to prepare Zords for
Update these

2024-08-12 22:33 UTC, phildominguez commented on module/sheet-handlers/power-ranger-handler.mjs
>   */
Update comment block

2024-08-12 22:33 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
>      // Delete Zord from MFZ
Update

2024-08-12 22:33 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
>      // Prepare Zords for MFZs
Update

2024-08-12 22:59 UTC, JFranklin3000 commented on module/sheet-handlers/drop-handler.mjs
> +    break;
changed

2024-08-12 23:08 UTC, JFranklin3000 commented on module/sheet-handlers/drop-handler.mjs
> +    ui.notifications.error(game.i18n.localize('E20.ActorDropError'));
changed.

2024-08-12 23:15 UTC, JFranklin3000 commented on module/sheet-handlers/drop-handler.mjs
> +  async function _selectVehicleLocation(droppedActor, targetActor) {
Added

2024-08-12 23:17 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
>      // Prepare Zords for MFZs
Updated

2024-08-12 23:17 UTC, JFranklin3000 commented on module/sheet-handlers/power-ranger-handler.mjs
>   */
Updated

2024-08-12 23:17 UTC, JFranklin3000 commented on module/sheet-handlers/power-ranger-handler.mjs
>   * @param {Actor} actor The Megaform Zord to prepare Zords for
Updated

2024-08-12 23:57 UTC, phildominguez requested changes

2024-08-12 23:57 UTC, phildominguez commented on module/sheet-handlers/drop-handler.mjs
> +
```suggestion
```

2024-08-12 23:57 UTC, phildominguez commented on module/sheet-handlers/drop-handler.mjs
> + * @param {actor} targetActor The actor that is being dropped on to
```suggestion
 * @param {Actor} droppedActor The actor that is being dropped
 * @param {Actor} targetActor The actor that is being dropped on to
```

2024-08-12 23:57 UTC, phildominguez commented on module/sheet-handlers/drop-handler.mjs
> + * @param {role} options An optional parameter for if a vehicle role has been selected
```suggestion
 * @param {Actor} droppedActor Actor dropped on to another actor
 * @param {Actor} targetActor Actor that is being dropped on to
 * @param {Objects} options An optional parameter for if a vehicle role has been selected
```

2024-08-12 23:57 UTC, phildominguez commented on module/sheet-handlers/drop-handler.mjs
> + * @returns
Missing what it returns

2024-08-12 23:57 UTC, phildominguez commented on module/sheet-handlers/drop-handler.mjs
> + * @param {object} entry The value to be written to the system.actors
```suggestion
 * Adds the dropped actor into system.actors
 * @param {Actor} droppedActor Actor dropped on to another actor
 * @param {Actor} targetActor Actor that is being dropped on to
 * @param {Object} entry The value to be written to the system.actors
```

2024-08-12 23:57 UTC, phildominguez commented on module/sheet-handlers/drop-handler.mjs
> + * @returns
Missing what it returns

2024-08-12 23:57 UTC, phildominguez commented on templates/actor/parts/misc/system-actors.hbs
> +        <input class="no-unlock" type="text" value="{{localize 'E20.ActorDrop'}}" readonly />
I would just use (centered) plan text here

2024-08-12 23:59 UTC, JFranklin3000 commented on templates/actor/parts/misc/system-actors.hbs
> +    {{#each @root.actors as |attachedActor|}}
added

2024-08-13 00:02 UTC, JFranklin3000 commented on module/sheet-handlers/drop-handler.mjs
> + * @returns
fixed

2024-08-13 00:02 UTC, JFranklin3000 commented on module/sheet-handlers/drop-handler.mjs
> + * @returns
fixed

2024-08-13 00:07 UTC, JFranklin3000 commented on templates/actor/parts/misc/system-actors.hbs
> +        <input class="no-unlock" type="text" value="{{localize 'E20.ActorDrop'}}" readonly />
changed

2024-08-13 01:40 UTC, phildominguez approved these changes

2024-08-13 01:40 UTC, merged