Passenger Updates
WookieeMatt/Essence20 pull request #730
Opened 2024-08-28 01:30 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- Added ability to update driver and passenger on vehicle and Zords
- Added checks to validate space for Drivers and Passengers.

##### Testing
- drop actors on Vehicles and assign vehicle role. 
- Validate you can't drop more than max (Zord's start with just 1 driver)

2024-10-27 14:03 UTC, phildominguez requested changes

2024-10-29 12:37 UTC, JFranklin3000 commented on module/sheet-handlers/drop-handler.mjs
> +
removed

2024-10-29 12:37 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +    html.find('.numCrew').change(ev=> onCrewNumberUpdate(ev, this));
fixed

2024-10-29 12:38 UTC, JFranklin3000 commented on module/sheet-handlers/power-ranger-handler.mjs
> +export async function onCrewNumberUpdate (event, actorSheet) {
fixed

2024-10-29 12:38 UTC, JFranklin3000 commented on module/sheet-handlers/power-ranger-handler.mjs
> +
removed

2024-10-29 12:41 UTC, JFranklin3000 commented on lang/en.json
> +    "VehicleRoleError": "That position is currently maxed out.",
changed

2024-10-29 12:41 UTC, JFranklin3000 commented on lang/en.json
> +    "VehicleRoleErrorTooManyCrew": "There are currently more crew members in the vehicle then your change allows.",
Fixed for now at a later date I might do templating.

2024-10-29 12:47 UTC, JFranklin3000 commented on module/sheet-handlers/power-ranger-handler.mjs
> +          label: "No",
fixed

2024-10-29 12:47 UTC, JFranklin3000 commented on module/sheet-handlers/power-ranger-handler.mjs
> +            label: "Cancel",
fixed

2024-10-29 12:51 UTC, JFranklin3000 commented on module/sheet-handlers/power-ranger-handler.mjs
> +        title: "Select Who to Flip With?",
fixed

2024-10-29 12:53 UTC, JFranklin3000 commented on module/sheet-handlers/drop-handler.mjs
> +  }
fixed

2024-10-29 18:36 UTC, phildominguez approved these changes

2024-10-29 21:34 UTC, merged