Actor Selector for Vehicle/Zord Rolls
WookieeMatt/Essence20 pull request #741
Opened 2024-11-09 05:20 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- Actor Selector for Skill rolls and Weapon Rolls. 

##### Testing
- Validate that all rolls can be selected (other than Initiative).

2024-11-09 18:39 UTC, phildominguez requested changes

2024-11-09 18:39 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +      html.find('.rollable').click(ev => actorSelector(ev, this.actor));
This is tricky. We use `on...` to indicate when a method is a listener. Could we leave `onRoll()` here and have that call `actorSelector()` when needed?

2024-11-09 18:39 UTC, phildominguez commented on module/sheet-handlers/listener-misc-handler.mjs
> +        title: game.i18n.localize('E20.ActorSelect'),
`E20.ActorSelect` not defined

2024-11-09 18:39 UTC, phildominguez commented on module/sheet-handlers/listener-misc-handler.mjs
> +  }
I would put this case first since it's kind of the normal/default behavior

2024-11-09 18:39 UTC, phildominguez commented on module/sheet-handlers/listener-misc-handler.mjs
> +    };
We could use `createId()` to make a safe ID and then pass that along to `alterDataset()`

2024-11-09 18:39 UTC, phildominguez commented on module/sheet-handlers/listener-misc-handler.mjs
> +async function alterDataset(actor, options, event) {
The name is a bit vague, what about `handleActorSelector()` or something?

2024-11-09 18:39 UTC, phildominguez commented on module/sheet-handlers/listener-misc-handler.mjs
> +
```suggestion
```

2024-11-11 02:53 UTC, JFranklin3000 commented on module/sheet-handlers/listener-misc-handler.mjs
> +
fixed

2024-11-11 03:24 UTC, JFranklin3000 commented on module/sheet-handlers/listener-misc-handler.mjs
> +    };
So this one is a safe idea as we create 4 digit keys as this is 5 it would never be duplicated.

2024-11-11 03:31 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +      html.find('.rollable').click(ev => actorSelector(ev, this.actor));
I had a lot of issues trying to stick it in the onRoll, which was why I kicked it out and did it first and then called onRoll. I am reluctant to retread that but there might be something we could do.

2024-11-11 03:35 UTC, JFranklin3000 commented on module/sheet-handlers/listener-misc-handler.mjs
> +        title: game.i18n.localize('E20.ActorSelect'),
fixed

2024-11-11 03:41 UTC, JFranklin3000 commented on module/sheet-handlers/listener-misc-handler.mjs
> +export async function onRoll(event, actor, rollingActor) {
changed

2024-11-11 03:44 UTC, JFranklin3000 commented on module/documents/item.mjs
> +      }
changed

2024-11-11 03:46 UTC, JFranklin3000 commented on module/sheet-handlers/listener-misc-handler.mjs
> +  }
changed

2024-11-11 03:47 UTC, JFranklin3000 commented on module/sheet-handlers/listener-misc-handler.mjs
> +async function alterDataset(actor, options, event) {
changed

2024-11-11 03:47 UTC, JFranklin3000 commented on module/sheet-handlers/listener-misc-handler.mjs
> +
fixed

2024-11-11 03:48 UTC, JFranklin3000 commented on module/documents/item.mjs
> +  async roll(dataset, actor, childKey, rollingActor) {
I removed the childKey and added the None thing. To me this is the actor that is actually going to make the roll thus rollingActor, passenger or crewman don't really convey that.

2024-11-12 02:08 UTC, phildominguez requested changes

2024-11-12 02:08 UTC, phildominguez commented on module/sheet-handlers/listener-misc-handler.mjs
> +
```suggestion
```

2024-11-12 02:08 UTC, phildominguez commented on module/sheet-handlers/listener-misc-handler.mjs
> +  if (options['actor'] == '00000') {
I'm thinking at the top of this file we should add a `CHILD_ROLLER_KEY = "00000"`, since it's used in two different methods. Now that i'm thinking about it, should we just make the key something more obvious, like "childRoller"? Could make debugging easier down the road.

2024-11-12 02:14 UTC, phildominguez requested changes

2024-11-12 02:14 UTC, phildominguez commented on module/sheet-handlers/listener-misc-handler.mjs
> +    onRoll(event,actor, null);
```suggestion
    onRoll(event, actor, null);
```

2024-11-12 02:15 UTC, phildominguez requested changes

2024-11-12 02:15 UTC, phildominguez commented on module/sheet-handlers/listener-misc-handler.mjs
> +    for (const [ key, passenger] of Object.entries (actor.system.actors)) {
```suggestion
    for (const [key, passenger] of Object.entries(actor.system.actors)) {
```

2024-11-12 02:45 UTC, JFranklin3000 commented on module/sheet-handlers/listener-misc-handler.mjs
> +  let childRoller = {};
Had to go back to let, because otherwise we failed lint.

2024-11-12 02:54 UTC, JFranklin3000 commented on module/sheets/actor-sheet.mjs
> +      html.find('.rollable').click(ev => actorSelector(ev, this.actor));
renamed per discussion

2024-11-12 03:49 UTC, phildominguez requested changes

2024-11-12 03:49 UTC, phildominguez commented on module/sheet-handlers/listener-misc-handler.mjs
> + *  @param {Event} event The originating click event
```suggestion
 * @param {Event} event The originating click event
 * @param {Actor} actor The Actor making the roll
```

2024-11-12 03:49 UTC, phildominguez commented on module/sheet-handlers/listener-misc-handler.mjs
> + * @param {Actor} childRoller If chosen the attached actor that is making the roll
```suggestion
 * @param {Event} event The originating click event
 * @param {Actor} actor The Actor making the roll
 * @param {Actor} childRoller Optional attached Actor making the roll
```

2024-11-12 03:49 UTC, phildominguez commented on module/sheets/actor-sheet.mjs
> +  onRest,
```suggestion
  onRest,
  onRoll,
```

2024-11-12 03:49 UTC, phildominguez commented on module/sheet-handlers/listener-misc-handler.mjs
> + * @param {Event} event The originating click event
```suggestion
 * @param {Actor} actor The Actor making the roll
 * @param {Object} options The options selected in the dialog
 * @param {Event} event The originating click event
```

2024-11-12 03:49 UTC, phildominguez commented on module/documents/item.mjs
> +   * @param {Actor} [childRoller=None] If an attached actor is making the roll
```suggestion
   * @param {Actor} childRoller Optional attached Actor making the roll
```

2024-11-12 03:49 UTC, phildominguez commented on lang/en.json
> +    "ActorSelect": "Select who to Roll.",
```suggestion
    "ActorSelect": "Who is performing this roll?",
```

2024-11-12 04:12 UTC, phildominguez approved these changes

2024-11-12 04:13 UTC, merged