Adding Choices Application V2
WookieeMatt/Essence20 pull request #769
Opened 2024-11-26 15:34 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- Moving Influence and Origin Drops to use Application V2 instead of Dialogs

##### Testing
- Validate drop of Influences with multiple Hang-Ups
- Validate drop of Origin including ones with multiple AltModes.

2024-11-27 00:16 UTC, phildominguez requested changes

2024-11-27 00:16 UTC, phildominguez commented on module/apps/choices-prompt.mjs
I feel like calling this file `choices-prompt` is throwing me off because it's very specifically for picking background stuff. Should this actually all be a part of `background-handler`?

2024-11-27 00:16 UTC, phildominguez commented on module/apps/trait-selector.mjs
> +
```suggestion
```

2024-11-27 00:16 UTC, phildominguez commented on module/helpers/traits.mjs
> +    break;
I think this should be at the top to be alphabetical?

2024-11-27 00:16 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
> +            console.log(influenceEssence);
```suggestion
```

2024-11-27 00:16 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
> +  if (altModes.length >0) {
```suggestion
```

2024-11-27 00:16 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
> +      if (item.type == "altMode") {
```suggestion
```
We know the type already because of `getItemsOfType`

2024-11-27 00:16 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
> +        if (selectedAltMode) {
How does one get into `setOriginValues` unless an alt mode was selected?

2024-11-27 00:16 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
> +
```suggestion
```

2024-11-27 00:16 UTC, phildominguez commented on templates/app/choice-select-prompt.hbs
The classes in here don't exist, can we add them?

2024-11-27 00:19 UTC, JFranklin3000 commented on module/apps/choices-prompt.mjs
> +    title: "Make a Selection",
This might be a problem. if I localize in here it breaks.

2024-11-27 00:21 UTC, JFranklin3000 commented on module/sheet-handlers/background-handler.mjs
> +  if (altModes.length >0) {
Yea we need that other wise Origins with out an altMode stop working.

2024-11-27 00:22 UTC, JFranklin3000 commented on module/sheet-handlers/background-handler.mjs
> +      if (item.type == "altMode") {
changed

2024-11-27 00:25 UTC, JFranklin3000 commented on module/sheet-handlers/background-handler.mjs
> +        if (selectedAltMode) {
``_checkForAltModes()`` if there are altModes on an Origin we do another ``ChoicePrompt()`` otherwise we go directly to ``setOriginValues``.

2024-11-27 00:27 UTC, JFranklin3000 commented on module/helpers/traits.mjs
> +    break;
Makes sense to me.

2024-11-27 00:27 UTC, JFranklin3000 commented on module/apps/choices-prompt.mjs
No because it isn't going to stay just for background stuff. It will be for Influences, Origins, Focus, Alterations, Shields, etc in the end.

2024-11-27 00:29 UTC, JFranklin3000 commented on templates/app/choice-select-prompt.hbs
add the into the scss? or where?

2024-11-27 00:38 UTC, phildominguez commented on templates/app/choice-select-prompt.hbs
Yeah, if you can find them in the pf scss code

2024-11-27 00:40 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
> +  if (altModes.length >0) {
But for loops handle empty lists fine. Do you have an example of this not working?

2024-11-27 00:46 UTC, JFranklin3000 commented on module/sheet-handlers/background-handler.mjs
> +  if (altModes.length >0) {
They do, but we need something to say don't go into the loop if the Origin doesn't have an altMode, but if it does and there is no selection return with an error.

2024-11-27 01:00 UTC, JFranklin3000 commented on module/apps/choices-prompt.mjs
> +    title: "Make a Selection",
fix pushed.

2024-11-27 01:20 UTC, phildominguez requested changes

2024-11-27 01:20 UTC, phildominguez commented on module/sheet-handlers/background-handler.mjs
>   * @param {Object} options The options resulting from _showOriginEssenceDialog()
```suggestion
 * @param {String} selectedEssence The Essence selected _showOriginEssenceDialog()
```
And similar for other methods with param changes

2024-11-27 01:20 UTC, phildominguez commented on module/apps/choices-prompt.mjs
> +  static origin(event,selection) {
```suggestion
  static origin(event, selection) {
```

2024-11-27 01:32 UTC, JFranklin3000 commented on module/sheet-handlers/background-handler.mjs
>   * @param {Object} options The options resulting from _showOriginEssenceDialog()
fixed the params.

2024-11-28 02:37 UTC, phildominguez approved these changes

2024-11-28 02:37 UTC, merged