Adding Shields as an item to the system
WookieeMatt/Essence20 pull request #777
Opened 2024-12-01 03:17 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- shields add as an item to the dataModel
- Shields added to the Gear Tab
- Shield Equip and Activate functions added. 
- Shields added to the Cobra Codex, A Jump Through Time, Beneath the Helmet, and Through the Shattered Grid packs. 

##### Testing
- Drop a shield on to an actor. 
- equip shields with different types of defense bonuses
- validate bonuses are applied
- Activate shield and see bonus changes.

2024-12-01 19:19 UTC, phildominguez requested changes

2024-12-01 19:19 UTC, phildominguez commented on templates/actor/parts/misc/collapsible-item-container-label-buttons.hbs
> +        <a class="shield-activate" data-id="{{item._id}}" {{#if system.active}} data-tooltip="Active"{{else}}data-tooltip="Passive"{{/if}} style="flex-grow: 0;"><i class="fas fa-shield"></i></a>
```suggestion
        <a class="shield-activate" data-id="{{item._id}}" style="flex-grow: 0;"
          {{#if system.active}} data-tooltip="Active" {{else}} data-tooltip="Passive" {{/if}}
        >
          <i class="fas fa-shield"></i>
        </a>
```
Just whitespace

2024-12-01 19:19 UTC, phildominguez commented on templates/actor/parts/misc/collapsible-item-container-label-buttons.hbs
> +    <input class="inline-edit item-label-checkbox {{#ifEquals item.type "shield"}} shield-equip{{/ifEquals}}" data-field="system.equipped" data-id="{{item._id}}" type="checkbox" name="shield.{{@index
```suggestion
    <input class="inline-edit item-label-checkbox {{#ifEquals item.type "shield"}} shield-equip{{/ifEquals}}"
      data-field="system.equipped" data-id="{{item._id}}" type="checkbox" name="shield.{{@index}}.equipped"
      {{checked item.system.equipped}} title="{{localize 'E20.ItemToggleEquipped'}}"
      {{#ifCond @root.shieldEquipped "&&" item.system.equipped}} {{else}} {{#if @root.shieldEquipped}} disabled {{/if}} {{/ifCond}}
    />
```
Just whitespace

2024-12-01 19:19 UTC, phildominguez commented on templates/item/sheets/shield.hbs
> +      {{> "systems/essence20/templates/item/parts/id-drop.hbs" className="weaponEffect" label='E20.ItemTypeWeaponEffectPlural' items=@root.system.items type='weaponEffect'}}
`E20.ItemTypeWeaponEffectPlural` not defined

2024-12-01 19:19 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> +    ui.notifications.error(game.i18n.localize('E20.ShieldNotEquipped'));
Not defined

2024-12-01 19:19 UTC, phildominguez commented on templates/actor/parts/misc/collapsible-item-container-label-buttons.hbs
> +        <a class="shield-activate" data-id="{{item._id}}" {{#if system.active}} data-tooltip="Active"{{else}}data-tooltip="Passive"{{/if}} style="flex-grow: 0;"><i class="fas fa-shield"></i></a>
I would have it use a shield outline when it's deactivated and a filled in shield when it's activated, otherwise it's hard to tell
![image](https://github.com/user-attachments/assets/f2c123fd-a91a-4838-ad0e-237f2417f5d3)

2024-12-01 19:19 UTC, phildominguez commented on templates/actor/parts/misc/pc-body.hbs
> +      {{> "systems/essence20/templates/actor/parts/items/shield/container.hbs"}}
Is it weird to have shields in the gear tab but not the combat tab? Especially when armor is in both?

2024-12-01 19:19 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> +export async function onShieldEquip(event, actorSheet) {
If I equip a shield, activate it, and then unequip it, then it should automatically deactivate I assume? Right now I'm seeing it stay active and it errors when I try to deactivate.

2024-12-01 19:28 UTC, phildominguez commented on templates/actor/parts/misc/collapsible-item-container-label-buttons.hbs
> +        <a class="shield-activate" data-id="{{item._id}}" {{#if system.active}} data-tooltip="Active"{{else}}data-tooltip="Passive"{{/if}} style="flex-grow: 0;"><i class="fas fa-shield"></i></a>
Maybe a checkmark?
![image](https://github.com/user-attachments/assets/ddf8f8da-c642-47ad-86d9-b2406c68be35)

2024-12-01 23:15 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> +export async function onShieldActivate(event, actorSheet) {
I was thinking of how we use onTransform or onMorph, but no issue changing it.

2024-12-01 23:16 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> +export async function onShieldActivate(event, actorSheet) {
changed

2024-12-01 23:18 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> +      currentShield = shield;
fixed

2024-12-01 23:22 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> +  }
fixed

2024-12-01 23:30 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> +    if (currentShield.system.passiveEffect.type == "defenseBonus" || currentShield.system.passiveEffect.type == "defenseBonusCombo") {
changed

2024-12-01 23:33 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> +  if (defense) {
It is if you do one of the weird Mixed bonuses. where you can get either a defense bonus or like Cover.

2024-12-01 23:34 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> +  }
ok got that one. changed.

2024-12-01 23:35 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> +export async function onShieldEquip(event, actorSheet) {
sure that works. changed.

2024-12-01 23:36 UTC, JFranklin3000 commented on templates/app/choice-select-prompt.hbs
> +        <button type="button" name="{{choice.defense}}" value="{{choice.value}}" data-action="{{../type}}">
it does, but it works! :D It lets me have something in the button I can pull directly for both the defense and the value.

2024-12-01 23:39 UTC, JFranklin3000 commented on templates/actor/parts/misc/pc-body.hbs
> +      {{> "systems/essence20/templates/actor/parts/items/shield/container.hbs"}}
This one I put to the Discord, I was thinking in the same thing. That was the predominant answer.

2024-12-01 23:46 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> +    ui.notifications.error(game.i18n.localize('E20.ShieldNotEquipped'));
fixed

2024-12-01 23:49 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> +export async function onShieldEquip(event, actorSheet) {
Added a fix for this to the unequip section.

2024-12-01 23:50 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> + * @returns
removed

2024-12-01 23:51 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> + * @returns
removed

2024-12-03 02:56 UTC, JFranklin3000 commented on templates/actor/parts/misc/collapsible-item-container-label-buttons.hbs
> +        <a class="shield-activate" data-id="{{item._id}}" {{#if system.active}} data-tooltip="Active"{{else}}data-tooltip="Passive"{{/if}} style="flex-grow: 0;"><i class="fas fa-shield"></i></a>
changed

2024-12-03 02:56 UTC, JFranklin3000 commented on templates/actor/parts/misc/pc-body.hbs
> +      {{> "systems/essence20/templates/actor/parts/items/shield/container.hbs"}}
I am good with adding it that is pretty quick,

2024-12-03 03:47 UTC, phildominguez requested changes

2024-12-03 03:47 UTC, phildominguez commented on templates/actor/parts/misc/collapsible-item-container-label-buttons.hbs
> +          {{/if}}
```suggestion
          {{#if system.active}}
            <i class="fas fa-shield-check fa-lg"></i>
          {{else}}
            <i class="fas fa-shield fa-lg"></i>
          {{/if}}
```
This looks better imo:
![image](https://github.com/user-attachments/assets/160f9476-8406-40a5-9d30-c0782b435514)

2024-12-03 03:47 UTC, phildominguez commented on templates/actor/parts/misc/collapsible-item-container-label-buttons.hbs
> +          {{#if system.active}} data-tooltip="Active" {{else}} data-tooltip="Passive" {{/if}}
I'm wondering if it's a little vague whether these titles refer to the current mode OR if they refer to what happens once they're clicked. What about something like `Current mode: Active`? These should be localized as well.

2024-12-03 03:47 UTC, phildominguez commented on templates/actor/parts/misc/collapsible-item-container-label-buttons.hbs
> +      {{#ifCond @root.shieldEquipped "&&" item.system.equipped}} {{else}} {{#if @root.shieldEquipped}} disabled {{/if}} {{/ifCond}}
```suggestion
      {{#if @root.shieldEquipped}} {{#unless item.system.equipped}} disabled {{/unless}} {{/if}}
```

2024-12-03 03:47 UTC, phildominguez commented on templates/app/shield-options.hbs
> +  <label>Select Shield Bonus</label>
Localize

2024-12-03 03:47 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> + * @param {*} actorSheet The actorSheet that the shield is being equipped or unequipped on
```suggestion
 * @param {ActorSheet} actorSheet The ActorSheet that the shield is being equipped or unequipped on
```

2024-12-03 03:47 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> + * @param {*} actorSheet The actorSheet that the shield is attached to.
```suggestion
 * @param {ActorSheet} actorSheet The ActorSheet that the shield is attached to.
```

2024-12-03 03:47 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> +  let currentShield = {};
```suggestion
  let currentShield = null;
```

2024-12-03 03:47 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> +  }
I see a lot of shared code between here and `onShieldActivationToggle`. Can we make a helper?

2024-12-03 03:47 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> +
```suggestion
```

2024-12-03 13:30 UTC, JFranklin3000 commented on templates/app/shield-options.hbs
> +  <label>Select Shield Bonus</label>
Deleting File as it is no longer used.

2024-12-03 13:38 UTC, JFranklin3000 commented on templates/actor/parts/misc/collapsible-item-container-label-buttons.hbs
> +          {{#if system.active}} data-tooltip="Active" {{else}} data-tooltip="Passive" {{/if}}
Changed

2024-12-04 01:38 UTC, phildominguez requested changes

2024-12-04 01:38 UTC, phildominguez commented on lang/en.json
> +    "ShieldOther": "Applies 1 other type of bonus",
```suggestion
    "ShieldDefense1Bonus": "Applies 1 defense bonus",
    "ShieldDefense1Of2Bonuses": "Applies 1 of 2 defense bonuses",
    "ShieldDefense1OtherBonus": "Applies 1 other type of bonus",
    "ShieldDefense2Bonuses": "Applies 2 defense bonuses",
    "ShieldDefenseMixedBonuses": "Applies 1 defense bonus or 1 other type of bonus",
    "ShieldNotEquipped": "This shield must be equipped to become activated.",
```
The diff looks bad but I just fixed the var names and sorted

2024-12-04 01:38 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> +
```suggestion
```

2024-12-04 01:38 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> +async function shieldUpdate(actor, currentShield, shieldState, stateString) {
Desc block

2024-12-04 01:38 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> + * @param {String} state Whether we are going to active or passive.
```suggestion
 * @param {String} state Whether we are going to active or passive.
 * @param {Integer} value The bonus amount.
 * @param {String} defense The defense that the bonus is being added to.
```
Just sorting

2024-12-04 01:38 UTC, phildominguez commented on templates/app/choice-select-prompt.hbs
> +        <button type="button" name="{{choice.defense}}" value="{{choice.value}}" data-action="{{../type}}">
Could this just be called choice.name, so that it can be useful elsewhere?

2024-12-04 01:38 UTC, phildominguez commented on lang/en.json
> +    "ShieldCurrentStatePassive": "Current mode: Passive",
Now that I think about it, should it be "state" instead of "mode"?

2024-12-04 04:35 UTC, JFranklin3000 commented on lang/en.json
> +    "ShieldCurrentStatePassive": "Current mode: Passive",
sure

2024-12-04 04:38 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> +async function shieldUpdate(actor, currentShield, shieldState, stateString) {
added

2024-12-04 13:26 UTC, phildominguez requested changes

2024-12-04 13:26 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> + * @param {Item} currentShield The shield that we are setting values from
```suggestion
 * @param {Shield} currentShield The shield that we are setting values from
```

2024-12-04 13:26 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> + * Handles setting the values of the shield that were selected from the Prompt
```suggestion
 * Handles setting the values of the shield that were selected from the prompt
```

2024-12-04 13:26 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> +async function shieldUpdate(actor, currentShield, shieldState, stateString) {
I think something is mixed up. `stateString` says it's a data location, but below we just check if it's equal to "activeEffect". And `shieldState` is a string, but below we're accessing it like an object (`shieldState.type`).

2024-12-04 23:14 UTC, phildominguez requested changes

2024-12-04 23:14 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> +    shieldUpdate(actor, currentShield, shieldState, stateString);
```suggestion
    shieldUpdate(actor, currentShield, 'passiveEffect');
```

2024-12-04 23:14 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> +  shieldUpdate(actor, currentShield, shieldState, stateString);
```suggestion
  const stateString = currentShield.system.active ?  'passiveEffect' : 'activeEffect';
  shieldUpdate(actor, currentShield, stateString);
```

2024-12-04 23:14 UTC, phildominguez commented on module/sheet-handlers/listener-item-handler.mjs
> +  if (shieldState.type == "defenseBonus" || shieldState.type == "defenseBonusCombo") {
```suggestion
 * @param {String} stateString The state the shield is going to
 */
async function shieldUpdate(actor, currentShield, stateString) {
  const shieldState = currentShield.system[stateString];

  if (shieldState.type == "defenseBonus" || shieldState.type == "defenseBonusCombo") {
```

2024-12-04 23:19 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> +  shieldUpdate(actor, currentShield, shieldState, stateString);
changed

2024-12-04 23:19 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> +  if (shieldState.type == "defenseBonus" || shieldState.type == "defenseBonusCombo") {
changed

2024-12-04 23:20 UTC, JFranklin3000 commented on module/sheet-handlers/listener-item-handler.mjs
> +    shieldUpdate(actor, currentShield, shieldState, stateString);
changed

2024-12-05 00:36 UTC, phildominguez approved these changes

2024-12-05 00:45 UTC, merged