Added Equipment Packages
WookieeMatt/Essence20 pull request #782
Opened 2024-12-07 03:25 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- Added Equipment Package as new Item Type
- Created the Missing items from Cobra Codex and Quartermaster's Guide to Gear
- Added a bug fix for the Focus has no Essence error

##### Testing
- Validate new items are good. 
- Validate Equipment Packages are working.

2024-12-07 19:48 UTC, phildominguez requested changes

2024-12-07 19:48 UTC, phildominguez commented on module/sheet-handlers/attachment-handler.mjs
> + * @param {Item} droppedItem The Item that is being dropped on the actor
This param needs to be an EquipmentPackage, not just an Item

2024-12-07 19:48 UTC, phildominguez commented on module/sheet-handlers/attachment-handler.mjs
> +        await createItemCopies(parentItem.system.items, actor, "weaponEffect", parentItem);
```suggestion
      if (["armor", "weapon"].includes(parentItem.type) {
        await createItemCopies(parentItem.system.items, actor, "upgrade", parentItem);
      }

      if (["shield", "weapon"].includes(parentItem.type) {
        await createItemCopies(parentItem.system.items, actor, "weaponEffect", parentItem);
```
Not tested

2024-12-07 19:48 UTC, phildominguez commented on module/sheet-handlers/attachment-handler.mjs
> +      } else if (parentItem.type == "shield") {
This shield check just made me notice that we are doing `createItemCopies` for shield upgrades in `gearDrop()`, I assume we don't want to

2024-12-07 19:48 UTC, phildominguez commented on module/sheet-handlers/attachment-handler.mjs
> +    }
```suggestion
    if (["armor", "gear", "shield", "weapon"].includes(droppedItem.type)) {
      entry['items'] = droppedItem.system.items;
      return _addItemIfUnique(droppedItem, targetItem, entry);
    }
```

2024-12-07 19:48 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +    html.find('.gear-delete').click(this._onObjectDelete.bind(this, ".gear"));
I don't see these used?

2024-12-07 19:48 UTC, phildominguez commented on templates/item/sheets/equipmentPackage.hbs
> +      {{#> "systems/essence20/templates/item/parts/sheet-field.hbs" label='E20.AlternateAccess'}}
Not defined

2024-12-07 20:02 UTC, phildominguez requested changes

2024-12-07 20:02 UTC, phildominguez commented on module/sheet-handlers/attachment-handler.mjs
> +  if (droppedItem.system.items) {
```suggestion
```
Is this checking if `items` is empty, or if it doesn't exist at all?

2024-12-07 20:23 UTC, JFranklin3000 commented on module/sheet-handlers/attachment-handler.mjs
> + * @param {Item} droppedItem The Item that is being dropped on the actor
changed

2024-12-07 20:27 UTC, JFranklin3000 commented on module/sheets/item-sheet.mjs
> +    html.find('.gear-delete').click(this._onObjectDelete.bind(this, ".gear"));
They are used in id-drop.hbs. ``<a class="item-control {{../className}}-delete flex-right" title="{{localize 'E20.DeleteItem'}}">``

2024-12-07 20:29 UTC, JFranklin3000 commented on templates/item/sheets/equipmentPackage.hbs
> +      {{#> "systems/essence20/templates/item/parts/sheet-field.hbs" label='E20.AlternateAccess'}}
defined now

2024-12-07 20:30 UTC, JFranklin3000 commented on module/sheet-handlers/attachment-handler.mjs
> +      } else if (parentItem.type == "shield") {
We don't allow the drop of upgrades on shields right now, so there wouldn't be any there to create a copy of.

2024-12-07 20:33 UTC, JFranklin3000 commented on module/sheet-handlers/attachment-handler.mjs
> +  if (droppedItem.system.items) {
if it is empty

2024-12-07 23:51 UTC, phildominguez requested changes

2024-12-07 23:51 UTC, phildominguez commented on module/sheet-handlers/attachment-handler.mjs
> +  if (droppedItem.system.items) {
![image](https://github.com/user-attachments/assets/4ca2a5af-3a0d-4b4b-a68b-6581c2b4af46)
Empty objects are truthy, and the `for` can handle empty objects fine, so we can remove this `if`

2024-12-07 23:51 UTC, phildominguez commented on module/sheets/item-sheet.mjs
> +    html.find('.gear-delete').click(this._onObjectDelete.bind(this, ".gear"));
Ah okay, all good. I do wonder if we can make this smarter at some point, because these and the other items are all basically doing the same thing?

2024-12-08 00:19 UTC, JFranklin3000 commented on module/sheet-handlers/attachment-handler.mjs
> +  if (droppedItem.system.items) {
ok cool pushed the fix.

2024-12-08 01:16 UTC, phildominguez approved these changes

2024-12-08 01:34 UTC, merged