Replaced Title with Data-tooltip
WookieeMatt/Essence20 pull request #788
Opened 2024-12-08 16:55 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- replaced title with data-tooltip
- fixed DeleteItem and DefenseShield that were missing from localization

##### Testing
- Navigate the sheets and validate things are working as expected.

2024-12-08 18:11 UTC, phildominguez requested changes

2024-12-08 18:11 UTC, phildominguez commented on templates/item/sheets/role.hbs
> +            <a class="trait-selector" data-options="armorType" data-target="system.armors.trained" data-tooltip="{{localize 'E20.TraitSelector'}}">
All the others have the format "Select ____". I feel like we should do "Select Traits" for these

2024-12-08 18:11 UTC, phildominguez commented on templates/item/sheets/role.hbs
> +            <a class="trait-selector" data-options="availabilities" data-target="system.upgrades.armors.trained" data-tooltip="{{localize 'E20.TraitSelector'}}">
E20.TraitSelector doesn't seem right for these and some below

2024-12-08 18:11 UTC, phildominguez commented on templates/item/sheets/rolePoints.hbs
> +          data-tooltip="{{localize 'E20.RolePointsIncreaseLevels'}}">
"Select levels"?

2024-12-08 18:11 UTC, phildominguez commented on templates/item/sheets/rolePoints.hbs
> +        data-tooltip="{{localize 'E20.EssenceSelector'}}">
```suggestion
        data-tooltip="{{localize 'E20.RolePointsIncreaseLevels'}}">
```

2024-12-09 01:02 UTC, JFranklin3000 commented on templates/actor/parts/headers/common.hbs
> +    <img class="profile-img" style="border-color: {{system.color}};" src="{{actor.img}}" data-edit="img" data-tooltip="{{actor.name}}" />
changed

2024-12-09 01:06 UTC, JFranklin3000 commented on templates/actor/parts/items/magicBauble/container.hbs
> +    <a class="rollable" data-roll-type="magicBauble"  data-tooltip="{{localize 'E20.MagicBaubleTitle'}}"><i class="fas fa-dice-d20"></i></a>
added

2024-12-09 01:07 UTC, JFranklin3000 commented on templates/actor/parts/items/power/container.hbs
> +      <a class="rollable" data-roll-type={{item.type}} data-tooltip="{{localize 'E20.PowerRollTitle'}}"><i class="fas fa-battery-bolt"></i></a>
changed

2024-12-09 01:09 UTC, JFranklin3000 commented on templates/actor/parts/items/rolePoints/container.hbs
> +        <a class="rollable" style="flex-grow: 0;" data-roll-type="rolePoints" data-tooltip="{{localize 'E20.RolePointsRoll'}}"><i
Changed

2024-12-09 01:10 UTC, JFranklin3000 commented on templates/actor/parts/items/shield/container.hbs
> +        <a class="rollable" data-roll-type="weaponEffect" data-tooltip="{{localize 'E20.WeaponRollTitle'}}"><i class="fas fa-dice-d20"></i></a>
changed

2024-12-09 01:11 UTC, JFranklin3000 commented on templates/actor/parts/misc/collapsible-item-container-header.hbs
> +    <a class="header-accordion-label" data-type={{dataType}} data-tooltip="{{ localize 'E20.ItemControlExpand' }}">
changed

2024-12-09 01:13 UTC, JFranklin3000 commented on templates/actor/parts/misc/system-actors.hbs
> +          <img class="zord-img" src="{{attachedActor.img}}" data-edit="img" data-tooltip="{{attachedActor.name}}" />
I don't think this one will actually let you change to image so that probably isn't a good idea.

2024-12-09 01:15 UTC, JFranklin3000 commented on templates/actor/parts/items/rolePoints/container.hbs
> +        <a class="rollable" style="flex-grow: 0;" data-roll-type="info" data-tooltip="{{localize 'E20.RolePoints'}}">
Changed

2024-12-09 01:17 UTC, JFranklin3000 commented on templates/item/parts/header.hbs
> +  <img class="profile-img" src="{{item.img}}" data-edit="img" data-tooltip="{{item.name}}"/>
changed

2024-12-09 01:33 UTC, JFranklin3000 commented on templates/actor/parts/misc/essence-skills.hbs
>    {{!-- Specializations header --}}
Added

2024-12-09 01:35 UTC, JFranklin3000 commented on templates/actor/parts/misc/health.hbs
> +        <input class="two-digit-input no-unlock" type="number" name="system.health.max" value="{{system.health.max}}" data-tooltip="{{system.health.string}}" readonly/>
I don't think this should be one. Removing

2024-12-09 01:39 UTC, JFranklin3000 commented on templates/item/sheets/rolePoints.hbs
> +          data-tooltip="{{localize 'E20.RolePointsIncreaseLevels'}}">
changed

2024-12-09 01:42 UTC, JFranklin3000 commented on templates/item/sheets/role.hbs
> +            <a class="trait-selector" data-options="availabilities" data-target="system.upgrades.armors.trained" data-tooltip="{{localize 'E20.TraitSelector'}}">
Changed to TrainingSelector

2024-12-09 01:45 UTC, JFranklin3000 commented on templates/actor/parts/misc/health.hbs
> +      <a class="rest" style="flex-grow: 0;" data-tooltip="{{localize "E20.RestButtonTitle"}}"><i class="fas fa-face-sleeping"></i></a>
changed to Take a rest

2024-12-09 03:07 UTC, phildominguez requested changes

2024-12-09 03:12 UTC, JFranklin3000 commented on lang/en.json
> +    "ItemControlExpand": "Expand all Items",
fix pushed.

2024-12-09 03:23 UTC, phildominguez approved these changes

2024-12-09 03:24 UTC, merged