Convert Crossover Options to sheet options
WookieeMatt/Essence20 pull request #805
Opened 2024-12-12 13:58 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- Created App V2 to replace existing Dialog

##### Testing
- validate why app opens at the same size as the character sheet.

2024-12-12 18:31 UTC, phildominguez requested changes

2024-12-12 18:31 UTC, phildominguez commented on templates/app/sheet-options.hbs
Cleaned up a bit

```hbs
<div class="trait-selector flexcol">
  {{#ifEquals actor.type "npc"}}
    {{#> "systems/essence20/templates/item/parts/sheet-field.hbs" label='E20.IsNPC'}}
    {{#*inline "item-field-inputs"}}
      <input type="checkbox" id="isNPC" name="system.isNPC" {{checked system.isNPC}} />
    {{/inline}}
    {{/"systems/essence20/templates/item/parts/sheet-field.hbs"}}

    {{#> "systems/essence20/templates/item/parts/sheet-field.hbs" label='E20.IsContact'}}
    {{#*inline "item-field-inputs"}}
      <input type="checkbox" id="isContact" name="system.isContact" {{checked system.isContact}} />
    {{/inline}}
    {{/"systems/essence20/templates/item/parts/sheet-field.hbs"}}
  {{/ifEquals}}

  {{#ifNotEquals role.system.version 'powerRanger'}}
    {{#> "systems/essence20/templates/item/parts/sheet-field.hbs" label='E20.CanMorph'}}
    {{#*inline "item-field-inputs"}}
      <input type="checkbox" id="canMorph" name="system.canMorph" {{checked system.canMorph}} />
    {{/inline}}
    {{/"systems/essence20/templates/item/parts/sheet-field.hbs"}}
  {{/ifNotEquals}}

  {{#ifNotEquals role.system.version 'myLittlePony'}}
    {{#> "systems/essence20/templates/item/parts/sheet-field.hbs" label='E20.CanSpellcast'}}
    {{#*inline "item-field-inputs"}}
      <input type="checkbox" id="canSpellcast" name="system.canSpellcast" {{checked system.canSpellcast}}/>
    {{/inline}}
    {{/"systems/essence20/templates/item/parts/sheet-field.hbs"}}
  {{/ifNotEquals}}

  {{#unless altMode}}
    {{#> "systems/essence20/templates/item/parts/sheet-field.hbs" label='E20.CanTransform'}}
    {{#*inline "item-field-inputs"}}
      <input type="checkbox" id="canTransform" name="system.canTransform" {{checked system.canTransform}}/>
    {{/inline}}
    {{/"systems/essence20/templates/item/parts/sheet-field.hbs"}}
  {{/unless}}
</div>
```

2024-12-12 18:31 UTC, phildominguez commented on templates/app/sheet-options.hbs
> +      {{/"systems/essence20/templates/item/parts/sheet-field.hbs"}}
I think we should make a new hbs instead of the one we use for item sheets

2024-12-13 00:11 UTC, JFranklin3000 commented on templates/app/sheet-options.hbs
Changed

2024-12-13 00:11 UTC, JFranklin3000 commented on templates/app/sheet-options.hbs
> +      {{/"systems/essence20/templates/item/parts/sheet-field.hbs"}}
I made a copy for now and put it in templates/app/parts. Should we move the existing hbs files to a subfolder?>

2024-12-13 17:00 UTC, phildominguez requested changes

2024-12-13 17:00 UTC, phildominguez commented on templates/app/parts/sheet-field.hbs
It's not being used in sheet-options.hbs. Also I think just name it field.hbs or something.

2024-12-13 20:42 UTC, JFranklin3000 commented on templates/app/parts/sheet-field.hbs
weird I changed it but it didn't take, I needed to add it to the template.mjs anyway,

2024-12-13 23:03 UTC, phildominguez requested changes

2024-12-13 23:03 UTC, phildominguez commented on templates/app/parts/field.hbs
> +</div>
```suggestion
<div class="flexrow">
  <div class="flexrow" style="gap: 5px;">
    <label style="flex-grow: 0; white-space: nowrap;">{{localize label}}</label>
    {{#> field-edit}}
    {{!-- Custom field edit button goes here --}}
    {{/field-edit}}
  </div>

  <div style="flex-grow: 0;">
    {{#> field-inputs}}
    {{!-- Custom inputs go here --}}
    {{/field-inputs}}
  </div>
</div>
```
The `inline` stuff in sheet-options.hbs will have to be changed from `item-field-edit` to `field-edit` and `item-field-inputs` to `field-inputs`.

2024-12-13 23:59 UTC, phildominguez approved these changes

2024-12-14 00:00 UTC, merged