Move the remaining Dialogs to Application V2
WookieeMatt/Essence20 pull request #833
Opened 2024-12-29 20:42 UTC by JFranklin3000

Closes [issue URL]

##### In this PR
- transform choices now an application
- Essence Selection for Roles now an application
- Alteration Essence modifications now  an application
- 

##### Testing
- Drop an alteration with an essence choice
- Use Modemaster to the test the Essence Selection applications
- give an actor at least 2 alt modes and transform.

2024-12-30 00:18 UTC, phildominguez requested changes

2024-12-30 00:18 UTC, phildominguez commented on module/apps/alteration-essence-prompt.mjs
What about alteration-skill-prompt? Or alteration-essence-skill-prompt? Since the selection is for a skill, not an essence.

2024-12-30 00:18 UTC, phildominguez commented on module/apps/alteration-essence-prompt.mjs
> +      }
This seems to be a recurring operation. Helper method that any app can use?

2024-12-30 00:18 UTC, phildominguez commented on module/apps/essence-select.mjs
essence-progression-select? Similar for class name.

2024-12-30 00:18 UTC, phildominguez commented on module/apps/multi-select-essence.mjs
> +export default class MultiSelectPrompt extends HandlebarsApplicationMixin(ApplicationV2) {
"essence" should be in this class name

2024-12-30 00:18 UTC, phildominguez commented on module/apps/multi-select-essence.mjs
> +    for (const [, selection] of Object.entries(formData.object)) {
Don't need to worry about this now, but it would be neat if we could disable the 2 remaining checkboxes if 2 have already been selected. Maybe with an hbs helper?

2024-12-30 00:18 UTC, phildominguez commented on templates/app/essence-select.hbs
> +
```suggestion
```

2024-12-30 00:18 UTC, phildominguez commented on templates/app/essence-select.hbs
> +
```suggestion
```

2024-12-30 00:18 UTC, phildominguez commented on templates/app/alteration-movement.hbs
> +
```suggestion
```

2024-12-30 01:45 UTC, JFranklin3000 commented on module/apps/alteration-essence-prompt.mjs
So the thought process is that the alteration is raising 1 essence by 1 and decreasing another essence by 1, the better the alteration the more options you get for what the cost is.

2024-12-30 01:58 UTC, JFranklin3000 commented on module/apps/multi-select-essence.mjs
> +    for (const [, selection] of Object.entries(formData.object)) {
Noted.

2024-12-30 01:59 UTC, JFranklin3000 commented on templates/app/essence-select.hbs
> +
removed

2024-12-30 01:59 UTC, JFranklin3000 commented on templates/app/essence-select.hbs
> +
removed

2024-12-30 01:59 UTC, JFranklin3000 commented on templates/app/alteration-movement.hbs
> +
removed

2024-12-30 02:00 UTC, JFranklin3000 commented on module/apps/alteration-essence-prompt.mjs
> +      }
helper created. I am leaving the dialog helpers for now, although none of them are used anymore.

2024-12-30 02:01 UTC, JFranklin3000 commented on module/apps/multi-select-essence.mjs
> +export default class MultiSelectPrompt extends HandlebarsApplicationMixin(ApplicationV2) {
changed

2024-12-30 02:02 UTC, JFranklin3000 commented on module/apps/alteration-essence-prompt.mjs
> +export default class OptionSelectPrompt extends HandlebarsApplicationMixin(ApplicationV2) {
Changed to AlterationEssencePrompt

2024-12-30 02:04 UTC, JFranklin3000 commented on module/apps/essence-select.mjs
EssenceProgressionSelectPrompt

2024-12-30 15:11 UTC, phildominguez requested changes

2024-12-30 15:11 UTC, phildominguez commented on module/apps/alteration-essence-prompt.mjs
> +}
```suggestion
  static async myFormHandler(event, form, formData) {
    const selection = getFormData(formData.object);

    if (!this._bonusSkill) {
      _processAlterationSkillIncrease(this._actor, this._alteration, selection, this._alterationUuid, this._dropFunc);
    } else if (!this._costEssence && this._alteration.system.essenceCost.length > 1) {
      _showAlterationCostSkillDialog(this._actor, this._alteration, this._bonusSkill, this._alterationUuid, selection, this._dropFunc);
    } else {
      _alterationStatUpdate(this._actor, this._alteration, this._bonusSkill, this._costEssence, selection, this._alterationUuid, this._dropFunc);
    }
  }
}
```
Not tested

2024-12-30 17:25 UTC, phildominguez requested changes

2024-12-30 17:25 UTC, phildominguez commented on module/apps/power-cost.mjs
> +export default class PowerCostSelector extends HandlebarsApplicationMixin(ApplicationV2) {
Should this file name also be power-cost-selector?

2025-01-03 00:09 UTC, phildominguez approved these changes

2025-01-03 00:19 UTC, merged