Zord sheet redesign
WookieeMatt/Essence20 pull request #85
Opened 2022-07-18 15:05 UTC by guswadsworth12

Large changes to the Zord and Megazord sheet. Also edited some UI elements.

2022-07-18 23:34 UTC, phildominguez requested changes
👍 Lmk if you need assistance with the conflicts 👍

2022-07-18 23:34 UTC, phildominguez commented on lang/en.json
> +    "TypeZordcombiner": "Zord Component",
I think we should leave these as Zord Combiner until we change it everywhere at the same time.

2022-07-18 23:34 UTC, phildominguez commented on css/essence20.css
> +/* ----- ZORD SHEET STYLING ---- */
I assume we can split these up into separate files somehow, yeah? I can't handle 1400 lines lol. Can put this off until next change, though.

2022-07-18 23:34 UTC, phildominguez commented on templates/actor/parts/actor-zordcombiner.hbs
> +<span class="flex-group-center">
4 space indentations in this file 😲

2022-07-18 23:35 UTC, phildominguez commented
> Lots of conflicts here. Holy moly.

LOL yeah, it happens. Generally it's a good idea to keep PRs smaller and focused on one feature/fix to avoid conflicts.

2022-07-19 20:19 UTC, guswadsworth12 commented on css/essence20.css
> +/* ----- ZORD SHEET STYLING ---- */
This will involve getting ourselves both set up with sass and less as a preprocessor. Will research.

2022-07-21 03:10 UTC, phildominguez approved these changes

2022-07-21 03:11 UTC, merged